/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QuerySecuritySettingsQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { querySecuritySettings } from "../../clients.ts";

export const querySecuritySettingsSuspenseQueryKey = () => [{ url: '/api/desk/security-settings' }] as const

export type QuerySecuritySettingsSuspenseQueryKey = ReturnType<typeof querySecuritySettingsSuspenseQueryKey>

export function querySecuritySettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = querySecuritySettingsSuspenseQueryKey()
        return queryOptions<QuerySecuritySettingsQueryResponse, ResponseErrorConfig<Error>, QuerySecuritySettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return querySecuritySettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query security settings
 * {@link /api/desk/security-settings}
 */
export function useQuerySecuritySettingsSuspense<TData = QuerySecuritySettingsQueryResponse, TQueryKey extends QueryKey = QuerySecuritySettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QuerySecuritySettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? querySecuritySettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...querySecuritySettingsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}