/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuerySecuritySettingsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { querySecuritySettings } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const querySecuritySettingsQueryKey = () => [{ url: '/api/desk/security-settings' }] as const

export type QuerySecuritySettingsQueryKey = ReturnType<typeof querySecuritySettingsQueryKey>

export function querySecuritySettingsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = querySecuritySettingsQueryKey()
        return queryOptions<QuerySecuritySettingsQueryResponse, ResponseErrorConfig<Error>, QuerySecuritySettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return querySecuritySettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query security settings
 * {@link /api/desk/security-settings}
 */
export function useQuerySecuritySettings<TData = QuerySecuritySettingsQueryResponse, TQueryData = QuerySecuritySettingsQueryResponse, TQueryKey extends QueryKey = QuerySecuritySettingsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QuerySecuritySettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? querySecuritySettingsQueryKey()
         

         const query = useQuery({
          ...querySecuritySettingsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}