/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateSecuritySettingsMutationRequest, UpdateSecuritySettingsMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateSecuritySettings } from "../../clients.ts";

export const updateSecuritySettingsMutationKey = () => [{ url: '/api/desk/security-settings' }] as const

export type UpdateSecuritySettingsMutationKey = ReturnType<typeof updateSecuritySettingsMutationKey>

export function updateSecuritySettingsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateSecuritySettingsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateSecuritySettingsMutationKey()
        return mutationOptions<UpdateSecuritySettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateSecuritySettingsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateSecuritySettings(data, config)
          },
        })

}

/**
 * @summary Update security settings
 * {@link /api/desk/security-settings}
 */
export function useUpdateSecuritySettings<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateSecuritySettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateSecuritySettingsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateSecuritySettingsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateSecuritySettingsMutationKey()

          const baseOptions = updateSecuritySettingsMutationOptions(config) as UseMutationOptions<UpdateSecuritySettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateSecuritySettingsMutationRequest}, TContext>
          

          return useMutation<UpdateSecuritySettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateSecuritySettingsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateSecuritySettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateSecuritySettingsMutationRequest}, TContext>
      
}