/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteDeviceCodeMutationResponse, DeleteDeviceCodePathParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteDeviceCode } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteDeviceCodeMutationKey = () => [{ url: '/api/desk/device_codes/:id' }] as const

export type DeleteDeviceCodeMutationKey = ReturnType<typeof deleteDeviceCodeMutationKey>

export function deleteDeviceCodeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteDeviceCodeMutationKey()
        return mutationOptions<DeleteDeviceCodeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteDeviceCodePathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteDeviceCode(id, config)
          },
        })

}

/**
 * @summary Delete device code
 * {@link /api/desk/device_codes/:id}
 */
export function useDeleteDeviceCode<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteDeviceCodeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteDeviceCodePathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteDeviceCodeMutationKey()

          const baseOptions = deleteDeviceCodeMutationOptions(config) as UseMutationOptions<DeleteDeviceCodeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteDeviceCodePathParams["id"]}, TContext>
          

          return useMutation<DeleteDeviceCodeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteDeviceCodePathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteDeviceCodeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteDeviceCodePathParams["id"]}, TContext>
      
}