/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  ListDeviceCodesQueryResponse,
  ListDeviceCodesQueryParams,
} from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { listDeviceCodes } from "../../clients.ts";

export const listDeviceCodesSuspenseQueryKey = (
  params?: ListDeviceCodesQueryParams,
) => [{ url: "/api/desk/device_codes" }, ...(params ? [params] : [])] as const;

export type ListDeviceCodesSuspenseQueryKey = ReturnType<
  typeof listDeviceCodesSuspenseQueryKey
>;

export function listDeviceCodesSuspenseQueryOptions(
  params?: ListDeviceCodesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listDeviceCodesSuspenseQueryKey(params);
  return queryOptions<
    ListDeviceCodesQueryResponse,
    ResponseErrorConfig<Error>,
    ListDeviceCodesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listDeviceCodes(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List device codes
 * {@link /api/desk/device_codes}
 */
export function useListDeviceCodesSuspense<
  TData = ListDeviceCodesQueryResponse,
  TQueryKey extends QueryKey = ListDeviceCodesSuspenseQueryKey,
>(
  params?: ListDeviceCodesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListDeviceCodesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? listDeviceCodesSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...listDeviceCodesSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
