/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListDeviceCodesQueryResponse, ListDeviceCodesQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listDeviceCodes } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listDeviceCodesQueryKey = (params?: ListDeviceCodesQueryParams) => [{ url: '/api/desk/device_codes' }, ...(params ? [params] : [])] as const

export type ListDeviceCodesQueryKey = ReturnType<typeof listDeviceCodesQueryKey>

export function listDeviceCodesQueryOptions(params?: ListDeviceCodesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listDeviceCodesQueryKey(params)
        return queryOptions<ListDeviceCodesQueryResponse, ResponseErrorConfig<Error>, ListDeviceCodesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listDeviceCodes(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List device codes
 * {@link /api/desk/device_codes}
 */
export function useListDeviceCodes<TData = ListDeviceCodesQueryResponse, TQueryData = ListDeviceCodesQueryResponse, TQueryKey extends QueryKey = ListDeviceCodesQueryKey>(params?: ListDeviceCodesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListDeviceCodesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listDeviceCodesQueryKey(params)
         

         const query = useQuery({
          ...listDeviceCodesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}