/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTerminalCompletionQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getTerminalCompletion } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getTerminalCompletionSuspenseQueryKey = () => [{ url: '/api/admin/system/terminal-completion' }] as const

export type GetTerminalCompletionSuspenseQueryKey = ReturnType<typeof getTerminalCompletionSuspenseQueryKey>

export function getTerminalCompletionSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTerminalCompletionSuspenseQueryKey()
        return queryOptions<GetTerminalCompletionQueryResponse, ResponseErrorConfig<Error>, GetTerminalCompletionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getTerminalCompletion({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/admin/system/terminal-completion}
 */
export function useGetTerminalCompletionSuspense<TData = GetTerminalCompletionQueryResponse, TQueryKey extends QueryKey = GetTerminalCompletionSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetTerminalCompletionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getTerminalCompletionSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getTerminalCompletionSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}