/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTerminalCompletionQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getTerminalCompletion } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getTerminalCompletionQueryKey = () => [{ url: '/api/admin/system/terminal-completion' }] as const

export type GetTerminalCompletionQueryKey = ReturnType<typeof getTerminalCompletionQueryKey>

export function getTerminalCompletionQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTerminalCompletionQueryKey()
        return queryOptions<GetTerminalCompletionQueryResponse, ResponseErrorConfig<Error>, GetTerminalCompletionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getTerminalCompletion({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/admin/system/terminal-completion}
 */
export function useGetTerminalCompletion<TData = GetTerminalCompletionQueryResponse, TQueryData = GetTerminalCompletionQueryResponse, TQueryKey extends QueryKey = GetTerminalCompletionQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetTerminalCompletionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getTerminalCompletionQueryKey()
         

         const query = useQuery({
          ...getTerminalCompletionQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}