[package]
name = "desk-capture-engine"
description = "Screen/audio capture and encoding engine for lcxl-remote-desk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
desk-utils = { workspace = true }
desk-signal-facade = { workspace = true }

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
utoipa = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }

yuv = "0.8"
x264 = { git = "https://github.com/lcxl/x264.git", tag = "v0.7.1" }
openh264 = "0.9.3"
rav1e = { version = "0.8" }

opusic-c = "1.5"

cpal = "0.15"
ringbuf = "0.4"

vpx-encode = { git = "https://github.com/lcxl/vpx-encode.git", tag = "v0.7.0", features = [
    "vp9",
] }

png = "0.17"
image = "0.25"
prometheus = "0.13.4"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61", features = [
    "Win32_Devices_FunctionDiscovery",
    "Win32_UI_HiDpi",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Globalization",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Hlsl",
    "Win32_Media_Audio",
    "Win32_Media_KernelStreaming",
    "Win32_Media_MediaFoundation",
    "Win32_Media_Multimedia",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_StationsAndDesktops",
    "Win32_System_SystemInformation",
    "Win32_System_Variant",
    "Win32_System_Threading",
    "Win32_System_Performance",
] }
windows-result = "0.3"
windows-core = "0.61"
windows-numerics = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.13", features = ["all-extensions"] }
libc = "0.2"
alsa = "0.9"
pipewire = "0.8"
xcb = { version = "1.5", features = ["randr"] }
zbus = "5.6"

[target.'cfg(target_os = "macos")'.dependencies]
screencapturekit = "0.2"
screencapturekit-sys = "0.2"
objc2 = "0.5"
objc2-foundation = "0.2"
core-graphics = { version = "0.23", features = ["highsierra"] }
core-audio-types = "0.2"

[dev-dependencies]
image = "0.25"
hound = "3.5"
tempfile = "3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }
