/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetGoalBudgetPolicyQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getGoalBudgetPolicy } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getGoalBudgetPolicySuspenseQueryKey = () => [{ url: '/api/admin/system/goal-budget-policy' }] as const

export type GetGoalBudgetPolicySuspenseQueryKey = ReturnType<typeof getGoalBudgetPolicySuspenseQueryKey>

export function getGoalBudgetPolicySuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getGoalBudgetPolicySuspenseQueryKey()
        return queryOptions<GetGoalBudgetPolicyQueryResponse, ResponseErrorConfig<Error>, GetGoalBudgetPolicyQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getGoalBudgetPolicy({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/admin/system/goal-budget-policy}
 */
export function useGetGoalBudgetPolicySuspense<TData = GetGoalBudgetPolicyQueryResponse, TQueryKey extends QueryKey = GetGoalBudgetPolicySuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetGoalBudgetPolicyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getGoalBudgetPolicySuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getGoalBudgetPolicySuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}