/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTurnUsageQueryResponse, GetTurnUsageQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getTurnUsage } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getTurnUsageSuspenseQueryKey = (params?: GetTurnUsageQueryParams) => [{ url: '/api/turn/usage' }, ...(params ? [params] : [])] as const

export type GetTurnUsageSuspenseQueryKey = ReturnType<typeof getTurnUsageSuspenseQueryKey>

export function getTurnUsageSuspenseQueryOptions(params?: GetTurnUsageQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTurnUsageSuspenseQueryKey(params)
        return queryOptions<GetTurnUsageQueryResponse, ResponseErrorConfig<Error>, GetTurnUsageQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getTurnUsage(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query local per-device TURN usage
 * {@link /api/turn/usage}
 */
export function useGetTurnUsageSuspense<TData = GetTurnUsageQueryResponse, TQueryKey extends QueryKey = GetTurnUsageSuspenseQueryKey>(params?: GetTurnUsageQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetTurnUsageQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getTurnUsageSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getTurnUsageSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}