[workspace]
members = [
    "signal-facade",
    "server",
    "turn",
    "utils",
    "server-version",
    "signal",
    "server-user",
    "capture-engine",
    "input-injection",
    "ipc-protocol",
    "tauri-app/src-tauri",
]
exclude = ["web", "third-deps"]
resolver = "3"

[workspace.package]
description = "Lcxl Remote Desk Web Server"
version = "0.1.0"
edition = "2024"
# need file lock feature 1.89.0
# see https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.try_lock
# need 1.90.0 for rust-analyzer
rust-version = "1.90"


[workspace.dependencies]
desk-ipc-protocol = { path = "ipc-protocol" }
desk-utils = { path = "utils" }
desk-turn = { path = "turn" }
desk-signal-facade = { path = "signal-facade" }
desk-server-version = { path = "server-version" }
desk-signal = { path = "signal" }
desk-server-user = { path = "server-user" }
lcxl-remote-desk-server = { path = "server" }
desk-capture-engine = { path = "capture-engine" }
desk-input-injection = { path = "input-injection" }

clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
chrono = { version = "0.4", features = ["serde"] }

utoipa = { version = "5", features = ["actix_extras", "chrono"] }
utoipa_repr = "0.1"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
utoipa-actix-web = "0.1"
utoipa-redoc = { version = "6", features = ["actix-web"] }
utoipa-rapidoc = { version = "6", features = ["actix-web"] }
utoipa-scalar = { version = "0.3", features = ["actix-web"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_urlencoded = "0.7"
bincode = "2.0"
wincode = { version = "0.5", features = ["derive"] }
tokio-util = { version = "0.7", features = ["codec"] }

turn = "0.17"
webrtc-util = "0.17"
hmac = "0.12"
sha1 = "0.10"
base64 = "0.22"
async-trait = "0.1"
futures = "0.3"
futures-util = "0.3"
anyhow = "1.0"
tokio = { version = "1.47", features = ["full", "tracing"] }
console-subscriber = "0.5"

actix-web = "4.11"
actix-ws = "0.3"
actix-session = { version = "0.11", features = ["cookie-session"] }
actix-files = "0.6"
actix-server = "2.6"
actix-http = "3.11"
actix-rt = "2"
awc = { version = "3.5", features = ["rustls-0_23"] }
actix-service = "2.0"

rustls = "0.23"
rustls-native-certs = "0.8"

webrtc = "0.17"
webrtc-media = "0.17"
webrtc-ice = "0.17"
rtp = "0.17"
rtcp = "0.17"
webrtc-mdns = "0.17"

strum = "0.27"
strum_macros = "0.27"
bytes = "1.10"
bytestring = "1.4"
uuid = "1.20"
portable-pty = "0.9"

url = "2.5.8"

sea-orm = { version = "2.0.0-rc", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
sea-orm-migration = "2.0.0-rc"

rand = { version = "0.9", features = ["std"] }

rust-i18n = "3.1"

mime = "0.3"
yuv = "0.8"
x264 = { git = "https://github.com/lcxl/x264.git", tag = "v0.7.2" }
openh264 = "0.9.3"
rav1e = "0.8" 
vpx-encode = { git = "https://github.com/lcxl/vpx-encode.git", tag = "v0.7.0", features = [
    "vp9",
] }
opusic-c = "1.5"

cpal = "0.15"
ringbuf = "0.4"

toml = "0.9"
config = { version = "0.15", features = ["toml"] }

codepage = "0.1"
encoding_rs = "0.8"
regex = "1.11"
prometheus = "0.13.4"
png = "0.17"
image = "0.25"

sysinfo = "0.37"

opentelemetry = { version = "0.31.0", features = ["metrics", "trace"] }
opentelemetry-otlp = { version = "0.31.0", features = [
    "metrics",
    "trace",
    "grpc-tonic",
] }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
tracing = "0.1"
tracing-opentelemetry = "0.32.1"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }

trash = "5.2.5"

auto-launch = "0.6.0"
once_cell = "1.21.4"

ureq = { version = "2", features = ["json"] }

hound = "3.5"
tempfile = "3"

# for windows
windows = { version = "0.61", features = [
    "Win32_Devices_FunctionDiscovery",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Animation",
    "Win32_UI_HiDpi",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Globalization",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Hlsl",
    "Win32_Media_Audio",
    "Win32_Media_KernelStreaming",
    "Win32_Media_MediaFoundation",
    "Win32_Media_Multimedia",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_StationsAndDesktops",
    "Win32_System_SystemInformation",
    "Win32_System_Variant",
    "Win32_System_Threading",
    "Win32_System_Performance",
    "Win32_System_Services",
    "Win32_System_RemoteDesktop",
    "Win32_System_Environment",
    "Win32_Foundation",
] }
windows-result = "0.3"
windows-core = "0.61"
windows-numerics = "0.2"
windows-service = "0.8"

which = { version = "8.0", features = ["regex"] }

# for unix (linux & macos)
libc = "0.2"

# for linux
alsa = "0.9"
pipewire = "0.8"
zbus = "5.6"
x11rb = { version = "0.13", features = ["all-extensions"] }
evdev = { version = "0.13", features = ["stream-trait"] }
raw-window-handle = "0.6"
xcb = { version = "1.5", features = ["randr"] }

# for macos
screencapturekit = "0.2"
screencapturekit-sys = "0.2"
objc2 = "0.5"
objc2-foundation = "0.2"
core-graphics = { version = "0.23", features = ["highsierra"] }
core-audio-types = "0.2"