[workspace]
members = ["server"]
exclude = ["web", "third-deps"]
resolver = "3"

[workspace.package]
description = "Lcxl Remote Desk Web Server"
version = "0.1.0"
edition = "2024"
# need file lock feature 1.89.0
# see https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.try_lock
# need 1.90.0 for rust-analyzer
rust-version = "1.90"


[workspace.dependencies]