[workspace]
members = [
    "signal-facade",
    "server",
    "turn",
    "utils",
    "server-version",
    "signal",
    "server-user",
    "tauri-app/src-tauri",
]
exclude = ["web", "third-deps"]
resolver = "3"

[workspace.package]
description = "Lcxl Remote Desk Web Server"
version = "0.1.0"
edition = "2024"
# need file lock feature 1.89.0
# see https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.try_lock
# need 1.90.0 for rust-analyzer
rust-version = "1.90"


[workspace.dependencies]
desk-utils = { path = "utils" }
desk-turn = { path = "turn" }
desk-signal-facade = { path = "signal-facade" }
desk-server-version = { path = "server-version" }
desk-signal = { path = "signal" }
desk-server-user = { path = "server-user" }
lcxl-remote-desk-server = { path = "server" }

clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
chrono = { version = "0.4", features = ["serde"] }

utoipa = { version = "5", features = ["actix_extras", "chrono"] }
utoipa_repr = "0.1"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
utoipa-actix-web = "0.1"
utoipa-redoc = { version = "6", features = ["actix-web"] }
utoipa-rapidoc = { version = "6", features = ["actix-web"] }
utoipa-scalar = { version = "0.3", features = ["actix-web"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_urlencoded = "0.7"

turn = "0.17"
webrtc-util = "0.17"
hmac = "0.12"
sha1 = "0.10"
base64 = "0.22"
async-trait = "0.1"
futures = "0.3"
futures-util = "0.3"
anyhow = "1.0"
tokio = { version = "1.47", features = ["full", "tracing"] }

actix-web = "4.11"
actix-ws = "0.3"
actix-session = { version = "0.11", features = ["cookie-session"] }
actix-files = "0.6"
actix-server = "2.6"
actix-http = "3.11"
awc = { version = "3.5", features = ["rustls-0_23"] }
actix-service = "2.0"

rustls = "0.23"
rustls-native-certs = "0.8"

webrtc = "0.17"
webrtc-media = "0.17"
webrtc-ice = "0.17"
rtp = "0.17"
webrtc-mdns = "0.17"

strum = "0.27"
strum_macros = "0.27"
bytes = "1.10"
bytestring = "1.4"
uuid = "1.20"
portable-pty = "0.9"

url = "2.5.8"

sea-orm = { version = "2.0.0-rc", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
sea-orm-migration = "2.0.0-rc"

rand = { version = "0.9", features = ["std"] }

rust-i18n = "3.1"
