/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetUsageRetentionQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getUsageRetention } from "../../clients.ts";

export const getUsageRetentionSuspenseQueryKey = () => [{ url: '/api/usage/usage-retention' }] as const

export type GetUsageRetentionSuspenseQueryKey = ReturnType<typeof getUsageRetentionSuspenseQueryKey>

export function getUsageRetentionSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUsageRetentionSuspenseQueryKey()
        return queryOptions<GetUsageRetentionQueryResponse, ResponseErrorConfig<Error>, GetUsageRetentionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getUsageRetention({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the usage-rollup retention windows
 * {@link /api/usage/usage-retention}
 */
export function useGetUsageRetentionSuspense<TData = GetUsageRetentionQueryResponse, TQueryKey extends QueryKey = GetUsageRetentionSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetUsageRetentionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUsageRetentionSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getUsageRetentionSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}