/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { InitRequirementsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { initRequirements } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const initRequirementsQueryKey = () => [{ url: '/api/init/requirements' }] as const

export type InitRequirementsQueryKey = ReturnType<typeof initRequirementsQueryKey>

export function initRequirementsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = initRequirementsQueryKey()
        return queryOptions<InitRequirementsQueryResponse, ResponseErrorConfig<Error>, InitRequirementsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return initRequirements({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query standalone initialization requirements
 * {@link /api/init/requirements}
 */
export function useInitRequirements<TData = InitRequirementsQueryResponse, TQueryData = InitRequirementsQueryResponse, TQueryKey extends QueryKey = InitRequirementsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<InitRequirementsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? initRequirementsQueryKey()
         

         const query = useQuery({
          ...initRequirementsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}