/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { QueryServerInfoQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { queryServerInfo } from "../../clients.ts";

export const queryServerInfoSuspenseQueryKey = () =>
  [{ url: "/api/server_info" }] as const;

export type QueryServerInfoSuspenseQueryKey = ReturnType<
  typeof queryServerInfoSuspenseQueryKey
>;

export function queryServerInfoSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = queryServerInfoSuspenseQueryKey();
  return queryOptions<
    QueryServerInfoQueryResponse,
    ResponseErrorConfig<Error>,
    QueryServerInfoQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return queryServerInfo({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get server information
 * {@link /api/server_info}
 */
export function useQueryServerInfoSuspense<
  TData = QueryServerInfoQueryResponse,
  TQueryKey extends QueryKey = QueryServerInfoSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        QueryServerInfoQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? queryServerInfoSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...queryServerInfoSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
