/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QueryMacosAutologinQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryMacosAutologin } from "../../clients.ts";

export const queryMacosAutologinQueryKey = () => [{ url: '/api/desk/macos/autologin' }] as const

export type QueryMacosAutologinQueryKey = ReturnType<typeof queryMacosAutologinQueryKey>

export function queryMacosAutologinQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryMacosAutologinQueryKey()
        return queryOptions<QueryMacosAutologinQueryResponse, ResponseErrorConfig<Error>, QueryMacosAutologinQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryMacosAutologin({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get macOS automatic-login helper status
 * {@link /api/desk/macos/autologin}
 */
export function useQueryMacosAutologin<TData = QueryMacosAutologinQueryResponse, TQueryData = QueryMacosAutologinQueryResponse, TQueryKey extends QueryKey = QueryMacosAutologinQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryMacosAutologinQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryMacosAutologinQueryKey()
         

         const query = useQuery({
          ...queryMacosAutologinQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}