/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryBackendInfoQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryBackendInfo } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const queryBackendInfoQueryKey = () => [{ url: '/api/desk/backend_info' }] as const

export type QueryBackendInfoQueryKey = ReturnType<typeof queryBackendInfoQueryKey>

export function queryBackendInfoQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryBackendInfoQueryKey()
        return queryOptions<QueryBackendInfoQueryResponse, ResponseErrorConfig<Error>, QueryBackendInfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryBackendInfo({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get backend diagnostics
 * {@link /api/desk/backend_info}
 */
export function useQueryBackendInfo<TData = QueryBackendInfoQueryResponse, TQueryData = QueryBackendInfoQueryResponse, TQueryKey extends QueryKey = QueryBackendInfoQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryBackendInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryBackendInfoQueryKey()
         

         const query = useQuery({
          ...queryBackendInfoQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}