/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QueryBackendInfoQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { queryBackendInfo } from "../../clients.ts";

export const queryBackendInfoSuspenseQueryKey = () => [{ url: '/api/desk/backend_info' }] as const

export type QueryBackendInfoSuspenseQueryKey = ReturnType<typeof queryBackendInfoSuspenseQueryKey>

export function queryBackendInfoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryBackendInfoSuspenseQueryKey()
        return queryOptions<QueryBackendInfoQueryResponse, ResponseErrorConfig<Error>, QueryBackendInfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return queryBackendInfo(config)
         },
        })

}

/**
 * @summary Get backend diagnostics
 * {@link /api/desk/backend_info}
 */
export function useQueryBackendInfoSuspense<TData = QueryBackendInfoQueryResponse, TQueryKey extends QueryKey = QueryBackendInfoSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryBackendInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? queryBackendInfoSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryBackendInfoSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}