/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QuerySysinfoQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { querySysinfo } from "../../clients.ts";

export const querySysinfoQueryKey = () => [{ url: '/api/desk/sysinfo' }] as const

export type QuerySysinfoQueryKey = ReturnType<typeof querySysinfoQueryKey>

export function querySysinfoQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = querySysinfoQueryKey()
        return queryOptions<QuerySysinfoQueryResponse, ResponseErrorConfig<Error>, QuerySysinfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return querySysinfo({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get system information
 * {@link /api/desk/sysinfo}
 */
export function useQuerySysinfo<TData = QuerySysinfoQueryResponse, TQueryData = QuerySysinfoQueryResponse, TQueryKey extends QueryKey = QuerySysinfoQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QuerySysinfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? querySysinfoQueryKey()
         

         const query = useQuery({
          ...querySysinfoQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}