/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetMySubagentPolicyQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getMySubagentPolicy } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMySubagentPolicyQueryKey = () => [{ url: '/api/my/ai-assistant-session/subagent-policy' }] as const

export type GetMySubagentPolicyQueryKey = ReturnType<typeof getMySubagentPolicyQueryKey>

export function getMySubagentPolicyQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getMySubagentPolicyQueryKey()
        return queryOptions<GetMySubagentPolicyQueryResponse, ResponseErrorConfig<Error>, GetMySubagentPolicyQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getMySubagentPolicy({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/ai-assistant-session/subagent-policy}
 */
export function useGetMySubagentPolicy<TData = GetMySubagentPolicyQueryResponse, TQueryData = GetMySubagentPolicyQueryResponse, TQueryKey extends QueryKey = GetMySubagentPolicyQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetMySubagentPolicyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getMySubagentPolicyQueryKey()
         

         const query = useQuery({
          ...getMySubagentPolicyQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}