/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetMyGoalBudgetPolicyQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getMyGoalBudgetPolicy } from "../../clients.ts";

export const getMyGoalBudgetPolicySuspenseQueryKey = () => [{ url: '/api/my/ai-assistant-session/goal/budget-policy' }] as const

export type GetMyGoalBudgetPolicySuspenseQueryKey = ReturnType<typeof getMyGoalBudgetPolicySuspenseQueryKey>

export function getMyGoalBudgetPolicySuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getMyGoalBudgetPolicySuspenseQueryKey()
        return queryOptions<GetMyGoalBudgetPolicyQueryResponse, ResponseErrorConfig<Error>, GetMyGoalBudgetPolicyQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getMyGoalBudgetPolicy({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/ai-assistant-session/goal/budget-policy}
 */
export function useGetMyGoalBudgetPolicySuspense<TData = GetMyGoalBudgetPolicyQueryResponse, TQueryKey extends QueryKey = GetMyGoalBudgetPolicySuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMyGoalBudgetPolicyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getMyGoalBudgetPolicySuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getMyGoalBudgetPolicySuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}