/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetMyGoalBudgetPolicyQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getMyGoalBudgetPolicy } from "../../clients.ts";

export const getMyGoalBudgetPolicyQueryKey = () => [{ url: '/api/my/ai-assistant-session/goal/budget-policy' }] as const

export type GetMyGoalBudgetPolicyQueryKey = ReturnType<typeof getMyGoalBudgetPolicyQueryKey>

export function getMyGoalBudgetPolicyQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getMyGoalBudgetPolicyQueryKey()
        return queryOptions<GetMyGoalBudgetPolicyQueryResponse, ResponseErrorConfig<Error>, GetMyGoalBudgetPolicyQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getMyGoalBudgetPolicy({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/ai-assistant-session/goal/budget-policy}
 */
export function useGetMyGoalBudgetPolicy<TData = GetMyGoalBudgetPolicyQueryResponse, TQueryData = GetMyGoalBudgetPolicyQueryResponse, TQueryKey extends QueryKey = GetMyGoalBudgetPolicyQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetMyGoalBudgetPolicyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getMyGoalBudgetPolicyQueryKey()
         

         const query = useQuery({
          ...getMyGoalBudgetPolicyQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}