/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  UpdateTelemetryConsentMutationRequest,
  UpdateTelemetryConsentMutationResponse,
} from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateTelemetryConsent } from "../../clients.ts";

export const updateTelemetryConsentMutationKey = () =>
  [{ url: "/api/desk/telemetry/consent" }] as const;

export type UpdateTelemetryConsentMutationKey = ReturnType<
  typeof updateTelemetryConsentMutationKey
>;

export function updateTelemetryConsentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateTelemetryConsentMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = updateTelemetryConsentMutationKey();
  return mutationOptions<
    UpdateTelemetryConsentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateTelemetryConsentMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return updateTelemetryConsent(data, config);
    },
  });
}

/**
 * @summary Update telemetry consent
 * {@link /api/desk/telemetry/consent}
 */
export function useUpdateTelemetryConsent<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateTelemetryConsentMutationResponse,
      ResponseErrorConfig<Error>,
      { data: UpdateTelemetryConsentMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateTelemetryConsentMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? updateTelemetryConsentMutationKey();

  const baseOptions = updateTelemetryConsentMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateTelemetryConsentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateTelemetryConsentMutationRequest },
    TContext
  >;

  return useMutation<
    UpdateTelemetryConsentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateTelemetryConsentMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateTelemetryConsentMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateTelemetryConsentMutationRequest },
    TContext
  >;
}
