/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetContextManagementQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getContextManagement } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getContextManagementQueryKey = () => [{ url: '/api/admin/system/ai-context-management' }] as const

export type GetContextManagementQueryKey = ReturnType<typeof getContextManagementQueryKey>

export function getContextManagementQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getContextManagementQueryKey()
        return queryOptions<GetContextManagementQueryResponse, ResponseErrorConfig<Error>, GetContextManagementQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getContextManagement({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/admin/system/ai-context-management}
 */
export function useGetContextManagement<TData = GetContextManagementQueryResponse, TQueryData = GetContextManagementQueryResponse, TQueryKey extends QueryKey = GetContextManagementQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetContextManagementQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getContextManagementQueryKey()
         

         const query = useQuery({
          ...getContextManagementQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}