/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QuerySettingsQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { querySettings } from "../../clients.ts";

export const querySettingsQueryKey = () => [{ url: '/api/desk/settings' }] as const

export type QuerySettingsQueryKey = ReturnType<typeof querySettingsQueryKey>

export function querySettingsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = querySettingsQueryKey()
        return queryOptions<QuerySettingsQueryResponse, ResponseErrorConfig<Error>, QuerySettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return querySettings(config)
         },
        })

}

/**
 * @summary Query settings
 * {@link /api/desk/settings}
 */
export function useQuerySettings<TData = QuerySettingsQueryResponse, TQueryData = QuerySettingsQueryResponse, TQueryKey extends QueryKey = QuerySettingsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QuerySettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? querySettingsQueryKey()
         

         const query = useQuery({
          ...querySettingsQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}