use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(AgentExecTask::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AgentExecTask::Id)
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::ExecRequestId)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::ExecutionGeneration)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::ConversationId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::ToolCallId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::TargetConnectionId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AgentExecTask::Status).string().not_null())
                    .col(ColumnDef::new(AgentExecTask::DispositionJson).text())
                    .col(ColumnDef::new(AgentExecTask::ResultText).text())
                    .col(
                        ColumnDef::new(AgentExecTask::EventId)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::DeliveryState)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::Deadline)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AgentExecTask::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx-agent-exec-task-delivery")
                    .table(AgentExecTask::Table)
                    .col(AgentExecTask::DeliveryState)
                    .col(AgentExecTask::Status)
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(AgentExecTask::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(Iden)]
enum AgentExecTask {
    Table,
    Id,
    ExecRequestId,
    ExecutionGeneration,
    ConversationId,
    ToolCallId,
    TargetConnectionId,
    Status,
    DispositionJson,
    ResultText,
    EventId,
    DeliveryState,
    Deadline,
    CreatedAt,
    UpdatedAt,
}
