/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryLogSettingsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryLogSettings } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const queryLogSettingsSuspenseQueryKey = () => [{ url: '/api/desk/settings/log' }] as const

export type QueryLogSettingsSuspenseQueryKey = ReturnType<typeof queryLogSettingsSuspenseQueryKey>

export function queryLogSettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryLogSettingsSuspenseQueryKey()
        return queryOptions<QueryLogSettingsQueryResponse, ResponseErrorConfig<Error>, QueryLogSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryLogSettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query log settings
 * {@link /api/desk/settings/log}
 */
export function useQueryLogSettingsSuspense<TData = QueryLogSettingsQueryResponse, TQueryKey extends QueryKey = QueryLogSettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryLogSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryLogSettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryLogSettingsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}