/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QueryLogSettingsQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryLogSettings } from "../../clients.ts";

export const queryLogSettingsQueryKey = () => [{ url: '/api/desk/settings/log' }] as const

export type QueryLogSettingsQueryKey = ReturnType<typeof queryLogSettingsQueryKey>

export function queryLogSettingsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryLogSettingsQueryKey()
        return queryOptions<QueryLogSettingsQueryResponse, ResponseErrorConfig<Error>, QueryLogSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryLogSettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query log settings
 * {@link /api/desk/settings/log}
 */
export function useQueryLogSettings<TData = QueryLogSettingsQueryResponse, TQueryData = QueryLogSettingsQueryResponse, TQueryKey extends QueryKey = QueryLogSettingsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryLogSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryLogSettingsQueryKey()
         

         const query = useQuery({
          ...queryLogSettingsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}