/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  UpdateLogSettingsMutationRequest,
  UpdateLogSettingsMutationResponse,
} from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateLogSettings } from "../../clients.ts";

export const updateLogSettingsMutationKey = () =>
  [{ url: "/api/desk/settings/log" }] as const;

export type UpdateLogSettingsMutationKey = ReturnType<
  typeof updateLogSettingsMutationKey
>;

export function updateLogSettingsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateLogSettingsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = updateLogSettingsMutationKey();
  return mutationOptions<
    UpdateLogSettingsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateLogSettingsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return updateLogSettings(data, config);
    },
  });
}

/**
 * @summary Update log settings
 * {@link /api/desk/settings/log}
 */
export function useUpdateLogSettings<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateLogSettingsMutationResponse,
      ResponseErrorConfig<Error>,
      { data: UpdateLogSettingsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateLogSettingsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? updateLogSettingsMutationKey();

  const baseOptions = updateLogSettingsMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateLogSettingsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateLogSettingsMutationRequest },
    TContext
  >;

  return useMutation<
    UpdateLogSettingsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateLogSettingsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateLogSettingsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: UpdateLogSettingsMutationRequest },
    TContext
  >;
}
