name: Rust Coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpipewire-0.3-dev pkg-config libclang-dev libasound2-dev libssl-dev libvpx-dev cmake

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.90.0
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests and collect coverage
        id: coverage
        run: cargo llvm-cov --all-features --workspace --no-report --no-fail-fast
        env:
          RUST_BACKTRACE: 1
        continue-on-error: true
      - name: Generate coverage report
        run: cargo llvm-cov report --html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov/html
      - name: Check for test failures
        if: steps.coverage.outcome == 'failure'
        run: exit 1
