/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthorizeWaylandMutationRequest, AuthorizeWaylandMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authorizeWayland } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authorizeWaylandMutationKey = () => [{ url: '/api/host-readiness/wayland/authorize' }] as const

export type AuthorizeWaylandMutationKey = ReturnType<typeof authorizeWaylandMutationKey>

export function authorizeWaylandMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AuthorizeWaylandMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = authorizeWaylandMutationKey()
        return mutationOptions<AuthorizeWaylandMutationResponse, ResponseErrorConfig<Error>, {data: AuthorizeWaylandMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return authorizeWayland(data, config)
          },
        })

}

/**
 * @summary Start local Wayland Portal authorization
 * {@link /api/host-readiness/wayland/authorize}
 */
export function useAuthorizeWayland<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthorizeWaylandMutationResponse, ResponseErrorConfig<Error>, {data: AuthorizeWaylandMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthorizeWaylandMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? authorizeWaylandMutationKey()

          const baseOptions = authorizeWaylandMutationOptions(config) as UseMutationOptions<AuthorizeWaylandMutationResponse, ResponseErrorConfig<Error>, {data: AuthorizeWaylandMutationRequest}, TContext>
          

          return useMutation<AuthorizeWaylandMutationResponse, ResponseErrorConfig<Error>, {data: AuthorizeWaylandMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AuthorizeWaylandMutationResponse, ResponseErrorConfig<Error>, {data: AuthorizeWaylandMutationRequest}, TContext>
      
}