/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CancelWaylandMutationRequest, CancelWaylandMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { cancelWayland } from "../../clients.ts";

export const cancelWaylandMutationKey = () => [{ url: '/api/host-readiness/wayland/cancel' }] as const

export type CancelWaylandMutationKey = ReturnType<typeof cancelWaylandMutationKey>

export function cancelWaylandMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CancelWaylandMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = cancelWaylandMutationKey()
        return mutationOptions<CancelWaylandMutationResponse, ResponseErrorConfig<Error>, {data: CancelWaylandMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return cancelWayland(data, config)
          },
        })

}

/**
 * @summary Cancel local Wayland Portal authorization
 * {@link /api/host-readiness/wayland/cancel}
 */
export function useCancelWayland<TContext>(options: 
{
  mutation?: UseMutationOptions<CancelWaylandMutationResponse, ResponseErrorConfig<Error>, {data: CancelWaylandMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CancelWaylandMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? cancelWaylandMutationKey()

          const baseOptions = cancelWaylandMutationOptions(config) as UseMutationOptions<CancelWaylandMutationResponse, ResponseErrorConfig<Error>, {data: CancelWaylandMutationRequest}, TContext>
          

          return useMutation<CancelWaylandMutationResponse, ResponseErrorConfig<Error>, {data: CancelWaylandMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CancelWaylandMutationResponse, ResponseErrorConfig<Error>, {data: CancelWaylandMutationRequest}, TContext>
      
}