/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OpenSignalingHandleQueryResponse, OpenSignalingHandleQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { openSignalingHandle } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const openSignalingHandleQueryKey = (params: OpenSignalingHandleQueryParams) => [{ url: '/api/desk/signaling' }, ...(params ? [params] : [])] as const

export type OpenSignalingHandleQueryKey = ReturnType<typeof openSignalingHandleQueryKey>

export function openSignalingHandleQueryOptions(params: OpenSignalingHandleQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = openSignalingHandleQueryKey(params)
        return queryOptions<OpenSignalingHandleQueryResponse, ResponseErrorConfig<Error>, OpenSignalingHandleQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return openSignalingHandle(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Open signaling handle and return a WebSocket stream
 * {@link /api/desk/signaling}
 */
export function useOpenSignalingHandle<TData = OpenSignalingHandleQueryResponse, TQueryData = OpenSignalingHandleQueryResponse, TQueryKey extends QueryKey = OpenSignalingHandleQueryKey>(params: OpenSignalingHandleQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<OpenSignalingHandleQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? openSignalingHandleQueryKey(params)
         

         const query = useQuery({
          ...openSignalingHandleQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}