/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { QueryTurnClientSettingsQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryTurnClientSettings } from "../../clients.ts";

export const queryTurnClientSettingsQueryKey = () =>
  [{ url: "/api/desk/settings/turn-client" }] as const;

export type QueryTurnClientSettingsQueryKey = ReturnType<
  typeof queryTurnClientSettingsQueryKey
>;

export function queryTurnClientSettingsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = queryTurnClientSettingsQueryKey();
  return queryOptions<
    QueryTurnClientSettingsQueryResponse,
    ResponseErrorConfig<Error>,
    QueryTurnClientSettingsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return queryTurnClientSettings({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Query turn client settings
 * {@link /api/desk/settings/turn-client}
 */
export function useQueryTurnClientSettings<
  TData = QueryTurnClientSettingsQueryResponse,
  TQueryData = QueryTurnClientSettingsQueryResponse,
  TQueryKey extends QueryKey = QueryTurnClientSettingsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        QueryTurnClientSettingsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? queryTurnClientSettingsQueryKey();

  const query = useQuery(
    {
      ...queryTurnClientSettingsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
