/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QueryTurnClientSettingsQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { queryTurnClientSettings } from "../../clients.ts";

export const queryTurnClientSettingsSuspenseQueryKey = () => [{ url: '/api/desk/settings/turn-client' }] as const

export type QueryTurnClientSettingsSuspenseQueryKey = ReturnType<typeof queryTurnClientSettingsSuspenseQueryKey>

export function queryTurnClientSettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryTurnClientSettingsSuspenseQueryKey()
        return queryOptions<QueryTurnClientSettingsQueryResponse, ResponseErrorConfig<Error>, QueryTurnClientSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return queryTurnClientSettings(config)
         },
        })

}

/**
 * @summary Query turn client settings
 * {@link /api/desk/settings/turn-client}
 */
export function useQueryTurnClientSettingsSuspense<TData = QueryTurnClientSettingsQueryResponse, TQueryKey extends QueryKey = QueryTurnClientSettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryTurnClientSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? queryTurnClientSettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryTurnClientSettingsSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}