[package]
name = "desk-server-user"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
utoipa = { workspace = true }
actix-session = { workspace = true }
desk-signal-facade = { workspace = true }
