/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetApprovalModelProviderQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getApprovalModelProvider } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApprovalModelProviderQueryKey = () => [{ url: '/api/model/approval-provider' }] as const

export type GetApprovalModelProviderQueryKey = ReturnType<typeof getApprovalModelProviderQueryKey>

export function getApprovalModelProviderQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApprovalModelProviderQueryKey()
        return queryOptions<GetApprovalModelProviderQueryResponse, ResponseErrorConfig<Error>, GetApprovalModelProviderQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApprovalModelProvider({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query masked independent approval model configuration
 * {@link /api/model/approval-provider}
 */
export function useGetApprovalModelProvider<TData = GetApprovalModelProviderQueryResponse, TQueryData = GetApprovalModelProviderQueryResponse, TQueryKey extends QueryKey = GetApprovalModelProviderQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetApprovalModelProviderQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApprovalModelProviderQueryKey()
         

         const query = useQuery({
          ...getApprovalModelProviderQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}