/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReuseAiGatewayForApprovalMutationRequest, ReuseAiGatewayForApprovalMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { reuseAiGatewayForApproval } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const reuseAiGatewayForApprovalMutationKey = () => [{ url: '/api/model/approval-provider/reuse-ai-gateway' }] as const

export type ReuseAiGatewayForApprovalMutationKey = ReturnType<typeof reuseAiGatewayForApprovalMutationKey>

export function reuseAiGatewayForApprovalMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ReuseAiGatewayForApprovalMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = reuseAiGatewayForApprovalMutationKey()
        return mutationOptions<ReuseAiGatewayForApprovalMutationResponse, ResponseErrorConfig<Error>, {data: ReuseAiGatewayForApprovalMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return reuseAiGatewayForApproval(data, config)
          },
        })

}

/**
 * @summary Copy the saved AI gateway into the independent approval model
 * {@link /api/model/approval-provider/reuse-ai-gateway}
 */
export function useReuseAiGatewayForApproval<TContext>(options: 
{
  mutation?: UseMutationOptions<ReuseAiGatewayForApprovalMutationResponse, ResponseErrorConfig<Error>, {data: ReuseAiGatewayForApprovalMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ReuseAiGatewayForApprovalMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? reuseAiGatewayForApprovalMutationKey()

          const baseOptions = reuseAiGatewayForApprovalMutationOptions(config) as UseMutationOptions<ReuseAiGatewayForApprovalMutationResponse, ResponseErrorConfig<Error>, {data: ReuseAiGatewayForApprovalMutationRequest}, TContext>
          

          return useMutation<ReuseAiGatewayForApprovalMutationResponse, ResponseErrorConfig<Error>, {data: ReuseAiGatewayForApprovalMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ReuseAiGatewayForApprovalMutationResponse, ResponseErrorConfig<Error>, {data: ReuseAiGatewayForApprovalMutationRequest}, TContext>
      
}