/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CancelDeviceAssistantBackgroundTaskMutationRequest, CancelDeviceAssistantBackgroundTaskMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { cancelDeviceAssistantBackgroundTask } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const cancelDeviceAssistantBackgroundTaskMutationKey = () => [{ url: '/api/my/device-assistant-session/background-task/cancel' }] as const

export type CancelDeviceAssistantBackgroundTaskMutationKey = ReturnType<typeof cancelDeviceAssistantBackgroundTaskMutationKey>

export function cancelDeviceAssistantBackgroundTaskMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CancelDeviceAssistantBackgroundTaskMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = cancelDeviceAssistantBackgroundTaskMutationKey()
        return mutationOptions<CancelDeviceAssistantBackgroundTaskMutationResponse, ResponseErrorConfig<Error>, {data: CancelDeviceAssistantBackgroundTaskMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return cancelDeviceAssistantBackgroundTask(data, config)
          },
        })

}

/**
 * @summary Request cancellation of an authorized Device Assistant background task
 * {@link /api/my/device-assistant-session/background-task/cancel}
 */
export function useCancelDeviceAssistantBackgroundTask<TContext>(options: 
{
  mutation?: UseMutationOptions<CancelDeviceAssistantBackgroundTaskMutationResponse, ResponseErrorConfig<Error>, {data: CancelDeviceAssistantBackgroundTaskMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CancelDeviceAssistantBackgroundTaskMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? cancelDeviceAssistantBackgroundTaskMutationKey()

          const baseOptions = cancelDeviceAssistantBackgroundTaskMutationOptions(config) as UseMutationOptions<CancelDeviceAssistantBackgroundTaskMutationResponse, ResponseErrorConfig<Error>, {data: CancelDeviceAssistantBackgroundTaskMutationRequest}, TContext>
          

          return useMutation<CancelDeviceAssistantBackgroundTaskMutationResponse, ResponseErrorConfig<Error>, {data: CancelDeviceAssistantBackgroundTaskMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CancelDeviceAssistantBackgroundTaskMutationResponse, ResponseErrorConfig<Error>, {data: CancelDeviceAssistantBackgroundTaskMutationRequest}, TContext>
      
}