/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteDeviceAssistantSessionMutationRequest, DeleteDeviceAssistantSessionMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteDeviceAssistantSession } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteDeviceAssistantSessionMutationKey = () => [{ url: '/api/my/device-assistant-session/delete' }] as const

export type DeleteDeviceAssistantSessionMutationKey = ReturnType<typeof deleteDeviceAssistantSessionMutationKey>

export function deleteDeviceAssistantSessionMutationOptions<TContext = unknown>(config: Partial<RequestConfig<DeleteDeviceAssistantSessionMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = deleteDeviceAssistantSessionMutationKey()
        return mutationOptions<DeleteDeviceAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: DeleteDeviceAssistantSessionMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return deleteDeviceAssistantSession(data, config)
          },
        })

}

/**
 * @summary Delete a Device Assistant conversation and stop its AI turn
 * {@link /api/my/device-assistant-session/delete}
 */
export function useDeleteDeviceAssistantSession<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteDeviceAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: DeleteDeviceAssistantSessionMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<DeleteDeviceAssistantSessionMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteDeviceAssistantSessionMutationKey()

          const baseOptions = deleteDeviceAssistantSessionMutationOptions(config) as UseMutationOptions<DeleteDeviceAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: DeleteDeviceAssistantSessionMutationRequest}, TContext>
          

          return useMutation<DeleteDeviceAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: DeleteDeviceAssistantSessionMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteDeviceAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: DeleteDeviceAssistantSessionMutationRequest}, TContext>
      
}