/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DecideDeviceAssistantPermissionMutationRequest, DecideDeviceAssistantPermissionMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { decideDeviceAssistantPermission } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const decideDeviceAssistantPermissionMutationKey = () => [{ url: '/api/my/device-assistant-session/permission-decision' }] as const

export type DecideDeviceAssistantPermissionMutationKey = ReturnType<typeof decideDeviceAssistantPermissionMutationKey>

export function decideDeviceAssistantPermissionMutationOptions<TContext = unknown>(config: Partial<RequestConfig<DecideDeviceAssistantPermissionMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = decideDeviceAssistantPermissionMutationKey()
        return mutationOptions<DecideDeviceAssistantPermissionMutationResponse, ResponseErrorConfig<Error>, {data: DecideDeviceAssistantPermissionMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return decideDeviceAssistantPermission(data, config)
          },
        })

}

/**
 * @summary Decide one pending Device Assistant permission request
 * {@link /api/my/device-assistant-session/permission-decision}
 */
export function useDecideDeviceAssistantPermission<TContext>(options: 
{
  mutation?: UseMutationOptions<DecideDeviceAssistantPermissionMutationResponse, ResponseErrorConfig<Error>, {data: DecideDeviceAssistantPermissionMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<DecideDeviceAssistantPermissionMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? decideDeviceAssistantPermissionMutationKey()

          const baseOptions = decideDeviceAssistantPermissionMutationOptions(config) as UseMutationOptions<DecideDeviceAssistantPermissionMutationResponse, ResponseErrorConfig<Error>, {data: DecideDeviceAssistantPermissionMutationRequest}, TContext>
          

          return useMutation<DecideDeviceAssistantPermissionMutationResponse, ResponseErrorConfig<Error>, {data: DecideDeviceAssistantPermissionMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DecideDeviceAssistantPermissionMutationResponse, ResponseErrorConfig<Error>, {data: DecideDeviceAssistantPermissionMutationRequest}, TContext>
      
}