/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DisposeDeviceAssistantUnknownOutcomeMutationRequest, DisposeDeviceAssistantUnknownOutcomeMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { disposeDeviceAssistantUnknownOutcome } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const disposeDeviceAssistantUnknownOutcomeMutationKey = () => [{ url: '/api/my/device-assistant-session/outcome-unknown/dispose' }] as const

export type DisposeDeviceAssistantUnknownOutcomeMutationKey = ReturnType<typeof disposeDeviceAssistantUnknownOutcomeMutationKey>

export function disposeDeviceAssistantUnknownOutcomeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<DisposeDeviceAssistantUnknownOutcomeMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = disposeDeviceAssistantUnknownOutcomeMutationKey()
        return mutationOptions<DisposeDeviceAssistantUnknownOutcomeMutationResponse, ResponseErrorConfig<Error>, {data: DisposeDeviceAssistantUnknownOutcomeMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return disposeDeviceAssistantUnknownOutcome(data, config)
          },
        })

}

/**
 * @summary Manually dispose one exact unknown Device Assistant action
 * {@link /api/my/device-assistant-session/outcome-unknown/dispose}
 */
export function useDisposeDeviceAssistantUnknownOutcome<TContext>(options: 
{
  mutation?: UseMutationOptions<DisposeDeviceAssistantUnknownOutcomeMutationResponse, ResponseErrorConfig<Error>, {data: DisposeDeviceAssistantUnknownOutcomeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<DisposeDeviceAssistantUnknownOutcomeMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? disposeDeviceAssistantUnknownOutcomeMutationKey()

          const baseOptions = disposeDeviceAssistantUnknownOutcomeMutationOptions(config) as UseMutationOptions<DisposeDeviceAssistantUnknownOutcomeMutationResponse, ResponseErrorConfig<Error>, {data: DisposeDeviceAssistantUnknownOutcomeMutationRequest}, TContext>
          

          return useMutation<DisposeDeviceAssistantUnknownOutcomeMutationResponse, ResponseErrorConfig<Error>, {data: DisposeDeviceAssistantUnknownOutcomeMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DisposeDeviceAssistantUnknownOutcomeMutationResponse, ResponseErrorConfig<Error>, {data: DisposeDeviceAssistantUnknownOutcomeMutationRequest}, TContext>
      
}