/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetDeviceAssistantSessionQueryResponse, GetDeviceAssistantSessionQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getDeviceAssistantSession } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getDeviceAssistantSessionSuspenseQueryKey = (params: GetDeviceAssistantSessionQueryParams) => [{ url: '/api/my/device-assistant-session' }, ...(params ? [params] : [])] as const

export type GetDeviceAssistantSessionSuspenseQueryKey = ReturnType<typeof getDeviceAssistantSessionSuspenseQueryKey>

export function getDeviceAssistantSessionSuspenseQueryOptions(params: GetDeviceAssistantSessionQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getDeviceAssistantSessionSuspenseQueryKey(params)
        return queryOptions<GetDeviceAssistantSessionQueryResponse, ResponseErrorConfig<Error>, GetDeviceAssistantSessionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getDeviceAssistantSession(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Read a Device Assistant conversation snapshot (browser view)
 * {@link /api/my/device-assistant-session}
 */
export function useGetDeviceAssistantSessionSuspense<TData = GetDeviceAssistantSessionQueryResponse, TQueryKey extends QueryKey = GetDeviceAssistantSessionSuspenseQueryKey>(params: GetDeviceAssistantSessionQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDeviceAssistantSessionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getDeviceAssistantSessionSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getDeviceAssistantSessionSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}