/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetAssistantAttachmentQueryResponse, GetAssistantAttachmentQueryParams } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getAssistantAttachment } from "../../clients.ts";

export const getAssistantAttachmentQueryKey = (params: GetAssistantAttachmentQueryParams) => [{ url: '/api/my/device-assistant-session/attachment' }, ...(params ? [params] : [])] as const

export type GetAssistantAttachmentQueryKey = ReturnType<typeof getAssistantAttachmentQueryKey>

export function getAssistantAttachmentQueryOptions(params: GetAssistantAttachmentQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getAssistantAttachmentQueryKey(params)
        return queryOptions<GetAssistantAttachmentQueryResponse, ResponseErrorConfig<Error>, GetAssistantAttachmentQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getAssistantAttachment(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/device-assistant-session/attachment}
 */
export function useGetAssistantAttachment<TData = GetAssistantAttachmentQueryResponse, TQueryData = GetAssistantAttachmentQueryResponse, TQueryKey extends QueryKey = GetAssistantAttachmentQueryKey>(params: GetAssistantAttachmentQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetAssistantAttachmentQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getAssistantAttachmentQueryKey(params)
         

         const query = useQuery({
          ...getAssistantAttachmentQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}