/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetAssistantImageQueryResponse, GetAssistantImageQueryParams, GetAssistantImage404 } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getAssistantImage } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAssistantImageSuspenseQueryKey = (params: GetAssistantImageQueryParams) => [{ url: '/api/my/device-assistant-session/image' }, ...(params ? [params] : [])] as const

export type GetAssistantImageSuspenseQueryKey = ReturnType<typeof getAssistantImageSuspenseQueryKey>

export function getAssistantImageSuspenseQueryOptions(params: GetAssistantImageQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getAssistantImageSuspenseQueryKey(params)
        return queryOptions<GetAssistantImageQueryResponse, ResponseErrorConfig<GetAssistantImage404>, GetAssistantImageQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getAssistantImage(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/device-assistant-session/image}
 */
export function useGetAssistantImageSuspense<TData = GetAssistantImageQueryResponse, TQueryKey extends QueryKey = GetAssistantImageSuspenseQueryKey>(params: GetAssistantImageQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetAssistantImageQueryResponse, ResponseErrorConfig<GetAssistantImage404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getAssistantImageSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getAssistantImageSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetAssistantImage404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}