/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListAssistantImagesQueryResponse, ListAssistantImagesQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listAssistantImages } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listAssistantImagesQueryKey = (params: ListAssistantImagesQueryParams) => [{ url: '/api/my/device-assistant-session/images' }, ...(params ? [params] : [])] as const

export type ListAssistantImagesQueryKey = ReturnType<typeof listAssistantImagesQueryKey>

export function listAssistantImagesQueryOptions(params: ListAssistantImagesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listAssistantImagesQueryKey(params)
        return queryOptions<ListAssistantImagesQueryResponse, ResponseErrorConfig<Error>, ListAssistantImagesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listAssistantImages(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/device-assistant-session/images}
 */
export function useListAssistantImages<TData = ListAssistantImagesQueryResponse, TQueryData = ListAssistantImagesQueryResponse, TQueryKey extends QueryKey = ListAssistantImagesQueryKey>(params: ListAssistantImagesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListAssistantImagesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listAssistantImagesQueryKey(params)
         

         const query = useQuery({
          ...listAssistantImagesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}