/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListAssistantImagesQueryResponse, ListAssistantImagesQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { listAssistantImages } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listAssistantImagesSuspenseQueryKey = (params: ListAssistantImagesQueryParams) => [{ url: '/api/my/device-assistant-session/images' }, ...(params ? [params] : [])] as const

export type ListAssistantImagesSuspenseQueryKey = ReturnType<typeof listAssistantImagesSuspenseQueryKey>

export function listAssistantImagesSuspenseQueryOptions(params: ListAssistantImagesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listAssistantImagesSuspenseQueryKey(params)
        return queryOptions<ListAssistantImagesQueryResponse, ResponseErrorConfig<Error>, ListAssistantImagesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listAssistantImages(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/device-assistant-session/images}
 */
export function useListAssistantImagesSuspense<TData = ListAssistantImagesQueryResponse, TQueryKey extends QueryKey = ListAssistantImagesSuspenseQueryKey>(params: ListAssistantImagesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListAssistantImagesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listAssistantImagesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...listAssistantImagesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}