/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListDeviceAssistantSessionsQueryResponse, ListDeviceAssistantSessionsQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { listDeviceAssistantSessions } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listDeviceAssistantSessionsSuspenseQueryKey = (params: ListDeviceAssistantSessionsQueryParams) => [{ url: '/api/my/device-assistant-sessions' }, ...(params ? [params] : [])] as const

export type ListDeviceAssistantSessionsSuspenseQueryKey = ReturnType<typeof listDeviceAssistantSessionsSuspenseQueryKey>

export function listDeviceAssistantSessionsSuspenseQueryOptions(params: ListDeviceAssistantSessionsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listDeviceAssistantSessionsSuspenseQueryKey(params)
        return queryOptions<ListDeviceAssistantSessionsQueryResponse, ResponseErrorConfig<Error>, ListDeviceAssistantSessionsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listDeviceAssistantSessions(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List recent Device Assistant conversations for a device
 * {@link /api/my/device-assistant-sessions}
 */
export function useListDeviceAssistantSessionsSuspense<TData = ListDeviceAssistantSessionsQueryResponse, TQueryKey extends QueryKey = ListDeviceAssistantSessionsSuspenseQueryKey>(params: ListDeviceAssistantSessionsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListDeviceAssistantSessionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listDeviceAssistantSessionsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...listDeviceAssistantSessionsSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}