/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { ReadAssistantAttachmentMutationRequest, ReadAssistantAttachmentMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { readAssistantAttachment } from "../../clients.ts";

export const readAssistantAttachmentMutationKey = () => [{ url: '/api/my/device-assistant-session/attachment/read' }] as const

export type ReadAssistantAttachmentMutationKey = ReturnType<typeof readAssistantAttachmentMutationKey>

export function readAssistantAttachmentMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ReadAssistantAttachmentMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = readAssistantAttachmentMutationKey()
        return mutationOptions<ReadAssistantAttachmentMutationResponse, ResponseErrorConfig<Error>, {data: ReadAssistantAttachmentMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return readAssistantAttachment(data, config)
          },
        })

}

/**
 * {@link /api/my/device-assistant-session/attachment/read}
 */
export function useReadAssistantAttachment<TContext>(options: 
{
  mutation?: UseMutationOptions<ReadAssistantAttachmentMutationResponse, ResponseErrorConfig<Error>, {data: ReadAssistantAttachmentMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ReadAssistantAttachmentMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? readAssistantAttachmentMutationKey()

          const baseOptions = readAssistantAttachmentMutationOptions(config) as UseMutationOptions<ReadAssistantAttachmentMutationResponse, ResponseErrorConfig<Error>, {data: ReadAssistantAttachmentMutationRequest}, TContext>
          

          return useMutation<ReadAssistantAttachmentMutationResponse, ResponseErrorConfig<Error>, {data: ReadAssistantAttachmentMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ReadAssistantAttachmentMutationResponse, ResponseErrorConfig<Error>, {data: ReadAssistantAttachmentMutationRequest}, TContext>
      
}