/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetDiagnoseSessionQueryResponse, GetDiagnoseSessionQueryParams } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDiagnoseSession } from "../../clients.ts";

export const getDiagnoseSessionQueryKey = (params: GetDiagnoseSessionQueryParams) => [{ url: '/api/my/diagnose-session' }, ...(params ? [params] : [])] as const

export type GetDiagnoseSessionQueryKey = ReturnType<typeof getDiagnoseSessionQueryKey>

export function getDiagnoseSessionQueryOptions(params: GetDiagnoseSessionQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getDiagnoseSessionQueryKey(params)
        return queryOptions<GetDiagnoseSessionQueryResponse, ResponseErrorConfig<Error>, GetDiagnoseSessionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getDiagnoseSession(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Read an AI-diagnose conversation snapshot (browser view)
 * {@link /api/my/diagnose-session}
 */
export function useGetDiagnoseSession<TData = GetDiagnoseSessionQueryResponse, TQueryData = GetDiagnoseSessionQueryResponse, TQueryKey extends QueryKey = GetDiagnoseSessionQueryKey>(params: GetDiagnoseSessionQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetDiagnoseSessionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getDiagnoseSessionQueryKey(params)
         

         const query = useQuery({
          ...getDiagnoseSessionQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}