/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListDiagnoseSessionsQueryResponse, ListDiagnoseSessionsQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listDiagnoseSessions } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listDiagnoseSessionsQueryKey = (params: ListDiagnoseSessionsQueryParams) => [{ url: '/api/my/diagnose-sessions' }, ...(params ? [params] : [])] as const

export type ListDiagnoseSessionsQueryKey = ReturnType<typeof listDiagnoseSessionsQueryKey>

export function listDiagnoseSessionsQueryOptions(params: ListDiagnoseSessionsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listDiagnoseSessionsQueryKey(params)
        return queryOptions<ListDiagnoseSessionsQueryResponse, ResponseErrorConfig<Error>, ListDiagnoseSessionsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listDiagnoseSessions(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List recent AI-diagnose conversations for a device
 * {@link /api/my/diagnose-sessions}
 */
export function useListDiagnoseSessions<TData = ListDiagnoseSessionsQueryResponse, TQueryData = ListDiagnoseSessionsQueryResponse, TQueryKey extends QueryKey = ListDiagnoseSessionsQueryKey>(params: ListDiagnoseSessionsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListDiagnoseSessionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listDiagnoseSessionsQueryKey(params)
         

         const query = useQuery({
          ...listDiagnoseSessionsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}