/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RevokeDiagnoseCapabilityGrantMutationRequest, RevokeDiagnoseCapabilityGrantMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { revokeDiagnoseCapabilityGrant } from "../../clients.ts";

export const revokeDiagnoseCapabilityGrantMutationKey = () => [{ url: '/api/my/diagnose-session/capability-grant/revoke' }] as const

export type RevokeDiagnoseCapabilityGrantMutationKey = ReturnType<typeof revokeDiagnoseCapabilityGrantMutationKey>

export function revokeDiagnoseCapabilityGrantMutationOptions<TContext = unknown>(config: Partial<RequestConfig<RevokeDiagnoseCapabilityGrantMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = revokeDiagnoseCapabilityGrantMutationKey()
        return mutationOptions<RevokeDiagnoseCapabilityGrantMutationResponse, ResponseErrorConfig<Error>, {data: RevokeDiagnoseCapabilityGrantMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return revokeDiagnoseCapabilityGrant(data, config)
          },
        })

}

/**
 * @summary Revoke one owner-scoped Device Assistant capability grant
 * {@link /api/my/diagnose-session/capability-grant/revoke}
 */
export function useRevokeDiagnoseCapabilityGrant<TContext>(options:
{
  mutation?: UseMutationOptions<RevokeDiagnoseCapabilityGrantMutationResponse, ResponseErrorConfig<Error>, {data: RevokeDiagnoseCapabilityGrantMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<RevokeDiagnoseCapabilityGrantMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? revokeDiagnoseCapabilityGrantMutationKey()

          const baseOptions = revokeDiagnoseCapabilityGrantMutationOptions(config) as UseMutationOptions<RevokeDiagnoseCapabilityGrantMutationResponse, ResponseErrorConfig<Error>, {data: RevokeDiagnoseCapabilityGrantMutationRequest}, TContext>


          return useMutation<RevokeDiagnoseCapabilityGrantMutationResponse, ResponseErrorConfig<Error>, {data: RevokeDiagnoseCapabilityGrantMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<RevokeDiagnoseCapabilityGrantMutationResponse, ResponseErrorConfig<Error>, {data: RevokeDiagnoseCapabilityGrantMutationRequest}, TContext>

}
