/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CloseAiAssistantApprovalDelegationMutationRequest, CloseAiAssistantApprovalDelegationMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { closeAiAssistantApprovalDelegation } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const closeAiAssistantApprovalDelegationMutationKey = () => [{ url: '/api/my/ai-assistant-session/approval-delegation/close' }] as const

export type CloseAiAssistantApprovalDelegationMutationKey = ReturnType<typeof closeAiAssistantApprovalDelegationMutationKey>

export function closeAiAssistantApprovalDelegationMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CloseAiAssistantApprovalDelegationMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = closeAiAssistantApprovalDelegationMutationKey()
        return mutationOptions<CloseAiAssistantApprovalDelegationMutationResponse, ResponseErrorConfig<Error>, {data: CloseAiAssistantApprovalDelegationMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return closeAiAssistantApprovalDelegation(data, config)
          },
        })

}

/**
 * @summary Disable independent AI review for one owner conversation
 * {@link /api/my/ai-assistant-session/approval-delegation/close}
 */
export function useCloseAiAssistantApprovalDelegation<TContext>(options: 
{
  mutation?: UseMutationOptions<CloseAiAssistantApprovalDelegationMutationResponse, ResponseErrorConfig<Error>, {data: CloseAiAssistantApprovalDelegationMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CloseAiAssistantApprovalDelegationMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? closeAiAssistantApprovalDelegationMutationKey()

          const baseOptions = closeAiAssistantApprovalDelegationMutationOptions(config) as UseMutationOptions<CloseAiAssistantApprovalDelegationMutationResponse, ResponseErrorConfig<Error>, {data: CloseAiAssistantApprovalDelegationMutationRequest}, TContext>
          

          return useMutation<CloseAiAssistantApprovalDelegationMutationResponse, ResponseErrorConfig<Error>, {data: CloseAiAssistantApprovalDelegationMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CloseAiAssistantApprovalDelegationMutationResponse, ResponseErrorConfig<Error>, {data: CloseAiAssistantApprovalDelegationMutationRequest}, TContext>
      
}