/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CancelAiAssistantCommandMutationRequest, CancelAiAssistantCommandMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { cancelAiAssistantCommand } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const cancelAiAssistantCommandMutationKey = () => [{ url: '/api/my/ai-assistant-session/command/cancel' }] as const

export type CancelAiAssistantCommandMutationKey = ReturnType<typeof cancelAiAssistantCommandMutationKey>

export function cancelAiAssistantCommandMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CancelAiAssistantCommandMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = cancelAiAssistantCommandMutationKey()
        return mutationOptions<CancelAiAssistantCommandMutationResponse, ResponseErrorConfig<Error>, {data: CancelAiAssistantCommandMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return cancelAiAssistantCommand(data, config)
          },
        })

}

/**
 * @summary Request a durable stop for one original AI command generation
 * {@link /api/my/ai-assistant-session/command/cancel}
 */
export function useCancelAiAssistantCommand<TContext>(options: 
{
  mutation?: UseMutationOptions<CancelAiAssistantCommandMutationResponse, ResponseErrorConfig<Error>, {data: CancelAiAssistantCommandMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CancelAiAssistantCommandMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? cancelAiAssistantCommandMutationKey()

          const baseOptions = cancelAiAssistantCommandMutationOptions(config) as UseMutationOptions<CancelAiAssistantCommandMutationResponse, ResponseErrorConfig<Error>, {data: CancelAiAssistantCommandMutationRequest}, TContext>
          

          return useMutation<CancelAiAssistantCommandMutationResponse, ResponseErrorConfig<Error>, {data: CancelAiAssistantCommandMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CancelAiAssistantCommandMutationResponse, ResponseErrorConfig<Error>, {data: CancelAiAssistantCommandMutationRequest}, TContext>
      
}