/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { ControlAiAssistantGoalMutationRequest, ControlAiAssistantGoalMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { controlAiAssistantGoal } from "../../clients.ts";

export const controlAiAssistantGoalMutationKey = () => [{ url: '/api/my/ai-assistant-session/goal/control' }] as const

export type ControlAiAssistantGoalMutationKey = ReturnType<typeof controlAiAssistantGoalMutationKey>

export function controlAiAssistantGoalMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ControlAiAssistantGoalMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = controlAiAssistantGoalMutationKey()
        return mutationOptions<ControlAiAssistantGoalMutationResponse, ResponseErrorConfig<Error>, {data: ControlAiAssistantGoalMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return controlAiAssistantGoal(data, config)
          },
        })

}

/**
 * @summary Pause, resume or cancel one owner-approved AI Assistant goal
 * {@link /api/my/ai-assistant-session/goal/control}
 */
export function useControlAiAssistantGoal<TContext>(options: 
{
  mutation?: UseMutationOptions<ControlAiAssistantGoalMutationResponse, ResponseErrorConfig<Error>, {data: ControlAiAssistantGoalMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ControlAiAssistantGoalMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? controlAiAssistantGoalMutationKey()

          const baseOptions = controlAiAssistantGoalMutationOptions(config) as UseMutationOptions<ControlAiAssistantGoalMutationResponse, ResponseErrorConfig<Error>, {data: ControlAiAssistantGoalMutationRequest}, TContext>
          

          return useMutation<ControlAiAssistantGoalMutationResponse, ResponseErrorConfig<Error>, {data: ControlAiAssistantGoalMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ControlAiAssistantGoalMutationResponse, ResponseErrorConfig<Error>, {data: ControlAiAssistantGoalMutationRequest}, TContext>
      
}