/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DecideAiAssistantGoalOpenMutationRequest, DecideAiAssistantGoalOpenMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { decideAiAssistantGoalOpen } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const decideAiAssistantGoalOpenMutationKey = () => [{ url: '/api/my/ai-assistant-session/goal/open-decision' }] as const

export type DecideAiAssistantGoalOpenMutationKey = ReturnType<typeof decideAiAssistantGoalOpenMutationKey>

export function decideAiAssistantGoalOpenMutationOptions<TContext = unknown>(config: Partial<RequestConfig<DecideAiAssistantGoalOpenMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = decideAiAssistantGoalOpenMutationKey()
        return mutationOptions<DecideAiAssistantGoalOpenMutationResponse, ResponseErrorConfig<Error>, {data: DecideAiAssistantGoalOpenMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return decideAiAssistantGoalOpen(data, config)
          },
        })

}

/**
 * @summary Approve or deny an AI-proposed AI Assistant goal
 * {@link /api/my/ai-assistant-session/goal/open-decision}
 */
export function useDecideAiAssistantGoalOpen<TContext>(options: 
{
  mutation?: UseMutationOptions<DecideAiAssistantGoalOpenMutationResponse, ResponseErrorConfig<Error>, {data: DecideAiAssistantGoalOpenMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<DecideAiAssistantGoalOpenMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? decideAiAssistantGoalOpenMutationKey()

          const baseOptions = decideAiAssistantGoalOpenMutationOptions(config) as UseMutationOptions<DecideAiAssistantGoalOpenMutationResponse, ResponseErrorConfig<Error>, {data: DecideAiAssistantGoalOpenMutationRequest}, TContext>
          

          return useMutation<DecideAiAssistantGoalOpenMutationResponse, ResponseErrorConfig<Error>, {data: DecideAiAssistantGoalOpenMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DecideAiAssistantGoalOpenMutationResponse, ResponseErrorConfig<Error>, {data: DecideAiAssistantGoalOpenMutationRequest}, TContext>
      
}