/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeleteAssistantAttachmentsMutationRequest, DeleteAssistantAttachmentsMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteAssistantAttachments } from "../../clients.ts";

export const deleteAssistantAttachmentsMutationKey = () => [{ url: '/api/my/ai-assistant-session/attachments/delete' }] as const

export type DeleteAssistantAttachmentsMutationKey = ReturnType<typeof deleteAssistantAttachmentsMutationKey>

export function deleteAssistantAttachmentsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<DeleteAssistantAttachmentsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = deleteAssistantAttachmentsMutationKey()
        return mutationOptions<DeleteAssistantAttachmentsMutationResponse, ResponseErrorConfig<Error>, {data: DeleteAssistantAttachmentsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return deleteAssistantAttachments(data, config)
          },
        })

}

/**
 * {@link /api/my/ai-assistant-session/attachments/delete}
 */
export function useDeleteAssistantAttachments<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteAssistantAttachmentsMutationResponse, ResponseErrorConfig<Error>, {data: DeleteAssistantAttachmentsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<DeleteAssistantAttachmentsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteAssistantAttachmentsMutationKey()

          const baseOptions = deleteAssistantAttachmentsMutationOptions(config) as UseMutationOptions<DeleteAssistantAttachmentsMutationResponse, ResponseErrorConfig<Error>, {data: DeleteAssistantAttachmentsMutationRequest}, TContext>
          

          return useMutation<DeleteAssistantAttachmentsMutationResponse, ResponseErrorConfig<Error>, {data: DeleteAssistantAttachmentsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteAssistantAttachmentsMutationResponse, ResponseErrorConfig<Error>, {data: DeleteAssistantAttachmentsMutationRequest}, TContext>
      
}