/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetAssistantAttachmentQueryResponse, GetAssistantAttachmentQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getAssistantAttachment } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAssistantAttachmentSuspenseQueryKey = (params: GetAssistantAttachmentQueryParams) => [{ url: '/api/my/ai-assistant-session/attachment' }, ...(params ? [params] : [])] as const

export type GetAssistantAttachmentSuspenseQueryKey = ReturnType<typeof getAssistantAttachmentSuspenseQueryKey>

export function getAssistantAttachmentSuspenseQueryOptions(params: GetAssistantAttachmentQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getAssistantAttachmentSuspenseQueryKey(params)
        return queryOptions<GetAssistantAttachmentQueryResponse, ResponseErrorConfig<Error>, GetAssistantAttachmentQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getAssistantAttachment(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/ai-assistant-session/attachment}
 */
export function useGetAssistantAttachmentSuspense<TData = GetAssistantAttachmentQueryResponse, TQueryKey extends QueryKey = GetAssistantAttachmentSuspenseQueryKey>(params: GetAssistantAttachmentQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetAssistantAttachmentQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getAssistantAttachmentSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getAssistantAttachmentSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}