/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetAiAssistantSubagentStatusQueryResponse, GetAiAssistantSubagentStatusQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getAiAssistantSubagentStatus } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAiAssistantSubagentStatusQueryKey = (params: GetAiAssistantSubagentStatusQueryParams) => [{ url: '/api/my/ai-assistant-session/subagents/status' }, ...(params ? [params] : [])] as const

export type GetAiAssistantSubagentStatusQueryKey = ReturnType<typeof getAiAssistantSubagentStatusQueryKey>

export function getAiAssistantSubagentStatusQueryOptions(params: GetAiAssistantSubagentStatusQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getAiAssistantSubagentStatusQueryKey(params)
        return queryOptions<GetAiAssistantSubagentStatusQueryResponse, ResponseErrorConfig<Error>, GetAiAssistantSubagentStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getAiAssistantSubagentStatus(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Read the authoritative status of one subagent
 * {@link /api/my/ai-assistant-session/subagents/status}
 */
export function useGetAiAssistantSubagentStatus<TData = GetAiAssistantSubagentStatusQueryResponse, TQueryData = GetAiAssistantSubagentStatusQueryResponse, TQueryKey extends QueryKey = GetAiAssistantSubagentStatusQueryKey>(params: GetAiAssistantSubagentStatusQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetAiAssistantSubagentStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getAiAssistantSubagentStatusQueryKey(params)
         

         const query = useQuery({
          ...getAiAssistantSubagentStatusQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}