/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListAiAssistantSubagentsQueryResponse, ListAiAssistantSubagentsQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listAiAssistantSubagents } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listAiAssistantSubagentsQueryKey = (params: ListAiAssistantSubagentsQueryParams) => [{ url: '/api/my/ai-assistant-session/subagents' }, ...(params ? [params] : [])] as const

export type ListAiAssistantSubagentsQueryKey = ReturnType<typeof listAiAssistantSubagentsQueryKey>

export function listAiAssistantSubagentsQueryOptions(params: ListAiAssistantSubagentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listAiAssistantSubagentsQueryKey(params)
        return queryOptions<ListAiAssistantSubagentsQueryResponse, ResponseErrorConfig<Error>, ListAiAssistantSubagentsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listAiAssistantSubagents(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List a bounded page of this conversation's subagents
 * {@link /api/my/ai-assistant-session/subagents}
 */
export function useListAiAssistantSubagents<TData = ListAiAssistantSubagentsQueryResponse, TQueryData = ListAiAssistantSubagentsQueryResponse, TQueryKey extends QueryKey = ListAiAssistantSubagentsQueryKey>(params: ListAiAssistantSubagentsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListAiAssistantSubagentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listAiAssistantSubagentsQueryKey(params)
         

         const query = useQuery({
          ...listAiAssistantSubagentsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}