/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListAssistantAttachmentsQueryResponse, ListAssistantAttachmentsQueryParams } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { listAssistantAttachments } from "../../clients.ts";

export const listAssistantAttachmentsQueryKey = (params: ListAssistantAttachmentsQueryParams) => [{ url: '/api/my/ai-assistant-session/attachments' }, ...(params ? [params] : [])] as const

export type ListAssistantAttachmentsQueryKey = ReturnType<typeof listAssistantAttachmentsQueryKey>

export function listAssistantAttachmentsQueryOptions(params: ListAssistantAttachmentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listAssistantAttachmentsQueryKey(params)
        return queryOptions<ListAssistantAttachmentsQueryResponse, ResponseErrorConfig<Error>, ListAssistantAttachmentsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listAssistantAttachments(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/my/ai-assistant-session/attachments}
 */
export function useListAssistantAttachments<TData = ListAssistantAttachmentsQueryResponse, TQueryData = ListAssistantAttachmentsQueryResponse, TQueryKey extends QueryKey = ListAssistantAttachmentsQueryKey>(params: ListAssistantAttachmentsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListAssistantAttachmentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listAssistantAttachmentsQueryKey(params)
         

         const query = useQuery({
          ...listAssistantAttachmentsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}