/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ListAiAssistantAttentionQueryResponse, ListAiAssistantAttentionQueryParams } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { listAiAssistantAttention } from "../../clients.ts";

export const listAiAssistantAttentionSuspenseQueryKey = (params?: ListAiAssistantAttentionQueryParams) => [{ url: '/api/my/ai-assistant-attention' }, ...(params ? [params] : [])] as const

export type ListAiAssistantAttentionSuspenseQueryKey = ReturnType<typeof listAiAssistantAttentionSuspenseQueryKey>

export function listAiAssistantAttentionSuspenseQueryOptions(params?: ListAiAssistantAttentionQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listAiAssistantAttentionSuspenseQueryKey(params)
        return queryOptions<ListAiAssistantAttentionQueryResponse, ResponseErrorConfig<Error>, ListAiAssistantAttentionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listAiAssistantAttention(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List durable AI Assistant actions requiring the account owner's attention
 * {@link /api/my/ai-assistant-attention}
 */
export function useListAiAssistantAttentionSuspense<TData = ListAiAssistantAttentionQueryResponse, TQueryKey extends QueryKey = ListAiAssistantAttentionSuspenseQueryKey>(params?: ListAiAssistantAttentionQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListAiAssistantAttentionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listAiAssistantAttentionSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...listAiAssistantAttentionSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}