/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListAiAssistantAttentionQueryResponse, ListAiAssistantAttentionQueryParams } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { listAiAssistantAttention } from "../../clients.ts";

export const listAiAssistantAttentionQueryKey = (params?: ListAiAssistantAttentionQueryParams) => [{ url: '/api/my/ai-assistant-attention' }, ...(params ? [params] : [])] as const

export type ListAiAssistantAttentionQueryKey = ReturnType<typeof listAiAssistantAttentionQueryKey>

export function listAiAssistantAttentionQueryOptions(params?: ListAiAssistantAttentionQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listAiAssistantAttentionQueryKey(params)
        return queryOptions<ListAiAssistantAttentionQueryResponse, ResponseErrorConfig<Error>, ListAiAssistantAttentionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listAiAssistantAttention(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List durable AI Assistant actions requiring the account owner's attention
 * {@link /api/my/ai-assistant-attention}
 */
export function useListAiAssistantAttention<TData = ListAiAssistantAttentionQueryResponse, TQueryData = ListAiAssistantAttentionQueryResponse, TQueryKey extends QueryKey = ListAiAssistantAttentionQueryKey>(params?: ListAiAssistantAttentionQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListAiAssistantAttentionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listAiAssistantAttentionQueryKey(params)
         

         const query = useQuery({
          ...listAiAssistantAttentionQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}