/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StopAiAssistantSessionMutationRequest, StopAiAssistantSessionMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { stopAiAssistantSession } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const stopAiAssistantSessionMutationKey = () => [{ url: '/api/my/ai-assistant-session/stop' }] as const

export type StopAiAssistantSessionMutationKey = ReturnType<typeof stopAiAssistantSessionMutationKey>

export function stopAiAssistantSessionMutationOptions<TContext = unknown>(config: Partial<RequestConfig<StopAiAssistantSessionMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = stopAiAssistantSessionMutationKey()
        return mutationOptions<StopAiAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: StopAiAssistantSessionMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return stopAiAssistantSession(data, config)
          },
        })

}

/**
 * @summary Stop main generation and optionally all unfinished subagents
 * {@link /api/my/ai-assistant-session/stop}
 */
export function useStopAiAssistantSession<TContext>(options: 
{
  mutation?: UseMutationOptions<StopAiAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: StopAiAssistantSessionMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<StopAiAssistantSessionMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? stopAiAssistantSessionMutationKey()

          const baseOptions = stopAiAssistantSessionMutationOptions(config) as UseMutationOptions<StopAiAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: StopAiAssistantSessionMutationRequest}, TContext>
          

          return useMutation<StopAiAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: StopAiAssistantSessionMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<StopAiAssistantSessionMutationResponse, ResponseErrorConfig<Error>, {data: StopAiAssistantSessionMutationRequest}, TContext>
      
}