[package]
name = "desk-ipc-protocol"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
desk-signal-facade = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
wincode = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
