/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelProviderQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getModelProvider } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getModelProviderQueryKey = () => [{ url: '/api/model/provider' }] as const

export type GetModelProviderQueryKey = ReturnType<typeof getModelProviderQueryKey>

export function getModelProviderQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelProviderQueryKey()
        return queryOptions<GetModelProviderQueryResponse, ResponseErrorConfig<Error>, GetModelProviderQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelProvider({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the masked model-provider configuration
 * {@link /api/model/provider}
 */
export function useGetModelProvider<TData = GetModelProviderQueryResponse, TQueryData = GetModelProviderQueryResponse, TQueryKey extends QueryKey = GetModelProviderQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetModelProviderQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelProviderQueryKey()
         

         const query = useQuery({
          ...getModelProviderQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}