/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelProviderQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getModelProvider } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getModelProviderSuspenseQueryKey = () => [{ url: '/api/model/provider' }] as const

export type GetModelProviderSuspenseQueryKey = ReturnType<typeof getModelProviderSuspenseQueryKey>

export function getModelProviderSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelProviderSuspenseQueryKey()
        return queryOptions<GetModelProviderQueryResponse, ResponseErrorConfig<Error>, GetModelProviderQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelProvider({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the masked model-provider configuration
 * {@link /api/model/provider}
 */
export function useGetModelProviderSuspense<TData = GetModelProviderQueryResponse, TQueryKey extends QueryKey = GetModelProviderSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetModelProviderQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelProviderSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getModelProviderSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}