/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { TestModelProviderMutationRequest, TestModelProviderMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { testModelProvider } from "../../clients.ts";

export const testModelProviderMutationKey = () => [{ url: '/api/model/provider/test' }] as const

export type TestModelProviderMutationKey = ReturnType<typeof testModelProviderMutationKey>

export function testModelProviderMutationOptions<TContext = unknown>(config: Partial<RequestConfig<TestModelProviderMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = testModelProviderMutationKey()
        return mutationOptions<TestModelProviderMutationResponse, ResponseErrorConfig<Error>, {data: TestModelProviderMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return testModelProvider(data, config)
          },
        })

}

/**
 * @summary Test the model-provider AI call chain
 * {@link /api/model/provider/test}
 */
export function useTestModelProvider<TContext>(options: 
{
  mutation?: UseMutationOptions<TestModelProviderMutationResponse, ResponseErrorConfig<Error>, {data: TestModelProviderMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TestModelProviderMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? testModelProviderMutationKey()

          const baseOptions = testModelProviderMutationOptions(config) as UseMutationOptions<TestModelProviderMutationResponse, ResponseErrorConfig<Error>, {data: TestModelProviderMutationRequest}, TContext>
          

          return useMutation<TestModelProviderMutationResponse, ResponseErrorConfig<Error>, {data: TestModelProviderMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<TestModelProviderMutationResponse, ResponseErrorConfig<Error>, {data: TestModelProviderMutationRequest}, TContext>
      
}