/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QueryDriverStatusQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryDriverStatus } from "../../clients.ts";

export const queryDriverStatusQueryKey = () => [{ url: '/api/virtual-display/driver/status' }] as const

export type QueryDriverStatusQueryKey = ReturnType<typeof queryDriverStatusQueryKey>

export function queryDriverStatusQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryDriverStatusQueryKey()
        return queryOptions<QueryDriverStatusQueryResponse, ResponseErrorConfig<Error>, QueryDriverStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return queryDriverStatus(config)
         },
        })

}

/**
 * @summary Query LcxlVirtualDisplay IDD driver status
 * {@link /api/virtual-display/driver/status}
 */
export function useQueryDriverStatus<TData = QueryDriverStatusQueryResponse, TQueryData = QueryDriverStatusQueryResponse, TQueryKey extends QueryKey = QueryDriverStatusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryDriverStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? queryDriverStatusQueryKey()
         

         const query = useQuery({
          ...queryDriverStatusQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}