/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QueryDriverStatusQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { queryDriverStatus } from "../../clients.ts";

export const queryDriverStatusSuspenseQueryKey = () => [{ url: '/api/virtual-display/driver/status' }] as const

export type QueryDriverStatusSuspenseQueryKey = ReturnType<typeof queryDriverStatusSuspenseQueryKey>

export function queryDriverStatusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryDriverStatusSuspenseQueryKey()
        return queryOptions<QueryDriverStatusQueryResponse, ResponseErrorConfig<Error>, QueryDriverStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return queryDriverStatus(config)
         },
        })

}

/**
 * @summary Query LcxlVirtualDisplay IDD driver status
 * {@link /api/virtual-display/driver/status}
 */
export function useQueryDriverStatusSuspense<TData = QueryDriverStatusQueryResponse, TQueryKey extends QueryKey = QueryDriverStatusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryDriverStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? queryDriverStatusSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryDriverStatusSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}