/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryVirtualDisplaySettingsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryVirtualDisplaySettings } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const queryVirtualDisplaySettingsQueryKey = () => [{ url: '/api/desk/settings/virtual-display' }] as const

export type QueryVirtualDisplaySettingsQueryKey = ReturnType<typeof queryVirtualDisplaySettingsQueryKey>

export function queryVirtualDisplaySettingsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryVirtualDisplaySettingsQueryKey()
        return queryOptions<QueryVirtualDisplaySettingsQueryResponse, ResponseErrorConfig<Error>, QueryVirtualDisplaySettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryVirtualDisplaySettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get virtual display settings
 * {@link /api/desk/settings/virtual-display}
 */
export function useQueryVirtualDisplaySettings<TData = QueryVirtualDisplaySettingsQueryResponse, TQueryData = QueryVirtualDisplaySettingsQueryResponse, TQueryKey extends QueryKey = QueryVirtualDisplaySettingsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryVirtualDisplaySettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryVirtualDisplaySettingsQueryKey()
         

         const query = useQuery({
          ...queryVirtualDisplaySettingsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}