/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateVirtualDisplaySettingsMutationRequest, UpdateVirtualDisplaySettingsMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateVirtualDisplaySettings } from "../../clients.ts";

export const updateVirtualDisplaySettingsMutationKey = () => [{ url: '/api/desk/settings/virtual-display' }] as const

export type UpdateVirtualDisplaySettingsMutationKey = ReturnType<typeof updateVirtualDisplaySettingsMutationKey>

export function updateVirtualDisplaySettingsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateVirtualDisplaySettingsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateVirtualDisplaySettingsMutationKey()
        return mutationOptions<UpdateVirtualDisplaySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateVirtualDisplaySettingsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateVirtualDisplaySettings(data, config)
          },
        })

}

/**
 * @summary Update virtual display settings
 * {@link /api/desk/settings/virtual-display}
 */
export function useUpdateVirtualDisplaySettings<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateVirtualDisplaySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateVirtualDisplaySettingsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateVirtualDisplaySettingsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateVirtualDisplaySettingsMutationKey()

          const baseOptions = updateVirtualDisplaySettingsMutationOptions(config) as UseMutationOptions<UpdateVirtualDisplaySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateVirtualDisplaySettingsMutationRequest}, TContext>
          

          return useMutation<UpdateVirtualDisplaySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateVirtualDisplaySettingsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateVirtualDisplaySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateVirtualDisplaySettingsMutationRequest}, TContext>
      
}