
export const SIGNALING_TYPE_CODE_HEARTBEAT = 1;

export const SIGNALING_TYPE_CODE_FETCH_SESSIONS = 21;
export const SIGNALING_TYPE_CODE_SESSION_LIST = 22;

export const SIGNALING_TYPE_CODE_REQUEST_REMOTE = 100;
export const SIGNALING_TYPE_CODE_INIT = 101;
export const SIGNALING_TYPE_CODE_OFFER = 102;
export const SIGNALING_TYPE_CODE_ANSWER = 103;
export const SIGNALING_TYPE_CODE_CANID = 104;

export const SIGNALING_TYPE_CODE_REQUIRE_CONTROL = 201;
export const SIGNALING_TYPE_CODE_ACCEPT_CONTROL = 202;
export const SIGNALING_TYPE_CODE_DENY_CONTROL = 203;
export const SIGNALING_TYPE_CODE_CLOSE_CONTROL = 204;

export const SIGNALING_TYPE_CODE_UPDATE_DESK_SETTINGS = 301;

export const SIGNALING_TYPE_CODE_ENABLE_PRIVATE_SCREEN = 206;
export const SIGNALING_TYPE_CODE_PRIVATE_SCREEN_STATE_CHANGED = 207;

export const SIGNALING_TYPE_CODE_ERROR = 10000000;
export const SIGNALING_TYPE_CODE_UNKNOWN_TYPE = 10000001;
