export const SIGNALING_API_VERSION = 1;

export const SIGNALING_TYPE_CODE_SEND_HEARTBEAT = 1;
export const SIGNALING_TYPE_CODE_HEARTBEAT_ACKNOWLEDGED = 2;

export const SIGNALING_TYPE_CODE_FETCH_CONNECTIONS = 21;
export const SIGNALING_TYPE_CODE_CONNECTIONS_FETCHED = 22;

export const SIGNALING_TYPE_CODE_REQUEST_REMOTE_ACCESS = 100;
export const SIGNALING_TYPE_CODE_REMOTE_ACCESS_INITIALIZED = 101;
export const SIGNALING_TYPE_CODE_OFFER = 102;
export const SIGNALING_TYPE_CODE_ANSWER = 103;
export const SIGNALING_TYPE_CODE_ICE_CANDIDATE = 104;

export const SIGNALING_TYPE_CODE_REQUIRE_CONTROL = 201;
export const SIGNALING_TYPE_CODE_CONTROL_ACCEPTED = 202;
export const SIGNALING_TYPE_CODE_CONTROL_DENIED = 203;
export const SIGNALING_TYPE_CODE_RELEASE_CONTROL = 204;
export const SIGNALING_TYPE_CODE_CHANGE_DISPLAY_SETTINGS = 205;
export const SIGNALING_TYPE_CODE_SET_PRIVATE_SCREEN_VISIBILITY = 206;
export const SIGNALING_TYPE_CODE_PRIVATE_SCREEN_STATE_CHANGED = 207;
export const SIGNALING_TYPE_CODE_AUDIO_PLAYBACK_FAILED = 208;
export const SIGNALING_TYPE_CODE_MEDIA_PIPELINE_STATE_CHANGED = 217;
export const SIGNALING_TYPE_CODE_RETRY_MEDIA_PIPELINE = 218;
export const SIGNALING_TYPE_CODE_CONTROL_RELEASED = 219;
export const SIGNALING_TYPE_CODE_DISPLAY_SETTINGS_CHANGED = 220;
export const SIGNALING_TYPE_CODE_CLOSE_REMOTE_SESSION = 221;
export const SIGNALING_TYPE_CODE_PRIVATE_SCREEN_VISIBILITY_SET = 222;
export const SIGNALING_TYPE_CODE_MEDIA_PIPELINE_RETRY_COMPLETED = 223;

export const SIGNALING_TYPE_CODE_APPLY_REMOTE_SESSION_SETTINGS = 301;
export const SIGNALING_TYPE_CODE_REMOTE_SESSION_SETTINGS_APPLIED = 302;
export const SIGNALING_TYPE_CODE_UPDATE_ADAPTIVE_VIDEO_QUALITY = 303;
export const SIGNALING_TYPE_CODE_SYSTEM_AUDIO_CAPTURE_STATE_CHANGED = 304;
export const SIGNALING_TYPE_CODE_DESKTOP_SWITCHING = 500;
export const SIGNALING_TYPE_CODE_DESKTOP_READY = 501;

export const SIGNALING_TYPE_CODE_INVOKE_AGENT_CAPABILITY = 600;
export const SIGNALING_TYPE_CODE_AGENT_CAPABILITY_COMPLETED = 601;
export const SIGNALING_TYPE_CODE_DIAGNOSE_DEVICE = 602;
export const SIGNALING_TYPE_CODE_DIAGNOSIS_UPDATED = 603;
export const SIGNALING_TYPE_CODE_CANCEL_DIAGNOSIS = 604;
export const SIGNALING_TYPE_CODE_PREVIEW_EXECUTION = 605;
export const SIGNALING_TYPE_CODE_EXECUTION_PREVIEW_GENERATED = 606;
export const SIGNALING_TYPE_CODE_RESOLVE_EXECUTION = 607;
export const SIGNALING_TYPE_CODE_EXECUTION_COMPLETED = 609;
export const SIGNALING_TYPE_CODE_ASK_TERMINAL_COPILOT = 617;
export const SIGNALING_TYPE_CODE_TERMINAL_COPILOT_UPDATED = 618;
export const SIGNALING_TYPE_CODE_CANCEL_TERMINAL_COPILOT = 619;
export const SIGNALING_TYPE_CODE_GENERATE_TERMINAL_COMPLETIONS = 620;
export const SIGNALING_TYPE_CODE_TERMINAL_COMPLETIONS_GENERATED = 621;
export const SIGNALING_TYPE_CODE_CONTROL_EXECUTION = 623;
export const SIGNALING_TYPE_CODE_EXECUTION_STATE_REPORTED = 624;
export const SIGNALING_TYPE_CODE_EXECUTION_PROGRESS_UPDATED = 625;
export const SIGNALING_TYPE_CODE_DISPATCH_COMPUTER_ACTION = 626;
export const SIGNALING_TYPE_CODE_CANCEL_COMPUTER_ACTION = 627;
export const SIGNALING_TYPE_CODE_QUERY_COMPUTER_ACTION_STATE = 628;
export const SIGNALING_TYPE_CODE_COMPUTER_ACTION_STARTED = 629;
export const SIGNALING_TYPE_CODE_COMPUTER_ACTION_COMPLETED = 630;
export const SIGNALING_TYPE_CODE_COMPUTER_ACTION_STATE_REPORTED = 631;
export const SIGNALING_TYPE_CODE_COMPUTER_USE_READINESS_UPDATED = 632;
export const SIGNALING_TYPE_CODE_ASK_DEVICE_ASSISTANT = 633;
export const SIGNALING_TYPE_CODE_DEVICE_ASSISTANT_UPDATED = 634;
export const SIGNALING_TYPE_CODE_CANCEL_DEVICE_ASSISTANT = 635;
export const SIGNALING_TYPE_CODE_GET_DEVICE_ASSISTANT_CAPABILITIES = 636;
export const SIGNALING_TYPE_CODE_DEVICE_ASSISTANT_CAPABILITIES_UPDATED = 637;
export const SIGNALING_TYPE_CODE_UPDATE_DEVICE_ASSISTANT_CONTEXT = 638;
export const SIGNALING_TYPE_CODE_DEVICE_ASSISTANT_CONTEXT_UPDATED = 639;
export const SIGNALING_TYPE_CODE_UPDATE_DEVICE_ASSISTANT_OBJECT_CONTEXT = 640;
export const SIGNALING_TYPE_CODE_DEVICE_ASSISTANT_OBJECT_CONTEXT_UPDATED = 641;

export const SIGNALING_TYPE_CODE_GET_SYSTEM_INFO = 10003;
export const SIGNALING_TYPE_CODE_SYSTEM_INFO_RETRIEVED = 10004;
export const SIGNALING_TYPE_CODE_LIST_FILES = 10005;
export const SIGNALING_TYPE_CODE_DELETE_FILE = 10006;
export const SIGNALING_TYPE_CODE_FILES_LISTED = 10015;
export const SIGNALING_TYPE_CODE_FILE_DELETED = 10016;

export const SIGNALING_TYPE_CODE_ERROR = -1;
export const SIGNALING_TYPE_CODE_UNKNOWN = -100;
