/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateBrowserExtensionPairingMutationRequest, CreateBrowserExtensionPairingMutationResponse, CreateBrowserExtensionPairing500 } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createBrowserExtensionPairing } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createBrowserExtensionPairingMutationKey = () => [{ url: '/api/desk/browser-extension/pairing' }] as const

export type CreateBrowserExtensionPairingMutationKey = ReturnType<typeof createBrowserExtensionPairingMutationKey>

export function createBrowserExtensionPairingMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreateBrowserExtensionPairingMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createBrowserExtensionPairingMutationKey()
        return mutationOptions<CreateBrowserExtensionPairingMutationResponse, ResponseErrorConfig<CreateBrowserExtensionPairing500>, {data: CreateBrowserExtensionPairingMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return createBrowserExtensionPairing(data, config)
          },
        })

}

/**
 * @summary Redeem a local OS-user proof for Chrome extension pairing
 * {@link /api/desk/browser-extension/pairing}
 */
export function useCreateBrowserExtensionPairing<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateBrowserExtensionPairingMutationResponse, ResponseErrorConfig<CreateBrowserExtensionPairing500>, {data: CreateBrowserExtensionPairingMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateBrowserExtensionPairingMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createBrowserExtensionPairingMutationKey()

          const baseOptions = createBrowserExtensionPairingMutationOptions(config) as UseMutationOptions<CreateBrowserExtensionPairingMutationResponse, ResponseErrorConfig<CreateBrowserExtensionPairing500>, {data: CreateBrowserExtensionPairingMutationRequest}, TContext>
          

          return useMutation<CreateBrowserExtensionPairingMutationResponse, ResponseErrorConfig<CreateBrowserExtensionPairing500>, {data: CreateBrowserExtensionPairingMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreateBrowserExtensionPairingMutationResponse, ResponseErrorConfig<CreateBrowserExtensionPairing500>, {data: CreateBrowserExtensionPairingMutationRequest}, TContext>
      
}