/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTurnMetricsQueryResponse, GetTurnMetrics503 } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getTurnMetrics } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getTurnMetricsSuspenseQueryKey = () => [{ url: '/api/turn/metrics' }] as const

export type GetTurnMetricsSuspenseQueryKey = ReturnType<typeof getTurnMetricsSuspenseQueryKey>

export function getTurnMetricsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTurnMetricsSuspenseQueryKey()
        return queryOptions<GetTurnMetricsQueryResponse, ResponseErrorConfig<GetTurnMetrics503>, GetTurnMetricsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getTurnMetrics({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Turn server metrics
 * {@link /api/turn/metrics}
 */
export function useGetTurnMetricsSuspense<TData = GetTurnMetricsQueryResponse, TQueryKey extends QueryKey = GetTurnMetricsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetTurnMetricsQueryResponse, ResponseErrorConfig<GetTurnMetrics503>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getTurnMetricsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getTurnMetricsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetTurnMetrics503>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}