/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetTurnMetricsQueryResponse, GetTurnMetrics503 } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getTurnMetrics } from "../../clients.ts";

export const getTurnMetricsQueryKey = () => [{ url: '/api/turn/metrics' }] as const

export type GetTurnMetricsQueryKey = ReturnType<typeof getTurnMetricsQueryKey>

export function getTurnMetricsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTurnMetricsQueryKey()
        return queryOptions<GetTurnMetricsQueryResponse, ResponseErrorConfig<GetTurnMetrics503>, GetTurnMetricsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getTurnMetrics({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Turn server metrics
 * {@link /api/turn/metrics}
 */
export function useGetTurnMetrics<TData = GetTurnMetricsQueryResponse, TQueryData = GetTurnMetricsQueryResponse, TQueryKey extends QueryKey = GetTurnMetricsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetTurnMetricsQueryResponse, ResponseErrorConfig<GetTurnMetrics503>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getTurnMetricsQueryKey()
         

         const query = useQuery({
          ...getTurnMetricsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetTurnMetrics503>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}