/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { QueryTurnSettingsQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryTurnSettings } from "../../clients.ts";

export const queryTurnSettingsQueryKey = () =>
  [{ url: "/api/desk/settings/turn" }] as const;

export type QueryTurnSettingsQueryKey = ReturnType<
  typeof queryTurnSettingsQueryKey
>;

export function queryTurnSettingsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = queryTurnSettingsQueryKey();
  return queryOptions<
    QueryTurnSettingsQueryResponse,
    ResponseErrorConfig<Error>,
    QueryTurnSettingsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return queryTurnSettings({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Query turn settings
 * {@link /api/desk/settings/turn}
 */
export function useQueryTurnSettings<
  TData = QueryTurnSettingsQueryResponse,
  TQueryData = QueryTurnSettingsQueryResponse,
  TQueryKey extends QueryKey = QueryTurnSettingsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        QueryTurnSettingsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? queryTurnSettingsQueryKey();

  const query = useQuery(
    {
      ...queryTurnSettingsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
