/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type { RegenerateTurnSecretMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { regenerateTurnSecret } from "../../clients.ts";

export const regenerateTurnSecretMutationKey = () =>
  [{ url: "/api/desk/settings/turn/regenerate-secret" }] as const;

export type RegenerateTurnSecretMutationKey = ReturnType<
  typeof regenerateTurnSecretMutationKey
>;

export function regenerateTurnSecretMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = regenerateTurnSecretMutationKey();
  return mutationOptions<
    RegenerateTurnSecretMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return regenerateTurnSecret(config);
    },
  });
}

/**
 * @summary Regenerate TURN static_auth_secret
 * {@link /api/desk/settings/turn/regenerate-secret}
 */
export function useRegenerateTurnSecret<TContext>(
  options: {
    mutation?: UseMutationOptions<
      RegenerateTurnSecretMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? regenerateTurnSecretMutationKey();

  const baseOptions = regenerateTurnSecretMutationOptions(
    config,
  ) as UseMutationOptions<
    RegenerateTurnSecretMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    RegenerateTurnSecretMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    RegenerateTurnSecretMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
