/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateTurnSettingsMutationRequest, UpdateTurnSettingsMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateTurnSettings } from "../../clients.ts";

export const updateTurnSettingsMutationKey = () => [{ url: '/api/desk/settings/turn' }] as const

export type UpdateTurnSettingsMutationKey = ReturnType<typeof updateTurnSettingsMutationKey>

export function updateTurnSettingsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateTurnSettingsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateTurnSettingsMutationKey()
        return mutationOptions<UpdateTurnSettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateTurnSettingsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateTurnSettings(data, config)
          },
        })

}

/**
 * @summary Update turn settings
 * {@link /api/desk/settings/turn}
 */
export function useUpdateTurnSettings<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateTurnSettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateTurnSettingsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateTurnSettingsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateTurnSettingsMutationKey()

          const baseOptions = updateTurnSettingsMutationOptions(config) as UseMutationOptions<UpdateTurnSettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateTurnSettingsMutationRequest}, TContext>
          

          return useMutation<UpdateTurnSettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateTurnSettingsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateTurnSettingsMutationResponse, ResponseErrorConfig<Error>, {data?: UpdateTurnSettingsMutationRequest}, TContext>
      
}