/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryCollectionPolicySettingsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryCollectionPolicySettings } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const queryCollectionPolicySettingsQueryKey = () => [{ url: '/api/desk/settings/collection-policy' }] as const

export type QueryCollectionPolicySettingsQueryKey = ReturnType<typeof queryCollectionPolicySettingsQueryKey>

export function queryCollectionPolicySettingsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryCollectionPolicySettingsQueryKey()
        return queryOptions<QueryCollectionPolicySettingsQueryResponse, ResponseErrorConfig<Error>, QueryCollectionPolicySettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryCollectionPolicySettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the edge collection policy
 * {@link /api/desk/settings/collection-policy}
 */
export function useQueryCollectionPolicySettings<TData = QueryCollectionPolicySettingsQueryResponse, TQueryData = QueryCollectionPolicySettingsQueryResponse, TQueryKey extends QueryKey = QueryCollectionPolicySettingsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryCollectionPolicySettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryCollectionPolicySettingsQueryKey()
         

         const query = useQuery({
          ...queryCollectionPolicySettingsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}