/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryAiAssistantSettingsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryAiAssistantSettings } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const queryAiAssistantSettingsSuspenseQueryKey = () => [{ url: '/api/desk/settings/ai-assistant' }] as const

export type QueryAiAssistantSettingsSuspenseQueryKey = ReturnType<typeof queryAiAssistantSettingsSuspenseQueryKey>

export function queryAiAssistantSettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryAiAssistantSettingsSuspenseQueryKey()
        return queryOptions<QueryAiAssistantSettingsQueryResponse, ResponseErrorConfig<Error>, QueryAiAssistantSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryAiAssistantSettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the authoritative device-owned AI Assistant switch
 * {@link /api/desk/settings/ai-assistant}
 */
export function useQueryAiAssistantSettingsSuspense<TData = QueryAiAssistantSettingsQueryResponse, TQueryKey extends QueryKey = QueryAiAssistantSettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryAiAssistantSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryAiAssistantSettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryAiAssistantSettingsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}