/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QueryCollectionPolicySettingsQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { queryCollectionPolicySettings } from "../../clients.ts";

export const queryCollectionPolicySettingsSuspenseQueryKey = () => [{ url: '/api/desk/settings/collection-policy' }] as const

export type QueryCollectionPolicySettingsSuspenseQueryKey = ReturnType<typeof queryCollectionPolicySettingsSuspenseQueryKey>

export function queryCollectionPolicySettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryCollectionPolicySettingsSuspenseQueryKey()
        return queryOptions<QueryCollectionPolicySettingsQueryResponse, ResponseErrorConfig<Error>, QueryCollectionPolicySettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryCollectionPolicySettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the edge collection policy
 * {@link /api/desk/settings/collection-policy}
 */
export function useQueryCollectionPolicySettingsSuspense<TData = QueryCollectionPolicySettingsQueryResponse, TQueryKey extends QueryKey = QueryCollectionPolicySettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryCollectionPolicySettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryCollectionPolicySettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryCollectionPolicySettingsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}