/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QueryAiModelSettingsQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryAiModelSettings } from "../../clients.ts";

export const queryAiModelSettingsQueryKey = () => [{ url: '/api/desk/settings/ai-model' }] as const

export type QueryAiModelSettingsQueryKey = ReturnType<typeof queryAiModelSettingsQueryKey>

export function queryAiModelSettingsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryAiModelSettingsQueryKey()
        return queryOptions<QueryAiModelSettingsQueryResponse, ResponseErrorConfig<Error>, QueryAiModelSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryAiModelSettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query AI model settings
 * {@link /api/desk/settings/ai-model}
 */
export function useQueryAiModelSettings<TData = QueryAiModelSettingsQueryResponse, TQueryData = QueryAiModelSettingsQueryResponse, TQueryKey extends QueryKey = QueryAiModelSettingsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryAiModelSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryAiModelSettingsQueryKey()
         

         const query = useQuery({
          ...queryAiModelSettingsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}