/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateCollectionPolicySettingsMutationRequest, UpdateCollectionPolicySettingsMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateCollectionPolicySettings } from "../../clients.ts";

export const updateCollectionPolicySettingsMutationKey = () => [{ url: '/api/desk/settings/collection-policy' }] as const

export type UpdateCollectionPolicySettingsMutationKey = ReturnType<typeof updateCollectionPolicySettingsMutationKey>

export function updateCollectionPolicySettingsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateCollectionPolicySettingsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateCollectionPolicySettingsMutationKey()
        return mutationOptions<UpdateCollectionPolicySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateCollectionPolicySettingsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateCollectionPolicySettings(data, config)
          },
        })

}

/**
 * @summary Update the edge collection policy
 * {@link /api/desk/settings/collection-policy}
 */
export function useUpdateCollectionPolicySettings<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateCollectionPolicySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateCollectionPolicySettingsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateCollectionPolicySettingsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateCollectionPolicySettingsMutationKey()

          const baseOptions = updateCollectionPolicySettingsMutationOptions(config) as UseMutationOptions<UpdateCollectionPolicySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateCollectionPolicySettingsMutationRequest}, TContext>
          

          return useMutation<UpdateCollectionPolicySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateCollectionPolicySettingsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateCollectionPolicySettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateCollectionPolicySettingsMutationRequest}, TContext>
      
}