/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateDeviceAssistantSettingsMutationRequest, UpdateDeviceAssistantSettingsMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateDeviceAssistantSettings } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateDeviceAssistantSettingsMutationKey = () => [{ url: '/api/desk/settings/device-assistant' }] as const

export type UpdateDeviceAssistantSettingsMutationKey = ReturnType<typeof updateDeviceAssistantSettingsMutationKey>

export function updateDeviceAssistantSettingsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateDeviceAssistantSettingsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateDeviceAssistantSettingsMutationKey()
        return mutationOptions<UpdateDeviceAssistantSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateDeviceAssistantSettingsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateDeviceAssistantSettings(data, config)
          },
        })

}

/**
 * @summary Compare-and-set the authoritative device-owned Device Assistant switch
 * {@link /api/desk/settings/device-assistant}
 */
export function useUpdateDeviceAssistantSettings<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateDeviceAssistantSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateDeviceAssistantSettingsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateDeviceAssistantSettingsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateDeviceAssistantSettingsMutationKey()

          const baseOptions = updateDeviceAssistantSettingsMutationOptions(config) as UseMutationOptions<UpdateDeviceAssistantSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateDeviceAssistantSettingsMutationRequest}, TContext>
          

          return useMutation<UpdateDeviceAssistantSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateDeviceAssistantSettingsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateDeviceAssistantSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateDeviceAssistantSettingsMutationRequest}, TContext>
      
}