export type { GetWebSearchQueryKey } from "./useGetWebSearch.ts";
export type { GetWebSearchSuspenseQueryKey } from "./useGetWebSearchSuspense.ts";
export type { TestWebSearchMutationKey } from "./useTestWebSearch.ts";
export type { UpdateWebSearchMutationKey } from "./useUpdateWebSearch.ts";
export { getWebSearchQueryKey } from "./useGetWebSearch.ts";
export { getWebSearchQueryOptions } from "./useGetWebSearch.ts";
export { useGetWebSearch } from "./useGetWebSearch.ts";
export { getWebSearchSuspenseQueryKey } from "./useGetWebSearchSuspense.ts";
export { getWebSearchSuspenseQueryOptions } from "./useGetWebSearchSuspense.ts";
export { useGetWebSearchSuspense } from "./useGetWebSearchSuspense.ts";
export { testWebSearchMutationKey } from "./useTestWebSearch.ts";
export { testWebSearchMutationOptions } from "./useTestWebSearch.ts";
export { useTestWebSearch } from "./useTestWebSearch.ts";
export { updateWebSearchMutationKey } from "./useUpdateWebSearch.ts";
export { updateWebSearchMutationOptions } from "./useUpdateWebSearch.ts";
export { useUpdateWebSearch } from "./useUpdateWebSearch.ts";