/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetWebSearchQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getWebSearch } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getWebSearchQueryKey = () => [{ url: '/api/admin/system/web-search' }] as const

export type GetWebSearchQueryKey = ReturnType<typeof getWebSearchQueryKey>

export function getWebSearchQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getWebSearchQueryKey()
        return queryOptions<GetWebSearchQueryResponse, ResponseErrorConfig<Error>, GetWebSearchQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getWebSearch({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/admin/system/web-search}
 */
export function useGetWebSearch<TData = GetWebSearchQueryResponse, TQueryData = GetWebSearchQueryResponse, TQueryKey extends QueryKey = GetWebSearchQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetWebSearchQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getWebSearchQueryKey()
         

         const query = useQuery({
          ...getWebSearchQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}