/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TestWebSearchMutationRequest, TestWebSearchMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { testWebSearch } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const testWebSearchMutationKey = () => [{ url: '/api/admin/system/web-search/test' }] as const

export type TestWebSearchMutationKey = ReturnType<typeof testWebSearchMutationKey>

export function testWebSearchMutationOptions<TContext = unknown>(config: Partial<RequestConfig<TestWebSearchMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = testWebSearchMutationKey()
        return mutationOptions<TestWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: TestWebSearchMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return testWebSearch(data, config)
          },
        })

}

/**
 * {@link /api/admin/system/web-search/test}
 */
export function useTestWebSearch<TContext>(options: 
{
  mutation?: UseMutationOptions<TestWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: TestWebSearchMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TestWebSearchMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? testWebSearchMutationKey()

          const baseOptions = testWebSearchMutationOptions(config) as UseMutationOptions<TestWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: TestWebSearchMutationRequest}, TContext>
          

          return useMutation<TestWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: TestWebSearchMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<TestWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: TestWebSearchMutationRequest}, TContext>
      
}