/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateWebSearchMutationRequest, UpdateWebSearchMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateWebSearch } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateWebSearchMutationKey = () => [{ url: '/api/admin/system/web-search' }] as const

export type UpdateWebSearchMutationKey = ReturnType<typeof updateWebSearchMutationKey>

export function updateWebSearchMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateWebSearchMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateWebSearchMutationKey()
        return mutationOptions<UpdateWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: UpdateWebSearchMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateWebSearch(data, config)
          },
        })

}

/**
 * {@link /api/admin/system/web-search}
 */
export function useUpdateWebSearch<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: UpdateWebSearchMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateWebSearchMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateWebSearchMutationKey()

          const baseOptions = updateWebSearchMutationOptions(config) as UseMutationOptions<UpdateWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: UpdateWebSearchMutationRequest}, TContext>
          

          return useMutation<UpdateWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: UpdateWebSearchMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateWebSearchMutationResponse, ResponseErrorConfig<Error>, {data: UpdateWebSearchMutationRequest}, TContext>
      
}