/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { SupportStatusQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { supportStatus } from "../../clients.ts";

export const supportStatusSuspenseQueryKey = () => [{ url: '/api/desk/support/status' }] as const

export type SupportStatusSuspenseQueryKey = ReturnType<typeof supportStatusSuspenseQueryKey>

export function supportStatusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = supportStatusSuspenseQueryKey()
        return queryOptions<SupportStatusQueryResponse, ResponseErrorConfig<Error>, SupportStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return supportStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the current temporary-support session status
 * {@link /api/desk/support/status}
 */
export function useSupportStatusSuspense<TData = SupportStatusQueryResponse, TQueryKey extends QueryKey = SupportStatusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<SupportStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? supportStatusSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...supportStatusSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}