/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { SupportStatusQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { supportStatus } from "../../clients.ts";

export const supportStatusQueryKey = () => [{ url: '/api/desk/support/status' }] as const

export type SupportStatusQueryKey = ReturnType<typeof supportStatusQueryKey>

export function supportStatusQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = supportStatusQueryKey()
        return queryOptions<SupportStatusQueryResponse, ResponseErrorConfig<Error>, SupportStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return supportStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query the current temporary-support session status
 * {@link /api/desk/support/status}
 */
export function useSupportStatus<TData = SupportStatusQueryResponse, TQueryData = SupportStatusQueryResponse, TQueryKey extends QueryKey = SupportStatusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<SupportStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? supportStatusQueryKey()
         

         const query = useQuery({
          ...supportStatusQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}