[package]
name = "desk-turn"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
desk-utils = { workspace = true }
desk-signal-facade = { workspace = true }

turn = { workspace = true }
stun = { workspace = true }
webrtc = { workspace = true }
webrtc-util = { workspace = true }

utoipa = { workspace = true }
serde = { workspace = true }

async-trait = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
actix-web = { workspace = true }
hmac = { workspace = true }
sha1 = { workspace = true }
base64 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
