[package]
name = "desk-turn"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
desk-utils = { path = "../utils" }

utoipa = { workspace = true }
serde = { workspace = true }
turn-server = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
actix-web = { workspace = true }
