import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import { AiGeneratedMark } from "./ai-generated-mark";

// i18n: real en-US locale so assertions match the copy users actually see.
vi.mock("react-i18next", () =>
    import("@/test-utils/i18n-mock").then((m) => m.reactI18nextMock()),
);

describe("AiGeneratedMark", () => {
    it("renders the visible marking even without provenance (fail-closed)", () => {
        // The content's AI-ness is established by the caller; a missing or stripped
        // provenance must never hide the mark.
        render(<AiGeneratedMark />);
        const mark = screen.getByRole("note");
        expect(mark).toHaveTextContent("AI-generated");
        expect(mark).toHaveAttribute("aria-label", "AI-generated content");
    });

    it("still marks when provenance is null", () => {
        render(<AiGeneratedMark provenance={null} />);
        expect(screen.getByRole("note")).toHaveTextContent("AI-generated");
    });

    it("names the model in the tooltip when provenance carries one", () => {
        render(
            <AiGeneratedMark
                provenance={{
                    model_id: "gpt-4o",
                    generated_at: "2026-07-14T00:00:00Z",
                    marking_scheme: "lcxl-ai-provenance/1",
                }}
            />,
        );
        expect(screen.getByRole("note")).toHaveAttribute(
            "title",
            "Generated by AI model gpt-4o",
        );
    });

    it("falls back to the generic tooltip when the model is unknown", () => {
        // The fleet rollup does not persist a model name; the mark must still render
        // with the generic label rather than a blank model tooltip.
        render(
            <AiGeneratedMark
                provenance={{ generated_at: "2026-07-14T00:00:00Z" }}
            />,
        );
        expect(screen.getByRole("note")).toHaveAttribute("title", "AI-generated");
    });
});
