/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetSubagentPolicyQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getSubagentPolicy } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getSubagentPolicyQueryKey = () => [{ url: '/api/admin/system/subagent-policy' }] as const

export type GetSubagentPolicyQueryKey = ReturnType<typeof getSubagentPolicyQueryKey>

export function getSubagentPolicyQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getSubagentPolicyQueryKey()
        return queryOptions<GetSubagentPolicyQueryResponse, ResponseErrorConfig<Error>, GetSubagentPolicyQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getSubagentPolicy({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/admin/system/subagent-policy}
 */
export function useGetSubagentPolicy<TData = GetSubagentPolicyQueryResponse, TQueryData = GetSubagentPolicyQueryResponse, TQueryKey extends QueryKey = GetSubagentPolicyQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetSubagentPolicyQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getSubagentPolicyQueryKey()
         

         const query = useQuery({
          ...getSubagentPolicyQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}