/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateSubagentPolicyMutationRequest, UpdateSubagentPolicyMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateSubagentPolicy } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateSubagentPolicyMutationKey = () => [{ url: '/api/admin/system/subagent-policy' }] as const

export type UpdateSubagentPolicyMutationKey = ReturnType<typeof updateSubagentPolicyMutationKey>

export function updateSubagentPolicyMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateSubagentPolicyMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateSubagentPolicyMutationKey()
        return mutationOptions<UpdateSubagentPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateSubagentPolicyMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateSubagentPolicy(data, config)
          },
        })

}

/**
 * {@link /api/admin/system/subagent-policy}
 */
export function useUpdateSubagentPolicy<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateSubagentPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateSubagentPolicyMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateSubagentPolicyMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateSubagentPolicyMutationKey()

          const baseOptions = updateSubagentPolicyMutationOptions(config) as UseMutationOptions<UpdateSubagentPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateSubagentPolicyMutationRequest}, TContext>
          

          return useMutation<UpdateSubagentPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateSubagentPolicyMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateSubagentPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateSubagentPolicyMutationRequest}, TContext>
      
}