/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetCurrentUserQueryResponse,
  GetCurrentUser401,
} from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getCurrentUser } from "../../clients.ts";

export const getCurrentUserSuspenseQueryKey = () =>
  [{ url: "/api/currentUser" }] as const;

export type GetCurrentUserSuspenseQueryKey = ReturnType<
  typeof getCurrentUserSuspenseQueryKey
>;

export function getCurrentUserSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getCurrentUserSuspenseQueryKey();
  return queryOptions<
    GetCurrentUserQueryResponse,
    ResponseErrorConfig<GetCurrentUser401>,
    GetCurrentUserQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getCurrentUser({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Get current user
 * {@link /api/currentUser}
 */
export function useGetCurrentUserSuspense<
  TData = GetCurrentUserQueryResponse,
  TQueryKey extends QueryKey = GetCurrentUserSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetCurrentUserQueryResponse,
        ResponseErrorConfig<GetCurrentUser401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getCurrentUserSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getCurrentUserSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetCurrentUser401>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
