/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { ExportDeviceFileRecoveryMutationRequest, ExportDeviceFileRecoveryMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { exportDeviceFileRecovery } from "../../clients.ts";

export const exportDeviceFileRecoveryMutationKey = () => [{ url: '/api/my/device-file-recovery/export' }] as const

export type ExportDeviceFileRecoveryMutationKey = ReturnType<typeof exportDeviceFileRecoveryMutationKey>

export function exportDeviceFileRecoveryMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ExportDeviceFileRecoveryMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = exportDeviceFileRecoveryMutationKey()
        return mutationOptions<ExportDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ExportDeviceFileRecoveryMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return exportDeviceFileRecovery(data, config)
          },
        })

}

/**
 * @summary Export an existing conversation's file backup
 * {@link /api/my/device-file-recovery/export}
 */
export function useExportDeviceFileRecovery<TContext>(options: 
{
  mutation?: UseMutationOptions<ExportDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ExportDeviceFileRecoveryMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ExportDeviceFileRecoveryMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? exportDeviceFileRecoveryMutationKey()

          const baseOptions = exportDeviceFileRecoveryMutationOptions(config) as UseMutationOptions<ExportDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ExportDeviceFileRecoveryMutationRequest}, TContext>
          

          return useMutation<ExportDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ExportDeviceFileRecoveryMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ExportDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ExportDeviceFileRecoveryMutationRequest}, TContext>
      
}