/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListFileRecoveryCleanupQueryResponse, ListFileRecoveryCleanupQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listFileRecoveryCleanup } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listFileRecoveryCleanupQueryKey = (params?: ListFileRecoveryCleanupQueryParams) => [{ url: '/api/my/device-file-recovery/cleanup-status' }, ...(params ? [params] : [])] as const

export type ListFileRecoveryCleanupQueryKey = ReturnType<typeof listFileRecoveryCleanupQueryKey>

export function listFileRecoveryCleanupQueryOptions(params?: ListFileRecoveryCleanupQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listFileRecoveryCleanupQueryKey(params)
        return queryOptions<ListFileRecoveryCleanupQueryResponse, ResponseErrorConfig<Error>, ListFileRecoveryCleanupQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listFileRecoveryCleanup(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List pending backup cleanup after conversation deletion
 * {@link /api/my/device-file-recovery/cleanup-status}
 */
export function useListFileRecoveryCleanup<TData = ListFileRecoveryCleanupQueryResponse, TQueryData = ListFileRecoveryCleanupQueryResponse, TQueryKey extends QueryKey = ListFileRecoveryCleanupQueryKey>(params?: ListFileRecoveryCleanupQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListFileRecoveryCleanupQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listFileRecoveryCleanupQueryKey(params)
         

         const query = useQuery({
          ...listFileRecoveryCleanupQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}