/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ManageDeviceFileRecoveryMutationRequest, ManageDeviceFileRecoveryMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { manageDeviceFileRecovery } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const manageDeviceFileRecoveryMutationKey = () => [{ url: '/api/my/device-file-recovery/manage' }] as const

export type ManageDeviceFileRecoveryMutationKey = ReturnType<typeof manageDeviceFileRecoveryMutationKey>

export function manageDeviceFileRecoveryMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ManageDeviceFileRecoveryMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = manageDeviceFileRecoveryMutationKey()
        return mutationOptions<ManageDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ManageDeviceFileRecoveryMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return manageDeviceFileRecovery(data, config)
          },
        })

}

/**
 * @summary Manage the owner's device file backups
 * {@link /api/my/device-file-recovery/manage}
 */
export function useManageDeviceFileRecovery<TContext>(options: 
{
  mutation?: UseMutationOptions<ManageDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ManageDeviceFileRecoveryMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ManageDeviceFileRecoveryMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? manageDeviceFileRecoveryMutationKey()

          const baseOptions = manageDeviceFileRecoveryMutationOptions(config) as UseMutationOptions<ManageDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ManageDeviceFileRecoveryMutationRequest}, TContext>
          

          return useMutation<ManageDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ManageDeviceFileRecoveryMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ManageDeviceFileRecoveryMutationResponse, ResponseErrorConfig<Error>, {data: ManageDeviceFileRecoveryMutationRequest}, TContext>
      
}