/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RetryFileRecoveryCleanupMutationRequest, RetryFileRecoveryCleanupMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { retryFileRecoveryCleanup } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const retryFileRecoveryCleanupMutationKey = () => [{ url: '/api/my/device-file-recovery/cleanup-retry' }] as const

export type RetryFileRecoveryCleanupMutationKey = ReturnType<typeof retryFileRecoveryCleanupMutationKey>

export function retryFileRecoveryCleanupMutationOptions<TContext = unknown>(config: Partial<RequestConfig<RetryFileRecoveryCleanupMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = retryFileRecoveryCleanupMutationKey()
        return mutationOptions<RetryFileRecoveryCleanupMutationResponse, ResponseErrorConfig<Error>, {data: RetryFileRecoveryCleanupMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return retryFileRecoveryCleanup(data, config)
          },
        })

}

/**
 * @summary Retry pending backup cleanup
 * {@link /api/my/device-file-recovery/cleanup-retry}
 */
export function useRetryFileRecoveryCleanup<TContext>(options: 
{
  mutation?: UseMutationOptions<RetryFileRecoveryCleanupMutationResponse, ResponseErrorConfig<Error>, {data: RetryFileRecoveryCleanupMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<RetryFileRecoveryCleanupMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? retryFileRecoveryCleanupMutationKey()

          const baseOptions = retryFileRecoveryCleanupMutationOptions(config) as UseMutationOptions<RetryFileRecoveryCleanupMutationResponse, ResponseErrorConfig<Error>, {data: RetryFileRecoveryCleanupMutationRequest}, TContext>
          

          return useMutation<RetryFileRecoveryCleanupMutationResponse, ResponseErrorConfig<Error>, {data: RetryFileRecoveryCleanupMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<RetryFileRecoveryCleanupMutationResponse, ResponseErrorConfig<Error>, {data: RetryFileRecoveryCleanupMutationRequest}, TContext>
      
}