/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListFilesQueryResponse, ListFilesQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { listFiles } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listFilesSuspenseQueryKey = (params: ListFilesQueryParams) => [{ url: '/api/desk/file/list' }, ...(params ? [params] : [])] as const

export type ListFilesSuspenseQueryKey = ReturnType<typeof listFilesSuspenseQueryKey>

export function listFilesSuspenseQueryOptions(params: ListFilesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listFilesSuspenseQueryKey(params)
        return queryOptions<ListFilesQueryResponse, ResponseErrorConfig<Error>, ListFilesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listFiles(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List files on remote desk
 * {@link /api/desk/file/list}
 */
export function useListFilesSuspense<TData = ListFilesQueryResponse, TQueryKey extends QueryKey = ListFilesSuspenseQueryKey>(params: ListFilesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListFilesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listFilesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...listFilesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}