/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsUnassociatedQueryResponse, GetModelMetricsUnassociatedQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getModelMetricsUnassociated } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getModelMetricsUnassociatedSuspenseQueryKey = (params?: GetModelMetricsUnassociatedQueryParams) => [{ url: '/api/model/metrics/unassociated' }, ...(params ? [params] : [])] as const

export type GetModelMetricsUnassociatedSuspenseQueryKey = ReturnType<typeof getModelMetricsUnassociatedSuspenseQueryKey>

export function getModelMetricsUnassociatedSuspenseQueryOptions(params?: GetModelMetricsUnassociatedQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsUnassociatedSuspenseQueryKey(params)
        return queryOptions<GetModelMetricsUnassociatedQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsUnassociatedQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsUnassociated(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query content-free facts missing original attribution or dispatch start
 * {@link /api/model/metrics/unassociated}
 */
export function useGetModelMetricsUnassociatedSuspense<TData = GetModelMetricsUnassociatedQueryResponse, TQueryKey extends QueryKey = GetModelMetricsUnassociatedSuspenseQueryKey>(params?: GetModelMetricsUnassociatedQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetModelMetricsUnassociatedQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsUnassociatedSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getModelMetricsUnassociatedSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}