/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsToolsQueryResponse, GetModelMetricsToolsQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getModelMetricsTools } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getModelMetricsToolsQueryKey = (params?: GetModelMetricsToolsQueryParams) => [{ url: '/api/model/metrics/tools' }, ...(params ? [params] : [])] as const

export type GetModelMetricsToolsQueryKey = ReturnType<typeof getModelMetricsToolsQueryKey>

export function getModelMetricsToolsQueryOptions(params?: GetModelMetricsToolsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsToolsQueryKey(params)
        return queryOptions<GetModelMetricsToolsQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsToolsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsTools(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query model observation tools
 * {@link /api/model/metrics/tools}
 */
export function useGetModelMetricsTools<TData = GetModelMetricsToolsQueryResponse, TQueryData = GetModelMetricsToolsQueryResponse, TQueryKey extends QueryKey = GetModelMetricsToolsQueryKey>(params?: GetModelMetricsToolsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetModelMetricsToolsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsToolsQueryKey(params)
         

         const query = useQuery({
          ...getModelMetricsToolsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}