/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsStatusQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getModelMetricsStatus } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getModelMetricsStatusQueryKey = () => [{ url: '/api/model/metrics/status' }] as const

export type GetModelMetricsStatusQueryKey = ReturnType<typeof getModelMetricsStatusQueryKey>

export function getModelMetricsStatusQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsStatusQueryKey()
        return queryOptions<GetModelMetricsStatusQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get model observation health
 * {@link /api/model/metrics/status}
 */
export function useGetModelMetricsStatus<TData = GetModelMetricsStatusQueryResponse, TQueryData = GetModelMetricsStatusQueryResponse, TQueryKey extends QueryKey = GetModelMetricsStatusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetModelMetricsStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsStatusQueryKey()
         

         const query = useQuery({
          ...getModelMetricsStatusQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}