/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsSeriesQueryResponse, GetModelMetricsSeriesQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getModelMetricsSeries } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getModelMetricsSeriesSuspenseQueryKey = (params?: GetModelMetricsSeriesQueryParams) => [{ url: '/api/model/metrics/series' }, ...(params ? [params] : [])] as const

export type GetModelMetricsSeriesSuspenseQueryKey = ReturnType<typeof getModelMetricsSeriesSuspenseQueryKey>

export function getModelMetricsSeriesSuspenseQueryOptions(params?: GetModelMetricsSeriesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsSeriesSuspenseQueryKey(params)
        return queryOptions<GetModelMetricsSeriesQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsSeriesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsSeries(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query model observation series
 * {@link /api/model/metrics/series}
 */
export function useGetModelMetricsSeriesSuspense<TData = GetModelMetricsSeriesQueryResponse, TQueryKey extends QueryKey = GetModelMetricsSeriesSuspenseQueryKey>(params?: GetModelMetricsSeriesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetModelMetricsSeriesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsSeriesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getModelMetricsSeriesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}