/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsStatusQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getModelMetricsStatus } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getModelMetricsStatusSuspenseQueryKey = () => [{ url: '/api/model/metrics/status' }] as const

export type GetModelMetricsStatusSuspenseQueryKey = ReturnType<typeof getModelMetricsStatusSuspenseQueryKey>

export function getModelMetricsStatusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsStatusSuspenseQueryKey()
        return queryOptions<GetModelMetricsStatusQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get model observation health
 * {@link /api/model/metrics/status}
 */
export function useGetModelMetricsStatusSuspense<TData = GetModelMetricsStatusQueryResponse, TQueryKey extends QueryKey = GetModelMetricsStatusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetModelMetricsStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsStatusSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getModelMetricsStatusSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}