/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsSettingsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getModelMetricsSettings } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getModelMetricsSettingsSuspenseQueryKey = () => [{ url: '/api/model/metrics/settings' }] as const

export type GetModelMetricsSettingsSuspenseQueryKey = ReturnType<typeof getModelMetricsSettingsSuspenseQueryKey>

export function getModelMetricsSettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsSettingsSuspenseQueryKey()
        return queryOptions<GetModelMetricsSettingsQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsSettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsSettings({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get shared model observation settings
 * {@link /api/model/metrics/settings}
 */
export function useGetModelMetricsSettingsSuspense<TData = GetModelMetricsSettingsQueryResponse, TQueryKey extends QueryKey = GetModelMetricsSettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetModelMetricsSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsSettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getModelMetricsSettingsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}