/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsCallsQueryResponse, GetModelMetricsCallsQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getModelMetricsCalls } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getModelMetricsCallsQueryKey = (params?: GetModelMetricsCallsQueryParams) => [{ url: '/api/model/metrics/calls' }, ...(params ? [params] : [])] as const

export type GetModelMetricsCallsQueryKey = ReturnType<typeof getModelMetricsCallsQueryKey>

export function getModelMetricsCallsQueryOptions(params?: GetModelMetricsCallsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsCallsQueryKey(params)
        return queryOptions<GetModelMetricsCallsQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsCallsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsCalls(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query model observation calls
 * {@link /api/model/metrics/calls}
 */
export function useGetModelMetricsCalls<TData = GetModelMetricsCallsQueryResponse, TQueryData = GetModelMetricsCallsQueryResponse, TQueryKey extends QueryKey = GetModelMetricsCallsQueryKey>(params?: GetModelMetricsCallsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetModelMetricsCallsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsCallsQueryKey(params)
         

         const query = useQuery({
          ...getModelMetricsCallsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}