/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelMetricsCallQueryResponse, GetModelMetricsCallPathParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getModelMetricsCall } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getModelMetricsCallSuspenseQueryKey = (observation_id: GetModelMetricsCallPathParams["observation_id"] | undefined) => [{ url: '/api/model/metrics/calls/:observation_id', params: {observation_id:observation_id} }] as const

export type GetModelMetricsCallSuspenseQueryKey = ReturnType<typeof getModelMetricsCallSuspenseQueryKey>

export function getModelMetricsCallSuspenseQueryOptions(observation_id: GetModelMetricsCallPathParams["observation_id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelMetricsCallSuspenseQueryKey(observation_id)
        return queryOptions<GetModelMetricsCallQueryResponse, ResponseErrorConfig<Error>, GetModelMetricsCallQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelMetricsCall(observation_id, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get content-free model observation details
 * {@link /api/model/metrics/calls/:observation_id}
 */
export function useGetModelMetricsCallSuspense<TData = GetModelMetricsCallQueryResponse, TQueryKey extends QueryKey = GetModelMetricsCallSuspenseQueryKey>(observation_id: GetModelMetricsCallPathParams["observation_id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetModelMetricsCallQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelMetricsCallSuspenseQueryKey(observation_id)
         

         const query = useSuspenseQuery({
          ...getModelMetricsCallSuspenseQueryOptions(observation_id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}