/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateModelMetricsSettingsMutationRequest, UpdateModelMetricsSettingsMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateModelMetricsSettings } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateModelMetricsSettingsMutationKey = () => [{ url: '/api/model/metrics/settings' }] as const

export type UpdateModelMetricsSettingsMutationKey = ReturnType<typeof updateModelMetricsSettingsMutationKey>

export function updateModelMetricsSettingsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateModelMetricsSettingsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateModelMetricsSettingsMutationKey()
        return mutationOptions<UpdateModelMetricsSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateModelMetricsSettingsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateModelMetricsSettings(data, config)
          },
        })

}

/**
 * @summary Update shared model observation settings with revision CAS
 * {@link /api/model/metrics/settings}
 */
export function useUpdateModelMetricsSettings<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateModelMetricsSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateModelMetricsSettingsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateModelMetricsSettingsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateModelMetricsSettingsMutationKey()

          const baseOptions = updateModelMetricsSettingsMutationOptions(config) as UseMutationOptions<UpdateModelMetricsSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateModelMetricsSettingsMutationRequest}, TContext>
          

          return useMutation<UpdateModelMetricsSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateModelMetricsSettingsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateModelMetricsSettingsMutationResponse, ResponseErrorConfig<Error>, {data: UpdateModelMetricsSettingsMutationRequest}, TContext>
      
}