/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateScheduleBudgetPolicyMutationRequest, UpdateScheduleBudgetPolicyMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateScheduleBudgetPolicy } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateScheduleBudgetPolicyMutationKey = () => [{ url: '/api/admin/system/schedule-budget-policy' }] as const

export type UpdateScheduleBudgetPolicyMutationKey = ReturnType<typeof updateScheduleBudgetPolicyMutationKey>

export function updateScheduleBudgetPolicyMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateScheduleBudgetPolicyMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateScheduleBudgetPolicyMutationKey()
        return mutationOptions<UpdateScheduleBudgetPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateScheduleBudgetPolicyMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateScheduleBudgetPolicy(data, config)
          },
        })

}

/**
 * {@link /api/admin/system/schedule-budget-policy}
 */
export function useUpdateScheduleBudgetPolicy<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateScheduleBudgetPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateScheduleBudgetPolicyMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateScheduleBudgetPolicyMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateScheduleBudgetPolicyMutationKey()

          const baseOptions = updateScheduleBudgetPolicyMutationOptions(config) as UseMutationOptions<UpdateScheduleBudgetPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateScheduleBudgetPolicyMutationRequest}, TContext>
          

          return useMutation<UpdateScheduleBudgetPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateScheduleBudgetPolicyMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateScheduleBudgetPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateScheduleBudgetPolicyMutationRequest}, TContext>
      
}