/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UninstallServiceMutationResponse, UninstallService503 } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { uninstallService } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const uninstallServiceMutationKey = () => [{ url: '/api/service/uninstall' }] as const

export type UninstallServiceMutationKey = ReturnType<typeof uninstallServiceMutationKey>

export function uninstallServiceMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = uninstallServiceMutationKey()
        return mutationOptions<UninstallServiceMutationResponse, ResponseErrorConfig<UninstallService503>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return uninstallService(config)
          },
        })

}

/**
 * @summary Uninstall OS system service
 * {@link /api/service/uninstall}
 */
export function useUninstallService<TContext>(options: 
{
  mutation?: UseMutationOptions<UninstallServiceMutationResponse, ResponseErrorConfig<UninstallService503>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? uninstallServiceMutationKey()

          const baseOptions = uninstallServiceMutationOptions(config) as UseMutationOptions<UninstallServiceMutationResponse, ResponseErrorConfig<UninstallService503>, void, TContext>
          

          return useMutation<UninstallServiceMutationResponse, ResponseErrorConfig<UninstallService503>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UninstallServiceMutationResponse, ResponseErrorConfig<UninstallService503>, void, TContext>
      
}