/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QueryManagerLinkStatusQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryManagerLinkStatus } from "../../clients.ts";

export const queryManagerLinkStatusQueryKey = () => [{ url: '/api/desk/manager-link/status' }] as const

export type QueryManagerLinkStatusQueryKey = ReturnType<typeof queryManagerLinkStatusQueryKey>

export function queryManagerLinkStatusQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryManagerLinkStatusQueryKey()
        return queryOptions<QueryManagerLinkStatusQueryResponse, ResponseErrorConfig<Error>, QueryManagerLinkStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryManagerLinkStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query host→manager link status
 * {@link /api/desk/manager-link/status}
 */
export function useQueryManagerLinkStatus<TData = QueryManagerLinkStatusQueryResponse, TQueryData = QueryManagerLinkStatusQueryResponse, TQueryKey extends QueryKey = QueryManagerLinkStatusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryManagerLinkStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryManagerLinkStatusQueryKey()
         

         const query = useQuery({
          ...queryManagerLinkStatusQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}