/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QueryManagerLinkStatusQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { queryManagerLinkStatus } from "../../clients.ts";

export const queryManagerLinkStatusSuspenseQueryKey = () => [{ url: '/api/desk/manager-link/status' }] as const

export type QueryManagerLinkStatusSuspenseQueryKey = ReturnType<typeof queryManagerLinkStatusSuspenseQueryKey>

export function queryManagerLinkStatusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryManagerLinkStatusSuspenseQueryKey()
        return queryOptions<QueryManagerLinkStatusQueryResponse, ResponseErrorConfig<Error>, QueryManagerLinkStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return queryManagerLinkStatus({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query host→manager link status
 * {@link /api/desk/manager-link/status}
 */
export function useQueryManagerLinkStatusSuspense<TData = QueryManagerLinkStatusQueryResponse, TQueryKey extends QueryKey = QueryManagerLinkStatusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryManagerLinkStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? queryManagerLinkStatusSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryManagerLinkStatusSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}