/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const audioDataFlowEnum = {
    Render: "Render",
    Capture: "Capture"
} as const;

export type AudioDataFlowEnumKey = (typeof audioDataFlowEnum)[keyof typeof audioDataFlowEnum];

/**
 * @description Audio Data Flow Enum
*/
export type AudioDataFlow = AudioDataFlowEnumKey;

/**
 * @description Audio Device Model
*/
export type AudioDevice = {
    /**
     * @description Audio Data Flow Enum
     * @type string
    */
    data_flow: AudioDataFlow;
    /**
     * @description Is default device for this data flow?
     * @type boolean
    */
    default: boolean;
    /**
     * @description Audio device friendly name, e.g. \"Speakers (Definition Audio)\"
     * @type string
    */
    firendly_name: string;
    /**
     * @description Device id
     * @type string
    */
    id: string;
};

/**
 * @description CPU information
*/
export type CpuInfo = {
    /**
     * @description CPU brand
     * @type string
    */
    brand: string;
    /**
     * @description CPU frequency in MHz
     * @minLength 0
     * @type integer, int64
    */
    frequency: bigint;
    /**
     * @description CPU name
     * @type string
    */
    name: string;
    /**
     * @description CPU usage percentage
     * @type number, float
    */
    usage: number;
    /**
     * @description CPU vendor ID
     * @type string
    */
    vendor_id: string;
};

export type LabelKey = {
    /**
     * @type string,null
    */
    key?: string | null;
    /**
     * @type string,null
    */
    label?: string | null;
};

export type Geographic = {
    city?: (null | LabelKey);
    province?: (null | LabelKey);
};

export type CurrentUser = {
    /**
     * @type string,null
    */
    access?: string | null;
    /**
     * @type string,null
    */
    address?: string | null;
    /**
     * @type string,null
    */
    avatar?: string | null;
    /**
     * @type string,null
    */
    country?: string | null;
    /**
     * @type string,null
    */
    email?: string | null;
    geographic?: (null | Geographic);
    /**
     * @type string,null
    */
    group?: string | null;
    /**
     * @type string
    */
    name: string;
    /**
     * @minLength 0
     * @type integer,null, int32
    */
    notifyCount?: number | null;
    /**
     * @type string,null
    */
    phone?: string | null;
    /**
     * @type string,null
    */
    signature?: string | null;
    /**
     * @type array,null
    */
    tags?: LabelKey[] | null;
    /**
     * @type string,null
    */
    targetSessionId?: string | null;
    /**
     * @type string,null
    */
    title?: string | null;
    /**
     * @minLength 0
     * @type integer,null, int32
    */
    unreadCount?: number | null;
    /**
     * @type string,null
    */
    userid?: string | null;
};

/**
 * @description Request body for deleting a file.
*/
export type DeleteFileRequest = {
    /**
     * @description Whether to delete permanently or move to trash
     * @type boolean,null
    */
    delete_permanently?: boolean | null;
    /**
     * @description The path of file to be deleted
     * @type string
    */
    file_path: string;
    /**
     * @type string,null
    */
    session_id?: string | null;
};

/**
 * @description Selected Audio Device Model
*/
export type SelectedAudioDevice = {
    /**
     * @description Audio Data Flow Enum
     * @type string
    */
    audio_data_flow: AudioDataFlow;
    /**
     * @description Audio device id, None for default audio device
     * @type string,null
    */
    audio_device_id?: string | null;
};

/**
 * @description H264 encoder settings
*/
export type H264EncoderSettings = {
    /**
     * @description Bitrate in bps (bits per second), default is 10,000,000 bps (10 Mbps)
     * @minLength 0
     * @default 10000000
     * @type integer | undefined, int32
    */
    bps?: number;
    /**
     * @description Group of Pictures, default is 0, which means the encoder will decide the value.
     * @minLength 0
     * @default 0
     * @type integer | undefined, int32
    */
    gop?: number;
};

/**
 * @description Opus encoder settings
*/
export type OpusEncoderSettings = {
    /**
     * @default "Audio"
     * @type string | undefined
    */
    application?: string;
    /**
     * @minLength 0
     * @default 2
     * @type integer | undefined, int32
    */
    channels?: number;
    /**
     * @minLength 0
     * @default 48000
     * @type integer | undefined, int32
    */
    sample_rate?: number;
};

export type HotkeySettings = {
    /**
     * @description HOT_KEY_MODIFIERS
     * @minLength 0
     * @default 3
     * @type integer | undefined, int32
    */
    fsmodifiers?: number;
    /**
     * @minLength 0
     * @default 76
     * @type integer | undefined, int32
    */
    vk?: number;
};

/**
 * @description Private screen settings
*/
export type PrivateScreenSettings = {
    /**
     * @description Whether private screen is enabled by default
     * @default false
     * @type boolean | undefined
    */
    enabled?: boolean;
    /**
     * @default null
    */
    hotkey?: (null | HotkeySettings);
    /**
     * @description Optional image path for the private screen background
     * @type string,null
    */
    image_path?: string | null;
    /**
     * @description Optional window extended style for the private screen window
     * @minLength 0
     * @type integer,null, int32
    */
    window_ex_style?: number | null;
    /**
     * @description Optional window style for the private screen window
     * @minLength 0
     * @type integer,null, int32
    */
    window_style?: number | null;
};

/**
 * @description VPX encoder settings
*/
export type VpxEncoderSettings = {
    /**
     * @description Bitrate in bps (bits per second), default is 5,000,000 bps (5 Mbps)
     * @minLength 0
     * @default 5000000
     * @type integer | undefined, int32
    */
    bps?: number;
};

/**
 * @description Desk settings
*/
export type DeskSettings = {
    /**
     * @description Enable adaptive web page resolution
     * @default false
     * @type boolean | undefined
    */
    adaptive_web_page_resolution?: boolean;
    /**
     * @description Selected audio capture device
     * @type string,null
    */
    audio_capture?: string | null;
    /**
     * @default null
    */
    audio_device?: (null | SelectedAudioDevice);
    /**
     * @description Audio encoder name, None for auto detection
     * @type string,null
    */
    audio_encoder?: string | null;
    /**
     * @description Display name
     * @type string,null
    */
    display_name?: string | null;
    /**
     * @description Enable D3D debug mode
     * @default false
     * @type boolean | undefined
    */
    enable_d3d_debug?: boolean;
    /**
     * @default null
    */
    h264_encoder?: (null | H264EncoderSettings);
    /**
     * @description Selected image capture device
     * @type string,null
    */
    image_capture?: string | null;
    /**
     * @default null
    */
    opus_encoder?: (null | OpusEncoderSettings);
    /**
     * @default [object Object]
    */
    private_screen?: PrivateScreenSettings;
    /**
     * @description Enable mouse display on the screen
     * @default true
     * @type boolean | undefined
    */
    show_mouse?: boolean;
    /**
     * @description Video device index
     * @minLength 0
     * @default 0
     * @type integer | undefined, int32
    */
    video_device_index?: number;
    /**
     * @description Video encode bitrate in bps (bits per second)
     * @minLength 0
     * @default 10000000
     * @type integer | undefined, int32
    */
    video_encode_bps?: number;
    /**
     * @description Video encoder name, None for auto detection
     * @type string,null
    */
    video_encoder?: string | null;
    /**
     * @description Video frame rate (e.g., 30 fps)
     * @minLength 0
     * @default 60
     * @type integer | undefined, int32
    */
    video_fps?: number;
    /**
     * @description Video zoom ratio (e.g., 50 for 50% zoom)
     * @minLength 0
     * @default 100
     * @type integer | undefined, int32
    */
    video_zoom_ratio?: number;
    /**
     * @default null
    */
    vp8_encoder?: (null | VpxEncoderSettings);
    /**
     * @default null
    */
    vp9_encoder?: (null | VpxEncoderSettings);
};

export type DeviceCodeBatchDeleteParams = {
    /**
     * @type array
    */
    ids: number[];
};

export type DeviceCodeCreateParams = {
    /**
     * @type string
    */
    client_id: string;
    /**
     * @type string,null
    */
    device_code?: string | null;
};

export type DeviceCodeItem = {
    /**
     * @type string
    */
    clientId: string;
    /**
     * @type string
    */
    createdAt: string;
    /**
     * @type string
    */
    deviceCode: string;
    /**
     * @type integer, int32
    */
    id: number;
    /**
     * @type boolean
    */
    isOnline: boolean;
    /**
     * @type string
    */
    updatedAt: string;
};

export type DeviceCodeListResult = {
    /**
     * @type array
    */
    items: DeviceCodeItem[];
    /**
     * @minLength 0
     * @type integer, int64
    */
    total: bigint;
};

export type DeviceCodeUpdateParams = {
    /**
     * @type string
    */
    device_code: string;
};

/**
 * @description Display Rectangle Struct
*/
export type DisplayRect = {
    /**
     * @description Bottom coordinate of the rectangle
     * @type integer, int32
    */
    bottom: number;
    /**
     * @description Left coordinate of the rectangle
     * @type integer, int32
    */
    left: number;
    /**
     * @description Right coordinate of the rectangle
     * @type integer, int32
    */
    right: number;
    /**
     * @description Top coordinate of the rectangle
     * @type integer, int32
    */
    top: number;
};

/**
 * @description Resolution Struct
*/
export type Resolution = {
    /**
     * @description Height of the resolution in pixels
     * @minLength 0
     * @type integer, int32
    */
    height: number;
    /**
     * @description Width of the resolution in pixels
     * @minLength 0
     * @type integer, int32
    */
    width: number;
};

/**
 * @description Display Info
*/
export type DisplayInfo = {
    /**
     * @description Is the display attached to the desktop
     * @type boolean
    */
    attached_to_desktop: boolean;
    /**
     * @description Display Rectangle Struct
     * @type object
    */
    desktop_coordinates: DisplayRect;
    /**
     * @description Display device name, e.g. \"\\\\.\\DISPLAY1\"
     * @type string
    */
    device_name: string;
    /**
     * @description Display device friendly name, e.g. \"Generic PnP Monitor\"
     * @type string,null
    */
    display_device_name?: string | null;
    /**
     * @description Supported display resolutions (width, height)
     * @type array
    */
    resolutions: Resolution[];
    /**
     * @description Display rotation angle in degrees, e.g. 0, 90, 180, 270
     * @type integer, int32
    */
    rotation: number;
};

export type DownloadRequest = {
    /**
     * @type string
    */
    file_path: string;
    /**
     * @type string
    */
    transfer_id: string;
};

export type DownloadResponse = {
    /**
     * @minLength 0
     * @type integer
    */
    chunk_size: number;
    /**
     * @type string
    */
    file_name: string;
    /**
     * @minLength 0
     * @type integer, int64
    */
    file_size: bigint;
    /**
     * @minLength 0
     * @type integer, int64
    */
    total_chunks: bigint;
    /**
     * @type string
    */
    transfer_id: string;
};

export type FakeCaptcha = {
    /**
     * @minLength 0
     * @type integer,null, int32
    */
    code?: number | null;
    /**
     * @type string,null
    */
    status?: string | null;
};

export type FakeCaptchaParams = {
    /**
     * @type string,null
    */
    phone?: string | null;
};

export type FileInfo = {
    /**
     * @type string, date-time
    */
    accessed: string;
    /**
     * @type string, date-time
    */
    created: string;
    /**
     * @type string,null
    */
    err_msg?: string | null;
    /**
     * @type boolean
    */
    is_dir: boolean;
    /**
     * @type boolean
    */
    is_file: boolean;
    /**
     * @type boolean
    */
    is_symlink: boolean;
    /**
     * @type string, date-time
    */
    modified: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    path: string;
    /**
     * @minLength 0
     * @type integer, int32
    */
    permissions: number;
    /**
     * @minLength 0
     * @type integer, int64
    */
    size: bigint;
};

export type FileListResponse = {
    /**
     * @type array
    */
    file_info_list: FileInfo[];
    /**
     * @type integer, int64
    */
    total_count: bigint;
};

export type UploadRequest = {
    /**
     * @minLength 0
     * @type integer
    */
    chunk_size: number;
    /**
     * @type string
    */
    file_name: string;
    /**
     * @minLength 0
     * @type integer, int64
    */
    file_size: bigint;
    /**
     * @type string
    */
    target_dir: string;
    /**
     * @minLength 0
     * @type integer, int64
    */
    total_chunks: bigint;
    /**
     * @type string
    */
    transfer_id: string;
};

export type UploadResponse = {
    /**
     * @type boolean
    */
    accepted: boolean;
    /**
     * @type string,null
    */
    message?: string | null;
    /**
     * @type string
    */
    transfer_id: string;
};

export type TransferComplete = {
    /**
     * @type string
    */
    transfer_id: string;
};

export type TransferError = {
    /**
     * @type string
    */
    message: string;
    /**
     * @type string
    */
    transfer_id: string;
};

export type TransferCancel = {
    /**
     * @type string
    */
    transfer_id: string;
};

export const fileTransferMessageTypeEnum = {
    download_request: "download_request"
} as const;

export type FileTransferMessageTypeEnumKey = (typeof fileTransferMessageTypeEnum)[keyof typeof fileTransferMessageTypeEnum];

export const fileTransferMessageTypeEnum2 = {
    download_response: "download_response"
} as const;

export type FileTransferMessageTypeEnum2Key = (typeof fileTransferMessageTypeEnum2)[keyof typeof fileTransferMessageTypeEnum2];

export const fileTransferMessageTypeEnum3 = {
    upload_request: "upload_request"
} as const;

export type FileTransferMessageTypeEnum3Key = (typeof fileTransferMessageTypeEnum3)[keyof typeof fileTransferMessageTypeEnum3];

export const fileTransferMessageTypeEnum4 = {
    upload_response: "upload_response"
} as const;

export type FileTransferMessageTypeEnum4Key = (typeof fileTransferMessageTypeEnum4)[keyof typeof fileTransferMessageTypeEnum4];

export const fileTransferMessageTypeEnum5 = {
    transfer_complete: "transfer_complete"
} as const;

export type FileTransferMessageTypeEnum5Key = (typeof fileTransferMessageTypeEnum5)[keyof typeof fileTransferMessageTypeEnum5];

export const fileTransferMessageTypeEnum6 = {
    transfer_error: "transfer_error"
} as const;

export type FileTransferMessageTypeEnum6Key = (typeof fileTransferMessageTypeEnum6)[keyof typeof fileTransferMessageTypeEnum6];

export const fileTransferMessageTypeEnum7 = {
    transfer_cancel: "transfer_cancel"
} as const;

export type FileTransferMessageTypeEnum7Key = (typeof fileTransferMessageTypeEnum7)[keyof typeof fileTransferMessageTypeEnum7];

/**
 * @description File transfer message types (JSON text messages over DataChannel)
*/
export type FileTransferMessage = ((DownloadRequest & {
    /**
     * @type string
    */
    type: FileTransferMessageTypeEnumKey;
}) | (DownloadResponse & {
    /**
     * @type string
    */
    type: FileTransferMessageTypeEnum2Key;
}) | (UploadRequest & {
    /**
     * @type string
    */
    type: FileTransferMessageTypeEnum3Key;
}) | (UploadResponse & {
    /**
     * @type string
    */
    type: FileTransferMessageTypeEnum4Key;
}) | (TransferComplete & {
    /**
     * @type string
    */
    type: FileTransferMessageTypeEnum5Key;
}) | (TransferError & {
    /**
     * @type string
    */
    type: FileTransferMessageTypeEnum6Key;
}) | (TransferCancel & {
    /**
     * @type string
    */
    type: FileTransferMessageTypeEnum7Key;
}));

export type InitParams = {
    /**
     * @type string
    */
    password: string;
    /**
     * @type boolean
    */
    telemetry_consent: boolean;
    /**
     * @type string
    */
    username: string;
};

/**
 * @description RTC IceServer
*/
export type LcxlRTCIceServer = {
    /**
     * @description Credential for the ICE server, if any.
     * @type string
    */
    credential: string;
    /**
     * @description List of URLs associated with the ICE server, e.g. [\"stun:stun.l.google.com:19302\"]
     * @type array
    */
    urls: string[];
    /**
     * @description Username for the ICE server, if any.
     * @type string
    */
    username: string;
};

/**
 * @description InitSignalingData is used to initialize signaling data.\nsee https://github.com/webrtc-rs/webrtc/blob/254bdd5d970933e847dc000de9545040ce16f19f/webrtc/src/peer_connection/configuration.rs
*/
export type InitSignalingData = {
    /**
     * @description Audio device list
     * @type object
    */
    audio_device_list: {
        [key: string]: AudioDevice[];
    };
    /**
     * @description Audio encoder list
     * @type array
    */
    audio_encoder_list: string[];
    /**
     * @description Desk settings
     * @type object
    */
    desk_settings: DeskSettings;
    /**
     * @description Whether the remote end has Tauri UI support (required for whiteboard overlay)
     * @type boolean | undefined
    */
    has_tauri?: boolean;
    /**
     * @description ICE servers to use for signaling.
     * @type array
    */
    ice_servers: LcxlRTCIceServer[];
    /**
     * @description User name for signaling.
     * @type string
    */
    user_name: string;
    /**
     * @description Video device list
     * @type object
    */
    video_device_list: {
        [key: string]: DisplayInfo[];
    };
    /**
     * @description Video encoder list
     * @type array
    */
    video_encoder_list: string[];
};

/**
 * @description Keyboard event data structure\nhttps://developer.mozilla.org/zh-CN/docs/Web/API/KeyboardEvent
*/
export type KeyboardEventData = {
    /**
     * @description whether the key is a system key
     * @type boolean
    */
    alt_key: boolean;
    /**
     * @description key code, e.g. \"KeyA\", \"Enter\", see https://developer.mozilla.org/zh-CN/docs/Web/API/KeyboardEvent/code#code_values
     * @type string
    */
    code: string;
    /**
     * @description whether the ctrl key is pressed
     * @type boolean
    */
    ctrl_key: boolean;
    /**
     * @description keyboard event type, e.g. \"keydown\", \"keyup\", \"keypress\"
     * @type string
    */
    event: string;
    /**
     * @description whether the key is composing
     * @type boolean
    */
    is_composing: boolean;
    /**
     * @description key value, e.g. \"a\", see https://developer.mozilla.org/zh-CN/docs/Web/API/UI_Events/Keyboard_event_key_values
     * @type string
    */
    key: string;
    /**
     * @description physical key code, e.g. 65 for \"a\", see https://developer.mozilla.org/zh-CN/docs/Web/API/KeyboardEvent/keyCode
     * @minLength 0
     * @type integer, int32
    */
    key_code: number;
    /**
     * @description location of the key on the keyboard
     * @type integer, int32
    */
    location: number;
    /**
     * @description whether the meta key is pressed
     * @type boolean
    */
    meta_key: boolean;
    /**
     * @description whether the key is repeated
     * @type boolean
    */
    repeat: boolean;
    /**
     * @description whether the shift key is pressed
     * @type boolean
    */
    shift_key: boolean;
};

/**
 * @description Login params
*/
export type LoginParams = {
    /**
     * @type boolean
    */
    autoLogin: boolean;
    /**
     * @type string,null
    */
    device_code?: string | null;
    /**
     * @type string
    */
    password: string;
    /**
     * @type string
    */
    type: string;
    /**
     * @type string
    */
    username: string;
};

/**
 * @description Login result
*/
export type LoginResult = {
    /**
     * @description return api version of signal/desk/manage server
     * @type integer, int32
    */
    api_version: number;
    /**
     * @type string
    */
    currentAuthority: string;
    /**
     * @type string,null
    */
    startup_mode?: string | null;
    /**
     * @type string
    */
    status: string;
    /**
     * @type string,null
    */
    targetSessionId?: string | null;
    /**
     * @type string
    */
    type: string;
};

/**
 * @description Mouse event data structure\nhttps://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent
*/
export type MouseEventData = {
    /**
     * @description Returns true if the alt key was down when the mouse event was fired.
     * @type boolean
    */
    alt_key: boolean;
    /**
     * @description The button number that was pressed or released (if applicable) when the mouse event was fired.
     * @type integer, int32
    */
    button: number;
    /**
     * @description The buttons being pressed (if any) when the mouse event was fired.
     * @type integer, int32
    */
    buttons: number;
    /**
     * @description The distance that the mouse wheel has been rotated around the X axis (if applicable) when the mouse event was fired.
     * @type number, double
    */
    delta_x: number;
    /**
     * @description The distance that the mouse wheel has been rotated around the Y axis (if applicable) when the mouse event was fired.
     * @type number, double
    */
    delta_y: number;
    /**
     * @description mouse event type, e.g. \"mousemove\", \"mousedown\", \"mouseup\", \"click\", \"dblclick\", \"contextmenu\", \"wheel\"
     * @type string
    */
    event: string;
    /**
     * @description Sequence number to prevent unordered packets (UDP-like channel) from overwriting newer states.
     * @minLength 0
     * @type integer,null, int64
    */
    sequence_number?: number | null;
    /**
     * @description mouse x coordinate(relative to the viewport)
     * @type number, double
    */
    x: number;
    /**
     * @description mouse y coordinate(relative to the viewport)
     * @type number, double
    */
    y: number;
};

export type NoLogintUser = {
    /**
     * @type boolean
    */
    isLogin: boolean;
};

export const operationSystemEnumEnum = {
    Windows: "Windows",
    Linux: "Linux",
    Mac: "Mac",
    Android: "Android",
    Ios: "Ios",
    Web: "Web",
    Other: "Other"
} as const;

export type OperationSystemEnumEnumKey = (typeof operationSystemEnumEnum)[keyof typeof operationSystemEnumEnum];

/**
 * @description Operation system enum
*/
export type OperationSystemEnum = OperationSystemEnumEnumKey;

/**
 * @description Password params
*/
export type PasswordParams = {
    /**
     * @description New password (optional)
     * @type string,null
    */
    new_password?: string | null;
    /**
     * @description New username (optional)
     * @type string,null
    */
    new_username?: string | null;
    /**
     * @description Old password
     * @type string
    */
    password: string;
    /**
     * @description Old username
     * @type string
    */
    username: string;
};

export const remoteDeskTypeEnumEnum = {
    browser: "browser",
    server: "server",
    signal: "signal",
    manager: "manager"
} as const;

export type RemoteDeskTypeEnumEnumKey = (typeof remoteDeskTypeEnumEnum)[keyof typeof remoteDeskTypeEnumEnum];

/**
 * @description Remote Desk Type Enum
*/
export type RemoteDeskTypeEnum = RemoteDeskTypeEnumEnumKey;

export type RestResponseServerInfo = {
    /**
     * @type integer, int32
    */
    code: number;
    /**
     * @description Server information
     * @type object | undefined
    */
    data?: {
        /**
         * @description Current API version supported by the server
         * @type integer, int32
        */
        api_version: number;
        /**
         * @description Indicates whether the system is initialized (e.g., admin password set)
         * @type boolean
        */
        initialized: boolean;
        /**
         * @description Startup mode of the server
         * @type string
        */
        startup_mode: string;
    };
    /**
     * @type string,null
    */
    message?: string | null;
    /**
     * @type boolean
    */
    success: boolean;
};

export type RestResponseSystemInfo = {
    /**
     * @type integer, int32
    */
    code: number;
    /**
     * @description System information
     * @type object | undefined
    */
    data?: {
        /**
         * @description List of CPU information
         * @type array
        */
        cpus: CpuInfo[];
        /**
         * @description Host name
         * @type string,null
        */
        host_name?: string | null;
        /**
         * @description System kernel version
         * @type string,null
        */
        kernel_version?: string | null;
        /**
         * @description System name
         * @type string,null
        */
        name?: string | null;
        /**
         * @description Operating system version
         * @type string,null
        */
        os_version?: string | null;
        /**
         * @description Startup mode
         * @type string
        */
        startup_mode: string;
        /**
         * @description Total memory in bytes
         * @minLength 0
         * @type integer, int64
        */
        total_memory: bigint;
        /**
         * @description Total swap in bytes
         * @minLength 0
         * @type integer, int64
        */
        total_swap: bigint;
        /**
         * @description Used memory in bytes
         * @minLength 0
         * @type integer, int64
        */
        used_memory: bigint;
        /**
         * @description Used swap in bytes
         * @minLength 0
         * @type integer, int64
        */
        used_swap: bigint;
    };
    /**
     * @type string,null
    */
    message?: string | null;
    /**
     * @type boolean
    */
    success: boolean;
};

export type RestResponseSystemSettings = {
    /**
     * @type integer, int32
    */
    code: number;
    /**
     * @description System settings for the application. This struct is used to load and save settings from a configuration file.
     * @type object | undefined
    */
    data?: {
        /**
         * @description Auto start the application on system login
         * @type boolean,null
        */
        auto_start?: boolean | null;
        /**
         * @description Client ID for telemetry
         * @type string,null
        */
        client_id?: string | null;
        /**
         * @description Enable IPv6 support
         * @default true
         * @type boolean | undefined
        */
        enable_ipv6?: boolean;
        /**
         * @description listen ipv4 address for the server to bind to
         * @default "0.0.0.0"
         * @type string | undefined
        */
        listen_addr_ipv4?: string;
        /**
         * @description listen ipv6 address for the server to bind to
         * @default "::"
         * @type string | undefined
        */
        listen_addr_ipv6?: string;
        /**
         * @description Optional locale setting (e.g., \"en\", \"zh-CN\")
         * @type string,null
        */
        locale?: string | null;
        /**
         * @description access logs are printed with the INFO level so ensure it is enabled by default
         * @default "info"
         * @type string | undefined
        */
        log_level?: string;
        /**
         * @description Whether to open the browser automatically on server startup
         * @default false
         * @type boolean | undefined
        */
        open_browser_on_startup?: boolean;
        /**
         * @description port number for the server to bind to
         * @minLength 0
         * @default 8081
         * @type integer | undefined, int32
        */
        port?: number;
        /**
         * @description Signaling server url, if not set, it will be \"ws://127.0.0.1:{port}/signaling\"
         * @type string,null
        */
        signaling_url?: string | null;
        /**
         * @description Telemetry consent status
         * @type boolean,null
        */
        telemetry_consent?: boolean | null;
        /**
         * @description Enable Rust backtrace for errors
         * @default true
         * @type boolean | undefined
        */
        traceback?: boolean;
    };
    /**
     * @type string,null
    */
    message?: string | null;
    /**
     * @type boolean
    */
    success: boolean;
};

export type RestResponseTelemetryStatus = {
    /**
     * @type integer, int32
    */
    code: number;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type boolean,null
        */
        consented?: boolean | null;
        /**
         * @type boolean
        */
        needed: boolean;
    };
    /**
     * @type string,null
    */
    message?: string | null;
    /**
     * @type boolean
    */
    success: boolean;
};

/**
 * @description Server information
*/
export type ServerInfo = {
    /**
     * @description Current API version supported by the server
     * @type integer, int32
    */
    api_version: number;
    /**
     * @description Indicates whether the system is initialized (e.g., admin password set)
     * @type boolean
    */
    initialized: boolean;
    /**
     * @description Startup mode of the server
     * @type string
    */
    startup_mode: string;
};

/**
 * @description Version information for the API.
*/
export type VersionInfo = {
    /**
     * @description The version of the API. This is a simple integer that increments when API is changed.
     * @type integer, int32
    */
    api_version: number;
    /**
     * @description The build number of the server.
     * @type integer, int32
    */
    build_number: number;
    /**
     * @description Client ID of the server.
     * @type string,null
    */
    client_id?: string | null;
    /**
     * @description The commit hash of the server.
     * @type string
    */
    commit_hash: string;
    /**
     * @description Display name of the remote desk.
     * @type string,null
    */
    display_name?: string | null;
    /**
     * @description Operation system enum
     * @type string
    */
    operation_system: OperationSystemEnum;
    /**
     * @description Remote Desk Type Enum
     * @type string
    */
    remote_desk_type: RemoteDeskTypeEnum;
};

/**
 * @description Session information
*/
export type SessionModel = {
    /**
     * @description IP address of the session
     * @type string,null
    */
    ip?: string | null;
    /**
     * @description Session ID
     * @type string
    */
    session_id: string;
    /**
     * @description Version information for the API.
     * @type object
    */
    version_info: VersionInfo;
};

/**
 * @description Session list information
*/
export type SessionList = {
    /**
     * @description Current session ID
     * @type string
    */
    current_session_id: string;
    /**
     * @description Session map
     * @type object
    */
    session_map: {
        [key: string]: SessionModel;
    };
};

/**
 * @description Signal request control data
*/
export type SignalRequestControlData = {
    /**
     * @description whether the control request is accepted
     * @default false
     * @type boolean | undefined
    */
    accept?: boolean;
    /**
     * @description whether to accept clipboard sync
     * @default false
     * @type boolean | undefined
    */
    accept_clipboard_sync?: boolean;
    /**
     * @description whether to accept file transfer
     * @default false
     * @type boolean | undefined
    */
    accept_file_transfer?: boolean;
};

export type SignalingResponseState = {
    /**
     * @description error code\n\nsee alse: desk_utils::DeskErrorCode
     * @type integer, int32
    */
    error_code: number;
    /**
     * @description error message
     * @type string,null
    */
    message?: string | null;
};

export type SignalingType = number;

/**
 * @description Signaling model
*/
export type SignalingModel = {
    /**
     * @description From session id, if None, means from signal server
     * @type string,null
    */
    from_session_id?: string | null;
    /**
     * @description Request id
     * @type string
    */
    request_id: string;
    response_state?: (null | SignalingResponseState);
    /**
     * @description Signaling data
    */
    signaling_data?: any;
    /**
     * @description Signaling type
     * @type integer, int32
    */
    signaling_type: SignalingType;
    /**
     * @description To session id, if None, means to signal server
     * @type string,null
    */
    to_session_id?: string | null;
};

/**
 * @description System information
*/
export type SystemInfo = {
    /**
     * @description List of CPU information
     * @type array
    */
    cpus: CpuInfo[];
    /**
     * @description Host name
     * @type string,null
    */
    host_name?: string | null;
    /**
     * @description System kernel version
     * @type string,null
    */
    kernel_version?: string | null;
    /**
     * @description System name
     * @type string,null
    */
    name?: string | null;
    /**
     * @description Operating system version
     * @type string,null
    */
    os_version?: string | null;
    /**
     * @description Startup mode
     * @type string
    */
    startup_mode: string;
    /**
     * @description Total memory in bytes
     * @minLength 0
     * @type integer, int64
    */
    total_memory: bigint;
    /**
     * @description Total swap in bytes
     * @minLength 0
     * @type integer, int64
    */
    total_swap: bigint;
    /**
     * @description Used memory in bytes
     * @minLength 0
     * @type integer, int64
    */
    used_memory: bigint;
    /**
     * @description Used swap in bytes
     * @minLength 0
     * @type integer, int64
    */
    used_swap: bigint;
};

/**
 * @description System settings for the application. This struct is used to load and save settings from a configuration file.
*/
export type SystemSettings = {
    /**
     * @description Auto start the application on system login
     * @type boolean,null
    */
    auto_start?: boolean | null;
    /**
     * @description Client ID for telemetry
     * @type string,null
    */
    client_id?: string | null;
    /**
     * @description Enable IPv6 support
     * @default true
     * @type boolean | undefined
    */
    enable_ipv6?: boolean;
    /**
     * @description listen ipv4 address for the server to bind to
     * @default "0.0.0.0"
     * @type string | undefined
    */
    listen_addr_ipv4?: string;
    /**
     * @description listen ipv6 address for the server to bind to
     * @default "::"
     * @type string | undefined
    */
    listen_addr_ipv6?: string;
    /**
     * @description Optional locale setting (e.g., \"en\", \"zh-CN\")
     * @type string,null
    */
    locale?: string | null;
    /**
     * @description access logs are printed with the INFO level so ensure it is enabled by default
     * @default "info"
     * @type string | undefined
    */
    log_level?: string;
    /**
     * @description Whether to open the browser automatically on server startup
     * @default false
     * @type boolean | undefined
    */
    open_browser_on_startup?: boolean;
    /**
     * @description port number for the server to bind to
     * @minLength 0
     * @default 8081
     * @type integer | undefined, int32
    */
    port?: number;
    /**
     * @description Signaling server url, if not set, it will be \"ws://127.0.0.1:{port}/signaling\"
     * @type string,null
    */
    signaling_url?: string | null;
    /**
     * @description Telemetry consent status
     * @type boolean,null
    */
    telemetry_consent?: boolean | null;
    /**
     * @description Enable Rust backtrace for errors
     * @default true
     * @type boolean | undefined
    */
    traceback?: boolean;
};

export type TelemetryConsent = {
    /**
     * @type boolean
    */
    consent: boolean;
};

export type TelemetryStatus = {
    /**
     * @type boolean,null
    */
    consented?: boolean | null;
    /**
     * @type boolean
    */
    needed: boolean;
};

/**
 * @description SignalingType::SendDataToTerminal
*/
export type TerminalInputData = {
    /**
     * @type string
    */
    content: string;
};

/**
 * @description Terminal list
*/
export type TerminalList = {
    /**
     * @description terminal command list
     * @type array
    */
    commands: string[][];
    /**
     * @description current terminal index
     * @minLength 0
     * @type integer
    */
    current: number;
};

export type TerminalOutputData = {
    /**
     * @type string
    */
    content: string;
};

export type TerminalResizeData = {
    /**
     * @minLength 0
     * @type integer, int32
    */
    cols: number;
    /**
     * @minLength 0
     * @type integer, int32
    */
    rows: number;
};

export const turnTransportEnum = {
    tcp: "tcp",
    udp: "udp"
} as const;

export type TurnTransportEnumKey = (typeof turnTransportEnum)[keyof typeof turnTransportEnum];

export type TurnTransport = TurnTransportEnumKey;

export type TurnInterface = {
    /**
     * @description turn server listen address
     * @type string
    */
    bind: string;
    /**
     * @description external address\n\nspecify the node external address and port.\nfor the case of exposing the service to the outside,\nyou need to manually specify the server external IP\naddress and service listening port.
     * @type string
    */
    external: string;
    /**
     * @type string
    */
    transport: TurnTransport;
};

export type TurnInfo = {
    /**
     * @type array
    */
    interfaces: TurnInterface[];
    /**
     * @minLength 0
     * @type integer
    */
    port_allocated: number;
    /**
     * @minLength 0
     * @type integer
    */
    port_capacity: number;
    /**
     * @type string
    */
    software: string;
    /**
     * @minLength 0
     * @type integer, int64
    */
    uptime: bigint;
};

export type TurnSession = {
    /**
     * @type array
    */
    channels: number[];
    /**
     * @minLength 0
     * @type integer, int64
    */
    expires: bigint;
    /**
     * @type array
    */
    permissions: number[];
    /**
     * @minLength 0
     * @type integer,null, int32
    */
    port?: number | null;
    /**
     * @type string
    */
    username: string;
};

export type TurnSessionStatistics = {
    /**
     * @minLength 0
     * @type integer
    */
    error_pkts: number;
    /**
     * @minLength 0
     * @type integer
    */
    received_bytes: number;
    /**
     * @minLength 0
     * @type integer
    */
    received_pkts: number;
    /**
     * @minLength 0
     * @type integer
    */
    send_bytes: number;
    /**
     * @minLength 0
     * @type integer
    */
    send_pkts: number;
};

export type UserResponeCurrentUser = {
    /**
     * @type object
    */
    data: {
        /**
         * @type string,null
        */
        access?: string | null;
        /**
         * @type string,null
        */
        address?: string | null;
        /**
         * @type string,null
        */
        avatar?: string | null;
        /**
         * @type string,null
        */
        country?: string | null;
        /**
         * @type string,null
        */
        email?: string | null;
        geographic?: (null | Geographic);
        /**
         * @type string,null
        */
        group?: string | null;
        /**
         * @type string
        */
        name: string;
        /**
         * @minLength 0
         * @type integer,null, int32
        */
        notifyCount?: number | null;
        /**
         * @type string,null
        */
        phone?: string | null;
        /**
         * @type string,null
        */
        signature?: string | null;
        /**
         * @type array,null
        */
        tags?: LabelKey[] | null;
        /**
         * @type string,null
        */
        targetSessionId?: string | null;
        /**
         * @type string,null
        */
        title?: string | null;
        /**
         * @minLength 0
         * @type integer,null, int32
        */
        unreadCount?: number | null;
        /**
         * @type string,null
        */
        userid?: string | null;
    };
    /**
     * @type integer, int32
    */
    errorCode: number;
    /**
     * @type string
    */
    errorMessage: string;
    /**
     * @type boolean
    */
    success: boolean;
};

export type UserResponeNoLogintUser = {
    /**
     * @type object
    */
    data: {
        /**
         * @type boolean
        */
        isLogin: boolean;
    };
    /**
     * @type integer, int32
    */
    errorCode: number;
    /**
     * @type string
    */
    errorMessage: string;
    /**
     * @type boolean
    */
    success: boolean;
};

/**
 * @description Current user info
*/
export type GetCurrentUser200 = UserResponeCurrentUser;

/**
 * @description Unauthorized
*/
export type GetCurrentUser401 = UserResponeNoLogintUser;

export type GetCurrentUserQueryResponse = GetCurrentUser200;

export type GetCurrentUserQuery = {
    Response: GetCurrentUser200;
    Errors: GetCurrentUser401;
};

/**
 * @description Change password successful
*/
export type ChangePassword200 = any;

/**
 * @description Illegal username or password
*/
export type ChangePassword403 = any;

export type ChangePasswordMutationRequest = PasswordParams;

export type ChangePasswordMutationResponse = ChangePassword200;

export type ChangePasswordMutation = {
    Response: ChangePassword200;
    Request: ChangePasswordMutationRequest;
    Errors: ChangePassword403;
};

export type ListDeviceCodesQueryParams = {
    /**
     * @description Page number
     * @minLength 0
     * @type integer | undefined, int64
    */
    page?: bigint;
    /**
     * @description Page size
     * @minLength 0
     * @type integer | undefined, int64
    */
    page_size?: bigint;
};

/**
 * @description List device codes successfully
*/
export type ListDeviceCodes200 = any;

export type ListDeviceCodesQueryResponse = ListDeviceCodes200;

export type ListDeviceCodesQuery = {
    Response: ListDeviceCodes200;
    QueryParams: ListDeviceCodesQueryParams;
    Errors: any;
};

/**
 * @description Create device code successfully
*/
export type CreateDeviceCode200 = any;

export type CreateDeviceCodeMutationRequest = DeviceCodeCreateParams;

export type CreateDeviceCodeMutationResponse = CreateDeviceCode200;

export type CreateDeviceCodeMutation = {
    Response: CreateDeviceCode200;
    Request: CreateDeviceCodeMutationRequest;
    Errors: any;
};

/**
 * @description Batch delete device codes successfully
*/
export type BatchDeleteDeviceCodes200 = any;

export type BatchDeleteDeviceCodesMutationRequest = DeviceCodeBatchDeleteParams;

export type BatchDeleteDeviceCodesMutationResponse = BatchDeleteDeviceCodes200;

export type BatchDeleteDeviceCodesMutation = {
    Response: BatchDeleteDeviceCodes200;
    Request: BatchDeleteDeviceCodesMutationRequest;
    Errors: any;
};

export type UpdateDeviceCodePathParams = {
    /**
     * @type integer, int32
    */
    id: number;
};

/**
 * @description Update device code successfully
*/
export type UpdateDeviceCode200 = any;

export type UpdateDeviceCodeMutationRequest = DeviceCodeUpdateParams;

export type UpdateDeviceCodeMutationResponse = UpdateDeviceCode200;

export type UpdateDeviceCodeMutation = {
    Response: UpdateDeviceCode200;
    Request: UpdateDeviceCodeMutationRequest;
    PathParams: UpdateDeviceCodePathParams;
    Errors: any;
};

export type DeleteDeviceCodePathParams = {
    /**
     * @type integer, int32
    */
    id: number;
};

/**
 * @description Delete device code successfully
*/
export type DeleteDeviceCode200 = any;

export type DeleteDeviceCodeMutationResponse = DeleteDeviceCode200;

export type DeleteDeviceCodeMutation = {
    Response: DeleteDeviceCode200;
    PathParams: DeleteDeviceCodePathParams;
    Errors: any;
};

/**
 * @description Delete file successfully
*/
export type DeleteFile200 = any;

/**
 * @description Bad request
*/
export type DeleteFile400 = any;

/**
 * @description Not implemented
*/
export type DeleteFile501 = any;

export type DeleteFileMutationRequest = DeleteFileRequest;

export type DeleteFileMutationResponse = DeleteFile200;

export type DeleteFileMutation = {
    Response: DeleteFile200;
    Request: DeleteFileMutationRequest;
    Errors: DeleteFile400 | DeleteFile501;
};

export type ListFilesQueryParams = {
    /**
     * @type string
    */
    path: string;
    /**
     * @type integer, int64
    */
    page_no: bigint;
    /**
     * @type integer, int64
    */
    page_count: bigint;
    /**
     * @description Minimum file size
     * @type integer,null, int64
    */
    min_file_size?: number | null;
    /**
     * @description Max file size
     * @type integer,null, int64
    */
    max_file_size?: number | null;
    /**
     * @description File name filtering
     * @type string,null
    */
    file_name?: string | null;
    /**
     * @description New field for file extension filtering
     * @type string,null
    */
    file_extension?: string | null;
    /**
     * @description Optional file extension list filtering, comma(,) separated values.
     * @type string,null
    */
    file_extension_list?: string | null;
    /**
     * @description Optional time range filter for file creation.
     * @type string,null, date-time
    */
    start_created_time?: string | null;
    /**
     * @type string,null, date-time
    */
    end_created_time?: string | null;
    /**
     * @description Optional time range filter for file modification.
     * @type string,null, date-time
    */
    start_modified_time?: string | null;
    /**
     * @type string,null, date-time
    */
    end_modified_time?: string | null;
    /**
     * @description Session ID for remote desk
     * @type string,null
    */
    session_id?: string | null;
};

/**
 * @description The list of file info
*/
export type ListFiles200 = FileListResponse;

export type ListFilesQueryResponse = ListFiles200;

export type ListFilesQuery = {
    Response: ListFiles200;
    QueryParams: ListFilesQueryParams;
    Errors: any;
};

/**
 * @description List of online desk sessions
*/
export type ListSessions200 = SessionModel[];

export type ListSessionsQueryResponse = ListSessions200;

export type ListSessionsQuery = {
    Response: ListSessions200;
    Errors: any;
};

/**
 * @description Query settings successfully
*/
export type QuerySettings200 = RestResponseSystemSettings;

export type QuerySettingsQueryResponse = QuerySettings200;

export type QuerySettingsQuery = {
    Response: QuerySettings200;
    Errors: any;
};

/**
 * @description Update settings successfully
*/
export type UpdateSettings200 = any;

export type UpdateSettingsMutationRequest = SystemSettings;

export type UpdateSettingsMutationResponse = UpdateSettings200;

export type UpdateSettingsMutation = {
    Response: UpdateSettings200;
    Request: UpdateSettingsMutationRequest;
    Errors: any;
};

export type OpenSignalingHandleQueryParams = {
    /**
     * @description The version of the API. This is a simple integer that increments when API is changed.
     * @type integer, int32
    */
    api_version: number;
    /**
     * @description The build number of the server.
     * @type integer, int32
    */
    build_number: number;
    /**
     * @description The commit hash of the server.
     * @type string
    */
    commit_hash: string;
    /**
     * @description Remote Desk Type Enum
     * @type string
    */
    remote_desk_type: RemoteDeskTypeEnum;
    /**
     * @description Operation system enum
     * @type string
    */
    operation_system: OperationSystemEnum;
    /**
     * @description Display name of the remote desk.
     * @type string,null
    */
    display_name?: string | null;
    /**
     * @description Client ID of the server.
     * @type string,null
    */
    client_id?: string | null;
};

/**
 * @description return websocket stream
*/
export type OpenSignalingHandle200 = any;

export type OpenSignalingHandleQueryResponse = OpenSignalingHandle200;

export type OpenSignalingHandleQuery = {
    Response: OpenSignalingHandle200;
    QueryParams: OpenSignalingHandleQueryParams;
    Errors: any;
};

/**
 * @description Get system information successfully
*/
export type QuerySysinfo200 = RestResponseSystemInfo;

export type QuerySysinfoQueryResponse = QuerySysinfo200;

export type QuerySysinfoQuery = {
    Response: QuerySysinfo200;
    Errors: any;
};

/**
 * @description Update telemetry consent successfully
*/
export type UpdateTelemetryConsent200 = any;

export type UpdateTelemetryConsentMutationRequest = TelemetryConsent;

export type UpdateTelemetryConsentMutationResponse = UpdateTelemetryConsent200;

export type UpdateTelemetryConsentMutation = {
    Response: UpdateTelemetryConsent200;
    Request: UpdateTelemetryConsentMutationRequest;
    Errors: any;
};

/**
 * @description Query telemetry status successfully
*/
export type QueryTelemetryStatus200 = RestResponseTelemetryStatus;

export type QueryTelemetryStatusQueryResponse = QueryTelemetryStatus200;

export type QueryTelemetryStatusQuery = {
    Response: QueryTelemetryStatus200;
    Errors: any;
};

export type OpenTerminalSessionPathParams = {
    /**
     * @description session id
     * @type string
    */
    session_id: string;
};

export type OpenTerminalSessionQueryParams = {
    /**
     * @description The command to start the terminal session. with the format of \"path/to/executable,arg1,arg2\"
     * @type string
    */
    command: string;
};

/**
 * @description return websocket stream
*/
export type OpenTerminalSession200 = any;

export type OpenTerminalSessionQueryResponse = OpenTerminalSession200;

export type OpenTerminalSessionQuery = {
    Response: OpenTerminalSession200;
    PathParams: OpenTerminalSessionPathParams;
    QueryParams: OpenTerminalSessionQueryParams;
    Errors: any;
};

export type ListTerminalPathParams = {
    /**
     * @description session id
     * @type string
    */
    session_id: string;
};

/**
 * @description return terminal command list
*/
export type ListTerminal200 = TerminalList;

export type ListTerminalQueryResponse = ListTerminal200;

export type ListTerminalQuery = {
    Response: ListTerminal200;
    PathParams: ListTerminalPathParams;
    Errors: any;
};

/**
 * @description System initialized successfully
*/
export type InitSystem200 = any;

/**
 * @description System already initialized
*/
export type InitSystem403 = any;

export type InitSystemMutationRequest = InitParams;

export type InitSystemMutationResponse = InitSystem200;

export type InitSystemMutation = {
    Response: InitSystem200;
    Request: InitSystemMutationRequest;
    Errors: InitSystem403;
};

/**
 * @description Login result
*/
export type LoginAccount200 = LoginResult;

/**
 * @description Illegal username or password
*/
export type LoginAccount403 = any;

export type LoginAccountMutationRequest = LoginParams;

export type LoginAccountMutationResponse = LoginAccount200;

export type LoginAccountMutation = {
    Response: LoginAccount200;
    Request: LoginAccountMutationRequest;
    Errors: LoginAccount403;
};

/**
 * @description Get captcha successfully
*/
export type GetCaptcha200 = FakeCaptcha;

/**
 * @description Bad request
*/
export type GetCaptcha400 = any;

/**
 * @description Not implemented
*/
export type GetCaptcha501 = any;

export type GetCaptchaMutationRequest = FakeCaptchaParams;

export type GetCaptchaMutationResponse = GetCaptcha200;

export type GetCaptchaMutation = {
    Response: GetCaptcha200;
    Request: GetCaptchaMutationRequest;
    Errors: GetCaptcha400 | GetCaptcha501;
};

/**
 * @description Logout successful
*/
export type LogoutAccount200 = any;

export type LogoutAccountMutationResponse = LogoutAccount200;

export type LogoutAccountMutation = {
    Response: LogoutAccount200;
    Errors: any;
};

export type LoginTauriQueryParams = {
    /**
     * @description One-time login token generated by Tauri
     * @type string
    */
    token: string;
};

/**
 * @description Login result
*/
export type LoginTauri200 = LoginResult;

/**
 * @description Invalid or expired token
*/
export type LoginTauri403 = any;

export type LoginTauriMutationResponse = LoginTauri200;

export type LoginTauriMutation = {
    Response: LoginTauri200;
    QueryParams: LoginTauriQueryParams;
    Errors: LoginTauri403;
};

/**
 * @description Get server information successfully
*/
export type QueryServerInfo200 = RestResponseServerInfo;

export type QueryServerInfoQueryResponse = QueryServerInfo200;

export type QueryServerInfoQuery = {
    Response: QueryServerInfo200;
    Errors: any;
};

/**
 * @description Turn server info
*/
export type GetTurnInfo200 = TurnInfo;

export type GetTurnInfoQueryResponse = GetTurnInfo200;

export type GetTurnInfoQuery = {
    Response: GetTurnInfo200;
    Errors: any;
};

/**
 * @description turn server metrics
*/
export type GetTurnMetrics200 = string;

/**
 * @description Expectation failed
*/
export type GetTurnMetrics417 = any;

export type GetTurnMetricsQueryResponse = GetTurnMetrics200;

export type GetTurnMetricsQuery = {
    Response: GetTurnMetrics200;
    Errors: GetTurnMetrics417;
};

export type GetTurnSessionQueryParams = {
    /**
     * @type string
    */
    address: string;
    /**
     * @type string
    */
    interface: string;
};

/**
 * @description Turn server session
*/
export type GetTurnSession200 = TurnSession;

export type GetTurnSessionQueryResponse = GetTurnSession200;

export type GetTurnSessionQuery = {
    Response: GetTurnSession200;
    QueryParams: GetTurnSessionQueryParams;
    Errors: any;
};

export type DeleteTurnSessionQueryParams = {
    /**
     * @type string
    */
    address: string;
    /**
     * @type string
    */
    interface: string;
};

/**
 * @description Deleted turn server session
*/
export type DeleteTurnSession200 = any;

/**
 * @description Expectation failed
*/
export type DeleteTurnSession417 = any;

export type DeleteTurnSessionMutationResponse = DeleteTurnSession200;

export type DeleteTurnSessionMutation = {
    Response: DeleteTurnSession200;
    QueryParams: DeleteTurnSessionQueryParams;
    Errors: DeleteTurnSession417;
};

export type GetTurnSessionStatisticsQueryParams = {
    /**
     * @type string
    */
    address: string;
    /**
     * @type string
    */
    interface: string;
};

/**
 * @description Turn server session statistics
*/
export type GetTurnSessionStatistics200 = TurnSessionStatistics;

/**
 * @description Turn server session not found
*/
export type GetTurnSessionStatistics404 = any;

export type GetTurnSessionStatisticsQueryResponse = GetTurnSessionStatistics200;

export type GetTurnSessionStatisticsQuery = {
    Response: GetTurnSessionStatistics200;
    QueryParams: GetTurnSessionStatisticsQueryParams;
    Errors: GetTurnSessionStatistics404;
};