/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeleteFileMutationRequest, DeleteFileMutationResponse, DeleteFile400, DeleteFile501 } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteFile } from "../../clients.ts";

export const deleteFileMutationKey = () => [{ url: '/api/desk/file' }] as const

export type DeleteFileMutationKey = ReturnType<typeof deleteFileMutationKey>

export function deleteFileMutationOptions<TContext = unknown>(config: Partial<RequestConfig<DeleteFileMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = deleteFileMutationKey()
        return mutationOptions<DeleteFileMutationResponse, ResponseErrorConfig<DeleteFile400 | DeleteFile501>, {data: DeleteFileMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return deleteFile(data, config)
          },
        })

}

/**
 * @summary Delete a file
 * {@link /api/desk/file}
 */
export function useDeleteFile<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteFileMutationResponse, ResponseErrorConfig<DeleteFile400 | DeleteFile501>, {data: DeleteFileMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<DeleteFileMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteFileMutationKey()

          const baseOptions = deleteFileMutationOptions(config) as UseMutationOptions<DeleteFileMutationResponse, ResponseErrorConfig<DeleteFile400 | DeleteFile501>, {data: DeleteFileMutationRequest}, TContext>
          

          return useMutation<DeleteFileMutationResponse, ResponseErrorConfig<DeleteFile400 | DeleteFile501>, {data: DeleteFileMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteFileMutationResponse, ResponseErrorConfig<DeleteFile400 | DeleteFile501>, {data: DeleteFileMutationRequest}, TContext>
      
}