/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { GetTurnInfoQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getTurnInfo } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getTurnInfoQueryKey = () => [{ url: '/api/turn/info' }] as const

export type GetTurnInfoQueryKey = ReturnType<typeof getTurnInfoQueryKey>

export function getTurnInfoQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTurnInfoQueryKey()
        return queryOptions<GetTurnInfoQueryResponse, ResponseErrorConfig<Error>, GetTurnInfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getTurnInfo(config)
         },
        })

}

/**
 * @summary Get turn server info
 * {@link /api/turn/info}
 */
export function useGetTurnInfo<TData = GetTurnInfoQueryResponse, TQueryData = GetTurnInfoQueryResponse, TQueryKey extends QueryKey = GetTurnInfoQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetTurnInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getTurnInfoQueryKey()
         

         const query = useQuery({
          ...getTurnInfoQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}