/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetTurnInfoQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getTurnInfo } from "../../clients.ts";

export const getTurnInfoSuspenseQueryKey = () => [{ url: '/api/turn/info' }] as const

export type GetTurnInfoSuspenseQueryKey = ReturnType<typeof getTurnInfoSuspenseQueryKey>

export function getTurnInfoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getTurnInfoSuspenseQueryKey()
        return queryOptions<GetTurnInfoQueryResponse, ResponseErrorConfig<Error>, GetTurnInfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getTurnInfo(config)
         },
        })

}

/**
 * @summary Get turn server info
 * {@link /api/turn/info}
 */
export function useGetTurnInfoSuspense<TData = GetTurnInfoQueryResponse, TQueryKey extends QueryKey = GetTurnInfoSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetTurnInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getTurnInfoSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getTurnInfoSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}