/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetNoticesQueryResponse, GetNotices401 } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getNotices } from "../../clients.ts";

export const getNoticesQueryKey = () => [{ url: '/api/notices' }] as const

export type GetNoticesQueryKey = ReturnType<typeof getNoticesQueryKey>

export function getNoticesQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getNoticesQueryKey()
        return queryOptions<GetNoticesQueryResponse, ResponseErrorConfig<GetNotices401>, GetNoticesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getNotices(config)
         },
        })

}

/**
 * @summary Get notices
 * {@link /api/notices}
 */
export function useGetNotices<TData = GetNoticesQueryResponse, TQueryData = GetNoticesQueryResponse, TQueryKey extends QueryKey = GetNoticesQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetNoticesQueryResponse, ResponseErrorConfig<GetNotices401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getNoticesQueryKey()
         

         const query = useQuery({
          ...getNoticesQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetNotices401>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}