/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { InstallServiceMutationResponse, InstallService503 } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { installService } from "../../clients.ts";

export const installServiceMutationKey = () => [{ url: '/api/service/install' }] as const

export type InstallServiceMutationKey = ReturnType<typeof installServiceMutationKey>

export function installServiceMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = installServiceMutationKey()
        return mutationOptions<InstallServiceMutationResponse, ResponseErrorConfig<InstallService503>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return installService(config)
          },
        })

}

/**
 * @description The HTTP handler is stateless: it sends a command to Tauri via the
 * `service_op_sender` channel and returns 202 Accepted immediately.
 * The caller should poll `GET /api/server_info` to check `service_installed`.
 * @summary Install OS system service
 * {@link /api/service/install}
 */
export function useInstallService<TContext>(options: 
{
  mutation?: UseMutationOptions<InstallServiceMutationResponse, ResponseErrorConfig<InstallService503>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? installServiceMutationKey()

          const baseOptions = installServiceMutationOptions(config) as UseMutationOptions<InstallServiceMutationResponse, ResponseErrorConfig<InstallService503>, void, TContext>
          

          return useMutation<InstallServiceMutationResponse, ResponseErrorConfig<InstallService503>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<InstallServiceMutationResponse, ResponseErrorConfig<InstallService503>, void, TContext>
      
}