/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListTerminalQueryResponse, ListTerminalPathParams } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { listTerminal } from "../../clients.ts";

export const listTerminalQueryKey = (connection_id: ListTerminalPathParams["connection_id"]) => [{ url: '/api/desk/terminals/:connection_id', params: {connection_id:connection_id} }] as const

export type ListTerminalQueryKey = ReturnType<typeof listTerminalQueryKey>

export function listTerminalQueryOptions(connection_id: ListTerminalPathParams["connection_id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listTerminalQueryKey(connection_id)
        return queryOptions<ListTerminalQueryResponse, ResponseErrorConfig<Error>, ListTerminalQueryResponse, typeof queryKey>({
         enabled: !!(connection_id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return listTerminal(connection_id, config)
         },
        })

}

/**
 * @summary List terminal
 * {@link /api/desk/terminals/:connection_id}
 */
export function useListTerminal<TData = ListTerminalQueryResponse, TQueryData = ListTerminalQueryResponse, TQueryKey extends QueryKey = ListTerminalQueryKey>(connection_id: ListTerminalPathParams["connection_id"], options: 
{
  query?: Partial<QueryObserverOptions<ListTerminalQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? listTerminalQueryKey(connection_id)
         

         const query = useQuery({
          ...listTerminalQueryOptions(connection_id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}