/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { ListSessionsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { listSessions } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listSessionsSuspenseQueryKey = () => [{ url: '/api/desk/sessions' }] as const

export type ListSessionsSuspenseQueryKey = ReturnType<typeof listSessionsSuspenseQueryKey>

export function listSessionsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listSessionsSuspenseQueryKey()
        return queryOptions<ListSessionsQueryResponse, ResponseErrorConfig<Error>, ListSessionsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return listSessions(config)
         },
        })

}

/**
 * @summary List all online desk sessions
 * {@link /api/desk/sessions}
 */
export function useListSessionsSuspense<TData = ListSessionsQueryResponse, TQueryKey extends QueryKey = ListSessionsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListSessionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? listSessionsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...listSessionsSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}