/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { ListTerminalQueryResponse, ListTerminalPathParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { listTerminal } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listTerminalSuspenseQueryKey = (session_id: ListTerminalPathParams["session_id"]) => [{ url: '/api/desk/terminals/:session_id', params: {session_id:session_id} }] as const

export type ListTerminalSuspenseQueryKey = ReturnType<typeof listTerminalSuspenseQueryKey>

export function listTerminalSuspenseQueryOptions(session_id: ListTerminalPathParams["session_id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listTerminalSuspenseQueryKey(session_id)
        return queryOptions<ListTerminalQueryResponse, ResponseErrorConfig<Error>, ListTerminalQueryResponse, typeof queryKey>({
         enabled: !!(session_id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return listTerminal(session_id, config)
         },
        })

}

/**
 * @summary List terminal
 * {@link /api/desk/terminals/:session_id}
 */
export function useListTerminalSuspense<TData = ListTerminalQueryResponse, TQueryKey extends QueryKey = ListTerminalSuspenseQueryKey>(session_id: ListTerminalPathParams["session_id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListTerminalQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? listTerminalSuspenseQueryKey(session_id)
         

         const query = useSuspenseQuery({
          ...listTerminalSuspenseQueryOptions(session_id, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}