/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { ListSessionsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listSessions } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listSessionsQueryKey = () => [{ url: '/api/desk/sessions' }] as const

export type ListSessionsQueryKey = ReturnType<typeof listSessionsQueryKey>

export function listSessionsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listSessionsQueryKey()
        return queryOptions<ListSessionsQueryResponse, ResponseErrorConfig<Error>, ListSessionsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return listSessions(config)
         },
        })

}

/**
 * @summary List all online desk sessions
 * {@link /api/desk/sessions}
 */
export function useListSessions<TData = ListSessionsQueryResponse, TQueryData = ListSessionsQueryResponse, TQueryKey extends QueryKey = ListSessionsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ListSessionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? listSessionsQueryKey()
         

         const query = useQuery({
          ...listSessionsQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}