/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { OpenTerminalSessionQueryResponse, OpenTerminalSessionPathParams, OpenTerminalSessionQueryParams } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { openTerminalSession } from "../../clients.ts";

export const openTerminalSessionSuspenseQueryKey = (connection_id: OpenTerminalSessionPathParams["connection_id"], params: OpenTerminalSessionQueryParams) => [{ url: '/api/desk/terminal/:connection_id', params: {connection_id:connection_id} }, ...(params ? [params] : [])] as const

export type OpenTerminalSessionSuspenseQueryKey = ReturnType<typeof openTerminalSessionSuspenseQueryKey>

export function openTerminalSessionSuspenseQueryOptions(connection_id: OpenTerminalSessionPathParams["connection_id"], params: OpenTerminalSessionQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = openTerminalSessionSuspenseQueryKey(connection_id, params)
        return queryOptions<OpenTerminalSessionQueryResponse, ResponseErrorConfig<Error>, OpenTerminalSessionQueryResponse, typeof queryKey>({
         enabled: !!(connection_id&& params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return openTerminalSession(connection_id, params, config)
         },
        })

}

/**
 * @summary Open terminal connection
 * {@link /api/desk/terminal/:connection_id}
 */
export function useOpenTerminalSessionSuspense<TData = OpenTerminalSessionQueryResponse, TQueryKey extends QueryKey = OpenTerminalSessionSuspenseQueryKey>(connection_id: OpenTerminalSessionPathParams["connection_id"], params: OpenTerminalSessionQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<OpenTerminalSessionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? openTerminalSessionSuspenseQueryKey(connection_id, params)
         

         const query = useSuspenseQuery({
          ...openTerminalSessionSuspenseQueryOptions(connection_id, params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}