/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { QueryTelemetryStatusQueryResponse } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { queryTelemetryStatus } from "../../clients.ts";

export const queryTelemetryStatusQueryKey = () => [{ url: '/api/desk/telemetry/status' }] as const

export type QueryTelemetryStatusQueryKey = ReturnType<typeof queryTelemetryStatusQueryKey>

export function queryTelemetryStatusQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryTelemetryStatusQueryKey()
        return queryOptions<QueryTelemetryStatusQueryResponse, ResponseErrorConfig<Error>, QueryTelemetryStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return queryTelemetryStatus(config)
         },
        })

}

/**
 * @summary Query telemetry status
 * {@link /api/desk/telemetry/status}
 */
export function useQueryTelemetryStatus<TData = QueryTelemetryStatusQueryResponse, TQueryData = QueryTelemetryStatusQueryResponse, TQueryKey extends QueryKey = QueryTelemetryStatusQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<QueryTelemetryStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? queryTelemetryStatusQueryKey()
         

         const query = useQuery({
          ...queryTelemetryStatusQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}