/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QuerySettingsQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { querySettings } from "../../clients.ts";

export const querySettingsSuspenseQueryKey = () => [{ url: '/api/desk/settings' }] as const

export type QuerySettingsSuspenseQueryKey = ReturnType<typeof querySettingsSuspenseQueryKey>

export function querySettingsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = querySettingsSuspenseQueryKey()
        return queryOptions<QuerySettingsQueryResponse, ResponseErrorConfig<Error>, QuerySettingsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return querySettings(config)
         },
        })

}

/**
 * @summary Query settings
 * {@link /api/desk/settings}
 */
export function useQuerySettingsSuspense<TData = QuerySettingsQueryResponse, TQueryKey extends QueryKey = QuerySettingsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QuerySettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? querySettingsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...querySettingsSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}