/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QuerySysinfoQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { querySysinfo } from "../../clients.ts";

export const querySysinfoSuspenseQueryKey = () => [{ url: '/api/desk/sysinfo' }] as const

export type QuerySysinfoSuspenseQueryKey = ReturnType<typeof querySysinfoSuspenseQueryKey>

export function querySysinfoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = querySysinfoSuspenseQueryKey()
        return queryOptions<QuerySysinfoQueryResponse, ResponseErrorConfig<Error>, QuerySysinfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return querySysinfo(config)
         },
        })

}

/**
 * @summary Get system information
 * {@link /api/desk/sysinfo}
 */
export function useQuerySysinfoSuspense<TData = QuerySysinfoQueryResponse, TQueryKey extends QueryKey = QuerySysinfoSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QuerySysinfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? querySysinfoSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...querySysinfoSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}