/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { QueryTelemetryStatusQueryResponse } from "../../types.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { queryTelemetryStatus } from "../../clients.ts";

export const queryTelemetryStatusSuspenseQueryKey = () => [{ url: '/api/desk/telemetry/status' }] as const

export type QueryTelemetryStatusSuspenseQueryKey = ReturnType<typeof queryTelemetryStatusSuspenseQueryKey>

export function queryTelemetryStatusSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = queryTelemetryStatusSuspenseQueryKey()
        return queryOptions<QueryTelemetryStatusQueryResponse, ResponseErrorConfig<Error>, QueryTelemetryStatusQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return queryTelemetryStatus(config)
         },
        })

}

/**
 * @summary Query telemetry status
 * {@link /api/desk/telemetry/status}
 */
export function useQueryTelemetryStatusSuspense<TData = QueryTelemetryStatusQueryResponse, TQueryKey extends QueryKey = QueryTelemetryStatusSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<QueryTelemetryStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? queryTelemetryStatusSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...queryTelemetryStatusSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}