/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateComputerUseCommunicationPolicyMutationRequest, UpdateComputerUseCommunicationPolicyMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateComputerUseCommunicationPolicy } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateComputerUseCommunicationPolicyMutationKey = () => [{ url: '/api/desk/settings/computer-use-communication' }] as const

export type UpdateComputerUseCommunicationPolicyMutationKey = ReturnType<typeof updateComputerUseCommunicationPolicyMutationKey>

export function updateComputerUseCommunicationPolicyMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateComputerUseCommunicationPolicyMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateComputerUseCommunicationPolicyMutationKey()
        return mutationOptions<UpdateComputerUseCommunicationPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateComputerUseCommunicationPolicyMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return updateComputerUseCommunicationPolicy(data, config)
          },
        })

}

/**
 * @summary Update the local Computer Use communication switches
 * {@link /api/desk/settings/computer-use-communication}
 */
export function useUpdateComputerUseCommunicationPolicy<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateComputerUseCommunicationPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateComputerUseCommunicationPolicyMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateComputerUseCommunicationPolicyMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateComputerUseCommunicationPolicyMutationKey()

          const baseOptions = updateComputerUseCommunicationPolicyMutationOptions(config) as UseMutationOptions<UpdateComputerUseCommunicationPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateComputerUseCommunicationPolicyMutationRequest}, TContext>
          

          return useMutation<UpdateComputerUseCommunicationPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateComputerUseCommunicationPolicyMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateComputerUseCommunicationPolicyMutationResponse, ResponseErrorConfig<Error>, {data: UpdateComputerUseCommunicationPolicyMutationRequest}, TContext>
      
}