/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetModelUsageQueryResponse, GetModelUsageQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getModelUsage } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getModelUsageSuspenseQueryKey = (params?: GetModelUsageQueryParams) => [{ url: '/api/model/usage' }, ...(params ? [params] : [])] as const

export type GetModelUsageSuspenseQueryKey = ReturnType<typeof getModelUsageSuspenseQueryKey>

export function getModelUsageSuspenseQueryOptions(params?: GetModelUsageQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getModelUsageSuspenseQueryKey(params)
        return queryOptions<GetModelUsageQueryResponse, ResponseErrorConfig<Error>, GetModelUsageQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getModelUsage(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Query local per-model AI gateway token usage
 * {@link /api/model/usage}
 */
export function useGetModelUsageSuspense<TData = GetModelUsageQueryResponse, TQueryKey extends QueryKey = GetModelUsageSuspenseQueryKey>(params?: GetModelUsageQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetModelUsageQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getModelUsageSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getModelUsageSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}