/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  ChangePasswordMutationRequest,
  ChangePasswordMutationResponse,
  ChangePassword403,
} from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { changePassword } from "../../clients.ts";

export const changePasswordMutationKey = () =>
  [{ url: "/api/desk/api/login/password" }] as const;

export type ChangePasswordMutationKey = ReturnType<
  typeof changePasswordMutationKey
>;

export function changePasswordMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<ChangePasswordMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = changePasswordMutationKey();
  return mutationOptions<
    ChangePasswordMutationResponse,
    ResponseErrorConfig<ChangePassword403>,
    { data: ChangePasswordMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return changePassword(data, config);
    },
  });
}

/**
 * @summary Change password of user account
 * {@link /api/desk/api/login/password}
 */
export function useChangePassword<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ChangePasswordMutationResponse,
      ResponseErrorConfig<ChangePassword403>,
      { data: ChangePasswordMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<ChangePasswordMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? changePasswordMutationKey();

  const baseOptions = changePasswordMutationOptions(
    config,
  ) as UseMutationOptions<
    ChangePasswordMutationResponse,
    ResponseErrorConfig<ChangePassword403>,
    { data: ChangePasswordMutationRequest },
    TContext
  >;

  return useMutation<
    ChangePasswordMutationResponse,
    ResponseErrorConfig<ChangePassword403>,
    { data: ChangePasswordMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ChangePasswordMutationResponse,
    ResponseErrorConfig<ChangePassword403>,
    { data: ChangePasswordMutationRequest },
    TContext
  >;
}
