/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  LoginAccountMutationRequest,
  LoginAccountMutationResponse,
  LoginAccount403,
} from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { loginAccount } from "../../clients.ts";

export const loginAccountMutationKey = () =>
  [{ url: "/api/login/account" }] as const;

export type LoginAccountMutationKey = ReturnType<
  typeof loginAccountMutationKey
>;

export function loginAccountMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<LoginAccountMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = loginAccountMutationKey();
  return mutationOptions<
    LoginAccountMutationResponse,
    ResponseErrorConfig<LoginAccount403>,
    { data: LoginAccountMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return loginAccount(data, config);
    },
  });
}

/**
 * @summary Login user account
 * {@link /api/login/account}
 */
export function useLoginAccount<TContext>(
  options: {
    mutation?: UseMutationOptions<
      LoginAccountMutationResponse,
      ResponseErrorConfig<LoginAccount403>,
      { data: LoginAccountMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<LoginAccountMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? loginAccountMutationKey();

  const baseOptions = loginAccountMutationOptions(config) as UseMutationOptions<
    LoginAccountMutationResponse,
    ResponseErrorConfig<LoginAccount403>,
    { data: LoginAccountMutationRequest },
    TContext
  >;

  return useMutation<
    LoginAccountMutationResponse,
    ResponseErrorConfig<LoginAccount403>,
    { data: LoginAccountMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    LoginAccountMutationResponse,
    ResponseErrorConfig<LoginAccount403>,
    { data: LoginAccountMutationRequest },
    TContext
  >;
}
