/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { LogoutAccountMutationResponse } from "../../types.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { logoutAccount } from "../../clients.ts";

export const logoutAccountMutationKey = () => [{ url: '/api/login/outLogin' }] as const

export type LogoutAccountMutationKey = ReturnType<typeof logoutAccountMutationKey>

export function logoutAccountMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = logoutAccountMutationKey()
        return mutationOptions<LogoutAccountMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return logoutAccount(config)
          },
        })

}

/**
 * @summary Logout user account
 * {@link /api/login/outLogin}
 */
export function useLogoutAccount<TContext>(options: 
{
  mutation?: UseMutationOptions<LogoutAccountMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? logoutAccountMutationKey()

          const baseOptions = logoutAccountMutationOptions(config) as UseMutationOptions<LogoutAccountMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<LogoutAccountMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<LogoutAccountMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}