/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListTerminalQueryResponse, ListTerminalPathParams, ListTerminalQueryParams } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listTerminal } from "../../clients.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listTerminalQueryKey = (connection_id: ListTerminalPathParams["connection_id"] | undefined, params?: ListTerminalQueryParams) => [{ url: '/api/desk/terminals/:connection_id', params: {connection_id:connection_id} }, ...(params ? [params] : [])] as const

export type ListTerminalQueryKey = ReturnType<typeof listTerminalQueryKey>

export function listTerminalQueryOptions(connection_id: ListTerminalPathParams["connection_id"] | undefined, params?: ListTerminalQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listTerminalQueryKey(connection_id, params)
        return queryOptions<ListTerminalQueryResponse, ResponseErrorConfig<Error>, ListTerminalQueryResponse, typeof queryKey>({
         enabled: !!(connection_id),
         queryKey,
         queryFn: async ({ signal }) => {
            return listTerminal(connection_id!, params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List terminal commands on remote desk
 * {@link /api/desk/terminals/:connection_id}
 */
export function useListTerminal<TData = ListTerminalQueryResponse, TQueryData = ListTerminalQueryResponse, TQueryKey extends QueryKey = ListTerminalQueryKey>(connection_id: ListTerminalPathParams["connection_id"] | undefined, params?: ListTerminalQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListTerminalQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listTerminalQueryKey(connection_id, params)
         

         const query = useQuery({
          ...listTerminalQueryOptions(connection_id, params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}