/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { OpenTerminalSessionQueryResponse, OpenTerminalSessionPathParams, OpenTerminalSessionQueryParams } from "../../types.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { openTerminalSession } from "../../clients.ts";

export const openTerminalSessionQueryKey = (connection_id: OpenTerminalSessionPathParams["connection_id"], params: OpenTerminalSessionQueryParams) => [{ url: '/api/desk/terminal/:connection_id', params: {connection_id:connection_id} }, ...(params ? [params] : [])] as const

export type OpenTerminalSessionQueryKey = ReturnType<typeof openTerminalSessionQueryKey>

export function openTerminalSessionQueryOptions(connection_id: OpenTerminalSessionPathParams["connection_id"], params: OpenTerminalSessionQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = openTerminalSessionQueryKey(connection_id, params)
        return queryOptions<OpenTerminalSessionQueryResponse, ResponseErrorConfig<Error>, OpenTerminalSessionQueryResponse, typeof queryKey>({
         enabled: !!(connection_id&& params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return openTerminalSession(connection_id, params, config)
         },
        })

}

/**
 * @summary Open terminal connection
 * {@link /api/desk/terminal/:connection_id}
 */
export function useOpenTerminalSession<TData = OpenTerminalSessionQueryResponse, TQueryData = OpenTerminalSessionQueryResponse, TQueryKey extends QueryKey = OpenTerminalSessionQueryKey>(connection_id: OpenTerminalSessionPathParams["connection_id"], params: OpenTerminalSessionQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<OpenTerminalSessionQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? openTerminalSessionQueryKey(connection_id, params)
         

         const query = useQuery({
          ...openTerminalSessionQueryOptions(connection_id, params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}