/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListConnectionsQueryResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { listConnections } from "../../clients.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listConnectionsSuspenseQueryKey = () => [{ url: '/api/desk/connections' }] as const

export type ListConnectionsSuspenseQueryKey = ReturnType<typeof listConnectionsSuspenseQueryKey>

export function listConnectionsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listConnectionsSuspenseQueryKey()
        return queryOptions<ListConnectionsQueryResponse, ResponseErrorConfig<Error>, ListConnectionsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listConnections({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List all online desk connections
 * {@link /api/desk/connections}
 */
export function useListConnectionsSuspense<TData = ListConnectionsQueryResponse, TQueryKey extends QueryKey = ListConnectionsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListConnectionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listConnectionsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...listConnectionsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}