/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VerifyConnectionMutationRequest, VerifyConnectionMutationResponse } from "../../types.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { verifyConnection } from "../../clients.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const verifyConnectionMutationKey = () => [{ url: '/api/connection/verify' }] as const

export type VerifyConnectionMutationKey = ReturnType<typeof verifyConnectionMutationKey>

export function verifyConnectionMutationOptions<TContext = unknown>(config: Partial<RequestConfig<VerifyConnectionMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = verifyConnectionMutationKey()
        return mutationOptions<VerifyConnectionMutationResponse, ResponseErrorConfig<Error>, {data: VerifyConnectionMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return verifyConnection(data, config)
          },
        })

}

/**
 * @summary Verify a signaling / manager connection target
 * {@link /api/connection/verify}
 */
export function useVerifyConnection<TContext>(options: 
{
  mutation?: UseMutationOptions<VerifyConnectionMutationResponse, ResponseErrorConfig<Error>, {data: VerifyConnectionMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<VerifyConnectionMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? verifyConnectionMutationKey()

          const baseOptions = verifyConnectionMutationOptions(config) as UseMutationOptions<VerifyConnectionMutationResponse, ResponseErrorConfig<Error>, {data: VerifyConnectionMutationRequest}, TContext>
          

          return useMutation<VerifyConnectionMutationResponse, ResponseErrorConfig<Error>, {data: VerifyConnectionMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<VerifyConnectionMutationResponse, ResponseErrorConfig<Error>, {data: VerifyConnectionMutationRequest}, TContext>
      
}